2024-01-26 17:08:45,857 INFO    StreamThr :3042423 [internal.py:wandb_internal():86] W&B internal server running at pid: 3042423, started at: 2024-01-26 17:08:45.856259
2024-01-26 17:08:45,883 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status
2024-01-26 17:08:45,883 INFO    WriterThread:3042423 [datastore.py:open_for_write():87] open: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/run-36lzu9m5.wandb
2024-01-26 17:08:45,884 DEBUG   SenderThread:3042423 [sender.py:send():382] send: header
2024-01-26 17:08:45,898 DEBUG   SenderThread:3042423 [sender.py:send():382] send: run
2024-01-26 17:08:46,853 INFO    SenderThread:3042423 [dir_watcher.py:__init__():211] watching files in: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/files
2024-01-26 17:08:46,854 INFO    SenderThread:3042423 [sender.py:_start_run_threads():1136] run started: 36lzu9m5 with start time 1706260125.829954
2024-01-26 17:08:46,855 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: check_version
2024-01-26 17:08:46,855 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: check_version
2024-01-26 17:08:47,307 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: run_start
2024-01-26 17:08:47,327 DEBUG   HandlerThread:3042423 [system_info.py:__init__():27] System info init
2024-01-26 17:08:47,327 DEBUG   HandlerThread:3042423 [system_info.py:__init__():42] System info init done
2024-01-26 17:08:47,327 INFO    HandlerThread:3042423 [system_monitor.py:start():194] Starting system monitor
2024-01-26 17:08:47,357 INFO    SystemMonitor:3042423 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-01-26 17:08:47,358 INFO    HandlerThread:3042423 [system_monitor.py:probe():214] Collecting system info
2024-01-26 17:08:47,397 INFO    SystemMonitor:3042423 [interfaces.py:start():190] Started cpu monitoring
2024-01-26 17:08:47,415 INFO    SystemMonitor:3042423 [interfaces.py:start():190] Started disk monitoring
2024-01-26 17:08:47,438 INFO    SystemMonitor:3042423 [interfaces.py:start():190] Started gpu monitoring
2024-01-26 17:08:47,447 INFO    SystemMonitor:3042423 [interfaces.py:start():190] Started memory monitoring
2024-01-26 17:08:47,463 INFO    SystemMonitor:3042423 [interfaces.py:start():190] Started network monitoring
2024-01-26 17:08:47,504 DEBUG   HandlerThread:3042423 [system_info.py:probe():151] Probing system
2024-01-26 17:08:47,561 DEBUG   HandlerThread:3042423 [system_info.py:_probe_git():136] Probing git
2024-01-26 17:08:47,614 DEBUG   HandlerThread:3042423 [system_info.py:_probe_git():144] Probing git done
2024-01-26 17:08:47,615 DEBUG   HandlerThread:3042423 [system_info.py:probe():199] Probing system done
2024-01-26 17:08:47,615 DEBUG   HandlerThread:3042423 [system_monitor.py:probe():223] {'os': 'Linux-5.15.0-91-generic-x86_64-with-glibc2.17', 'python': '3.8.17', 'heartbeatAt': '2024-01-26T09:08:47.518037', 'startedAt': '2024-01-26T09:08:45.795893', 'docker': None, 'cuda': None, 'args': ('--local_rank=4', '--config_file', 'config/bert_pretraining_phase2_config.json', '--input_dir', '/home/yanxindong/mkor/bert/data/encoded/sequences_lowercase_max_seq_len_512_next_seq_task_true', '--output_dir', 'results/adam', '--weight_decay', '0.01', '--num_steps_per_checkpoint', '200'), 'state': 'running', 'program': 'run_pretraining.py', 'codePathLocal': 'run_pretraining.py', 'codePath': 'bert/run_pretraining.py', 'git': {'remote': 'https://github.com/kkkjj-d/mkor.git', 'commit': 'efe99e84fef5594780cfb1df6d6a1f61da4ebba0'}, 'email': '1262670315@qq.com', 'root': '/home/yanxindong/mkor', 'host': 'a6000-X640-G40', 'username': 'yanxindong', 'executable': '/home/yanxindong/anaconda/envs/eva/bin/python', 'cpu_count': 64, 'cpu_count_logical': 128, 'cpu_freq': {'current': 2044.7455078125, 'min': 800.0, 'max': 3400.0}, 'cpu_freq_per_core': [{'current': 3300.002, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 923.133, 'min': 800.0, 'max': 3400.0}, {'current': 2100.0, 'min': 800.0, 'max': 3400.0}, {'current': 3182.689, 'min': 800.0, 'max': 3400.0}, {'current': 1700.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3000.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2727.168, 'min': 800.0, 'max': 3400.0}, {'current': 2519.44, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3013.199, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 863.585, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3221.866, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3030.093, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3250.239, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 1700.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3222.118, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2985.634, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3027.036, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3265.661, 'min': 800.0, 'max': 3400.0}, {'current': 3221.967, 'min': 800.0, 'max': 3400.0}, {'current': 857.954, 'min': 800.0, 'max': 3400.0}, {'current': 2900.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2990.769, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3260.823, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2200.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3286.921, 'min': 800.0, 'max': 3400.0}, {'current': 3234.904, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2700.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}], 'disk': {'/': {'total': 438.05088806152344, 'used': 28.042720794677734}}, 'gpu': 'NVIDIA RTX A6000', 'gpu_count': 8, 'gpu_devices': [{'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}], 'memory': {'total': 503.51250076293945}}
2024-01-26 17:08:47,615 INFO    HandlerThread:3042423 [system_monitor.py:probe():224] Finished collecting system info
2024-01-26 17:08:47,615 INFO    HandlerThread:3042423 [system_monitor.py:probe():227] Publishing system info
2024-01-26 17:08:47,615 DEBUG   HandlerThread:3042423 [system_info.py:_save_conda():208] Saving list of conda packages installed into the current environment
2024-01-26 17:08:47,855 INFO    Thread-12 :3042423 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/files/conda-environment.yaml
2024-01-26 17:08:57,856 INFO    Thread-12 :3042423 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/files/conda-environment.yaml
2024-01-26 17:08:57,927 DEBUG   HandlerThread:3042423 [system_info.py:_save_conda():220] Saving conda packages done
2024-01-26 17:08:57,928 INFO    HandlerThread:3042423 [system_monitor.py:probe():229] Finished publishing system info
2024-01-26 17:08:57,934 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:08:57,940 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:08:57,940 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:08:57,940 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:08:57,941 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: python_packages
2024-01-26 17:08:57,941 DEBUG   SenderThread:3042423 [sender.py:send():382] send: files
2024-01-26 17:08:57,941 INFO    SenderThread:3042423 [sender.py:_save_file():1403] saving file wandb-metadata.json with policy now
2024-01-26 17:08:57,942 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: python_packages
2024-01-26 17:08:57,969 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:08:57,970 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:08:57,997 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:08:58,319 DEBUG   SenderThread:3042423 [sender.py:send():382] send: telemetry
2024-01-26 17:08:58,854 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/36lzu9m5/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S5heqgzp0xoicCobJR3AEkRGEKD5qivEoeW9yeHHMvkp0RfgjqZtvgV8WxZzUBJJSwVNyTxJp%2BMabFalIjIllIm2Dciwc86dcBYQVhFpLHl5FcFad38ORK2wjkAx8pomWH9FkYu1swLdy3CRMnpKf%2B9ccuTTTf9M9ZZ7BVc3uTtV3ww5sPa3qkNf2M1k6uwVgtLfhxCEVN5TSR7QG03BRJDuLy3FYfOUClnt%2B%2FWImad9h7KZMyPsXfgAVZHDZK2HlVQ6EhKGVABkKx8BLEAgacPgS3u0Wt49IoDkOd7K%2BLuk7cGyqTjrcB9fQ%2Fb%2Bs6odEbzo9CnGiWOw1ynQ2MYwFg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/36lzu9m5/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S5heqgzp0xoicCobJR3AEkRGEKD5qivEoeW9yeHHMvkp0RfgjqZtvgV8WxZzUBJJSwVNyTxJp%2BMabFalIjIllIm2Dciwc86dcBYQVhFpLHl5FcFad38ORK2wjkAx8pomWH9FkYu1swLdy3CRMnpKf%2B9ccuTTTf9M9ZZ7BVc3uTtV3ww5sPa3qkNf2M1k6uwVgtLfhxCEVN5TSR7QG03BRJDuLy3FYfOUClnt%2B%2FWImad9h7KZMyPsXfgAVZHDZK2HlVQ6EhKGVABkKx8BLEAgacPgS3u0Wt49IoDkOd7K%2BLuk7cGyqTjrcB9fQ%2Fb%2Bs6odEbzo9CnGiWOw1ynQ2MYwFg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c70373970>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:08:58,854 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15648'}
2024-01-26 17:08:58,854 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:08:58,856 INFO    Thread-12 :3042423 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/files/requirements.txt
2024-01-26 17:08:58,856 INFO    Thread-12 :3042423 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/files/wandb-metadata.json
2024-01-26 17:09:00,056 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/36lzu9m5/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S5heqgzp0xoicCobJR3AEkRGEKD5qivEoeW9yeHHMvkp0RfgjqZtvgV8WxZzUBJJSwVNyTxJp%2BMabFalIjIllIm2Dciwc86dcBYQVhFpLHl5FcFad38ORK2wjkAx8pomWH9FkYu1swLdy3CRMnpKf%2B9ccuTTTf9M9ZZ7BVc3uTtV3ww5sPa3qkNf2M1k6uwVgtLfhxCEVN5TSR7QG03BRJDuLy3FYfOUClnt%2B%2FWImad9h7KZMyPsXfgAVZHDZK2HlVQ6EhKGVABkKx8BLEAgacPgS3u0Wt49IoDkOd7K%2BLuk7cGyqTjrcB9fQ%2Fb%2Bs6odEbzo9CnGiWOw1ynQ2MYwFg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/36lzu9m5/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S5heqgzp0xoicCobJR3AEkRGEKD5qivEoeW9yeHHMvkp0RfgjqZtvgV8WxZzUBJJSwVNyTxJp%2BMabFalIjIllIm2Dciwc86dcBYQVhFpLHl5FcFad38ORK2wjkAx8pomWH9FkYu1swLdy3CRMnpKf%2B9ccuTTTf9M9ZZ7BVc3uTtV3ww5sPa3qkNf2M1k6uwVgtLfhxCEVN5TSR7QG03BRJDuLy3FYfOUClnt%2B%2FWImad9h7KZMyPsXfgAVZHDZK2HlVQ6EhKGVABkKx8BLEAgacPgS3u0Wt49IoDkOd7K%2BLuk7cGyqTjrcB9fQ%2Fb%2Bs6odEbzo9CnGiWOw1ynQ2MYwFg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c70373a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:00,056 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15648'}
2024-01-26 17:09:00,056 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:01,320 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:02,308 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/36lzu9m5/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S5heqgzp0xoicCobJR3AEkRGEKD5qivEoeW9yeHHMvkp0RfgjqZtvgV8WxZzUBJJSwVNyTxJp%2BMabFalIjIllIm2Dciwc86dcBYQVhFpLHl5FcFad38ORK2wjkAx8pomWH9FkYu1swLdy3CRMnpKf%2B9ccuTTTf9M9ZZ7BVc3uTtV3ww5sPa3qkNf2M1k6uwVgtLfhxCEVN5TSR7QG03BRJDuLy3FYfOUClnt%2B%2FWImad9h7KZMyPsXfgAVZHDZK2HlVQ6EhKGVABkKx8BLEAgacPgS3u0Wt49IoDkOd7K%2BLuk7cGyqTjrcB9fQ%2Fb%2Bs6odEbzo9CnGiWOw1ynQ2MYwFg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/36lzu9m5/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S5heqgzp0xoicCobJR3AEkRGEKD5qivEoeW9yeHHMvkp0RfgjqZtvgV8WxZzUBJJSwVNyTxJp%2BMabFalIjIllIm2Dciwc86dcBYQVhFpLHl5FcFad38ORK2wjkAx8pomWH9FkYu1swLdy3CRMnpKf%2B9ccuTTTf9M9ZZ7BVc3uTtV3ww5sPa3qkNf2M1k6uwVgtLfhxCEVN5TSR7QG03BRJDuLy3FYfOUClnt%2B%2FWImad9h7KZMyPsXfgAVZHDZK2HlVQ6EhKGVABkKx8BLEAgacPgS3u0Wt49IoDkOd7K%2BLuk7cGyqTjrcB9fQ%2Fb%2Bs6odEbzo9CnGiWOw1ynQ2MYwFg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c703841f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:02,308 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15648'}
2024-01-26 17:09:02,308 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:02,308 INFO    wandb-upload_0:3042423 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8c703841f0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/36lzu9m5/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S5heqgzp0xoicCobJR3AEkRGEKD5qivEoeW9yeHHMvkp0RfgjqZtvgV8WxZzUBJJSwVNyTxJp%2BMabFalIjIllIm2Dciwc86dcBYQVhFpLHl5FcFad38ORK2wjkAx8pomWH9FkYu1swLdy3CRMnpKf%2B9ccuTTTf9M9ZZ7BVc3uTtV3ww5sPa3qkNf2M1k6uwVgtLfhxCEVN5TSR7QG03BRJDuLy3FYfOUClnt%2B%2FWImad9h7KZMyPsXfgAVZHDZK2HlVQ6EhKGVABkKx8BLEAgacPgS3u0Wt49IoDkOd7K%2BLuk7cGyqTjrcB9fQ%2Fb%2Bs6odEbzo9CnGiWOw1ynQ2MYwFg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c703841f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/36lzu9m5/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S5heqgzp0xoicCobJR3AEkRGEKD5qivEoeW9yeHHMvkp0RfgjqZtvgV8WxZzUBJJSwVNyTxJp%2BMabFalIjIllIm2Dciwc86dcBYQVhFpLHl5FcFad38ORK2wjkAx8pomWH9FkYu1swLdy3CRMnpKf%2B9ccuTTTf9M9ZZ7BVc3uTtV3ww5sPa3qkNf2M1k6uwVgtLfhxCEVN5TSR7QG03BRJDuLy3FYfOUClnt%2B%2FWImad9h7KZMyPsXfgAVZHDZK2HlVQ6EhKGVABkKx8BLEAgacPgS3u0Wt49IoDkOd7K%2BLuk7cGyqTjrcB9fQ%2Fb%2Bs6odEbzo9CnGiWOw1ynQ2MYwFg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c703841f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2789, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-01-26 17:09:06,321 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:06,698 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/36lzu9m5/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S5heqgzp0xoicCobJR3AEkRGEKD5qivEoeW9yeHHMvkp0RfgjqZtvgV8WxZzUBJJSwVNyTxJp%2BMabFalIjIllIm2Dciwc86dcBYQVhFpLHl5FcFad38ORK2wjkAx8pomWH9FkYu1swLdy3CRMnpKf%2B9ccuTTTf9M9ZZ7BVc3uTtV3ww5sPa3qkNf2M1k6uwVgtLfhxCEVN5TSR7QG03BRJDuLy3FYfOUClnt%2B%2FWImad9h7KZMyPsXfgAVZHDZK2HlVQ6EhKGVABkKx8BLEAgacPgS3u0Wt49IoDkOd7K%2BLuk7cGyqTjrcB9fQ%2Fb%2Bs6odEbzo9CnGiWOw1ynQ2MYwFg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/36lzu9m5/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S5heqgzp0xoicCobJR3AEkRGEKD5qivEoeW9yeHHMvkp0RfgjqZtvgV8WxZzUBJJSwVNyTxJp%2BMabFalIjIllIm2Dciwc86dcBYQVhFpLHl5FcFad38ORK2wjkAx8pomWH9FkYu1swLdy3CRMnpKf%2B9ccuTTTf9M9ZZ7BVc3uTtV3ww5sPa3qkNf2M1k6uwVgtLfhxCEVN5TSR7QG03BRJDuLy3FYfOUClnt%2B%2FWImad9h7KZMyPsXfgAVZHDZK2HlVQ6EhKGVABkKx8BLEAgacPgS3u0Wt49IoDkOd7K%2BLuk7cGyqTjrcB9fQ%2Fb%2Bs6odEbzo9CnGiWOw1ynQ2MYwFg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c70225df0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:06,698 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15648'}
2024-01-26 17:09:06,698 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:11,321 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:12,958 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:09:12,958 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:09:13,002 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:09:16,314 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/36lzu9m5/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S5heqgzp0xoicCobJR3AEkRGEKD5qivEoeW9yeHHMvkp0RfgjqZtvgV8WxZzUBJJSwVNyTxJp%2BMabFalIjIllIm2Dciwc86dcBYQVhFpLHl5FcFad38ORK2wjkAx8pomWH9FkYu1swLdy3CRMnpKf%2B9ccuTTTf9M9ZZ7BVc3uTtV3ww5sPa3qkNf2M1k6uwVgtLfhxCEVN5TSR7QG03BRJDuLy3FYfOUClnt%2B%2FWImad9h7KZMyPsXfgAVZHDZK2HlVQ6EhKGVABkKx8BLEAgacPgS3u0Wt49IoDkOd7K%2BLuk7cGyqTjrcB9fQ%2Fb%2Bs6odEbzo9CnGiWOw1ynQ2MYwFg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/36lzu9m5/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S5heqgzp0xoicCobJR3AEkRGEKD5qivEoeW9yeHHMvkp0RfgjqZtvgV8WxZzUBJJSwVNyTxJp%2BMabFalIjIllIm2Dciwc86dcBYQVhFpLHl5FcFad38ORK2wjkAx8pomWH9FkYu1swLdy3CRMnpKf%2B9ccuTTTf9M9ZZ7BVc3uTtV3ww5sPa3qkNf2M1k6uwVgtLfhxCEVN5TSR7QG03BRJDuLy3FYfOUClnt%2B%2FWImad9h7KZMyPsXfgAVZHDZK2HlVQ6EhKGVABkKx8BLEAgacPgS3u0Wt49IoDkOd7K%2BLuk7cGyqTjrcB9fQ%2Fb%2Bs6odEbzo9CnGiWOw1ynQ2MYwFg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c703849d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:16,314 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15648'}
2024-01-26 17:09:16,314 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:17,276 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:17,862 INFO    Thread-12 :3042423 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/files/config.yaml
2024-01-26 17:09:22,586 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:27,611 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:27,958 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:09:27,959 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:09:28,012 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:09:32,374 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/36lzu9m5/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S5heqgzp0xoicCobJR3AEkRGEKD5qivEoeW9yeHHMvkp0RfgjqZtvgV8WxZzUBJJSwVNyTxJp%2BMabFalIjIllIm2Dciwc86dcBYQVhFpLHl5FcFad38ORK2wjkAx8pomWH9FkYu1swLdy3CRMnpKf%2B9ccuTTTf9M9ZZ7BVc3uTtV3ww5sPa3qkNf2M1k6uwVgtLfhxCEVN5TSR7QG03BRJDuLy3FYfOUClnt%2B%2FWImad9h7KZMyPsXfgAVZHDZK2HlVQ6EhKGVABkKx8BLEAgacPgS3u0Wt49IoDkOd7K%2BLuk7cGyqTjrcB9fQ%2Fb%2Bs6odEbzo9CnGiWOw1ynQ2MYwFg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/36lzu9m5/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S5heqgzp0xoicCobJR3AEkRGEKD5qivEoeW9yeHHMvkp0RfgjqZtvgV8WxZzUBJJSwVNyTxJp%2BMabFalIjIllIm2Dciwc86dcBYQVhFpLHl5FcFad38ORK2wjkAx8pomWH9FkYu1swLdy3CRMnpKf%2B9ccuTTTf9M9ZZ7BVc3uTtV3ww5sPa3qkNf2M1k6uwVgtLfhxCEVN5TSR7QG03BRJDuLy3FYfOUClnt%2B%2FWImad9h7KZMyPsXfgAVZHDZK2HlVQ6EhKGVABkKx8BLEAgacPgS3u0Wt49IoDkOd7K%2BLuk7cGyqTjrcB9fQ%2Fb%2Bs6odEbzo9CnGiWOw1ynQ2MYwFg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c701dc3a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:32,374 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15648'}
2024-01-26 17:09:32,374 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:33,335 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:38,336 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:42,959 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:09:42,959 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:09:43,002 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:09:44,883 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:47,464 DEBUG   SystemMonitor:3042423 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-01-26 17:09:47,467 DEBUG   SenderThread:3042423 [sender.py:send():382] send: stats
2024-01-26 17:09:50,469 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:55,474 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:57,959 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:09:57,959 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:09:58,002 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:10:01,232 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:06,242 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:09,784 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/36lzu9m5/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S5heqgzp0xoicCobJR3AEkRGEKD5qivEoeW9yeHHMvkp0RfgjqZtvgV8WxZzUBJJSwVNyTxJp%2BMabFalIjIllIm2Dciwc86dcBYQVhFpLHl5FcFad38ORK2wjkAx8pomWH9FkYu1swLdy3CRMnpKf%2B9ccuTTTf9M9ZZ7BVc3uTtV3ww5sPa3qkNf2M1k6uwVgtLfhxCEVN5TSR7QG03BRJDuLy3FYfOUClnt%2B%2FWImad9h7KZMyPsXfgAVZHDZK2HlVQ6EhKGVABkKx8BLEAgacPgS3u0Wt49IoDkOd7K%2BLuk7cGyqTjrcB9fQ%2Fb%2Bs6odEbzo9CnGiWOw1ynQ2MYwFg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/36lzu9m5/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S5heqgzp0xoicCobJR3AEkRGEKD5qivEoeW9yeHHMvkp0RfgjqZtvgV8WxZzUBJJSwVNyTxJp%2BMabFalIjIllIm2Dciwc86dcBYQVhFpLHl5FcFad38ORK2wjkAx8pomWH9FkYu1swLdy3CRMnpKf%2B9ccuTTTf9M9ZZ7BVc3uTtV3ww5sPa3qkNf2M1k6uwVgtLfhxCEVN5TSR7QG03BRJDuLy3FYfOUClnt%2B%2FWImad9h7KZMyPsXfgAVZHDZK2HlVQ6EhKGVABkKx8BLEAgacPgS3u0Wt49IoDkOd7K%2BLuk7cGyqTjrcB9fQ%2Fb%2Bs6odEbzo9CnGiWOw1ynQ2MYwFg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c70373c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:10:09,784 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15648'}
2024-01-26 17:10:09,784 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:10:11,298 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:12,962 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:10:12,962 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:10:13,002 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:10:16,323 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:17,471 DEBUG   SenderThread:3042423 [sender.py:send():382] send: stats
2024-01-26 17:10:21,472 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:26,473 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:27,959 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:10:27,959 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:10:28,001 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:10:32,341 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:34,028 INFO    Thread-12 :3042423 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/files/output.log
2024-01-26 17:10:36,028 INFO    Thread-12 :3042423 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/files/output.log
2024-01-26 17:10:38,200 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:43,201 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:47,172 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:10:47,172 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:10:47,176 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:10:47,707 DEBUG   SenderThread:3042423 [sender.py:send():382] send: stats
2024-01-26 17:10:48,748 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:53,749 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:58,758 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:02,171 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:11:02,172 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:02,214 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:11:04,461 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:09,619 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:14,621 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:16,082 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/36lzu9m5/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S5heqgzp0xoicCobJR3AEkRGEKD5qivEoeW9yeHHMvkp0RfgjqZtvgV8WxZzUBJJSwVNyTxJp%2BMabFalIjIllIm2Dciwc86dcBYQVhFpLHl5FcFad38ORK2wjkAx8pomWH9FkYu1swLdy3CRMnpKf%2B9ccuTTTf9M9ZZ7BVc3uTtV3ww5sPa3qkNf2M1k6uwVgtLfhxCEVN5TSR7QG03BRJDuLy3FYfOUClnt%2B%2FWImad9h7KZMyPsXfgAVZHDZK2HlVQ6EhKGVABkKx8BLEAgacPgS3u0Wt49IoDkOd7K%2BLuk7cGyqTjrcB9fQ%2Fb%2Bs6odEbzo9CnGiWOw1ynQ2MYwFg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/36lzu9m5/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S5heqgzp0xoicCobJR3AEkRGEKD5qivEoeW9yeHHMvkp0RfgjqZtvgV8WxZzUBJJSwVNyTxJp%2BMabFalIjIllIm2Dciwc86dcBYQVhFpLHl5FcFad38ORK2wjkAx8pomWH9FkYu1swLdy3CRMnpKf%2B9ccuTTTf9M9ZZ7BVc3uTtV3ww5sPa3qkNf2M1k6uwVgtLfhxCEVN5TSR7QG03BRJDuLy3FYfOUClnt%2B%2FWImad9h7KZMyPsXfgAVZHDZK2HlVQ6EhKGVABkKx8BLEAgacPgS3u0Wt49IoDkOd7K%2BLuk7cGyqTjrcB9fQ%2Fb%2Bs6odEbzo9CnGiWOw1ynQ2MYwFg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c701dc0a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:11:16,082 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15648'}
2024-01-26 17:11:16,082 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:11:17,172 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:11:17,172 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:17,214 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:11:17,703 DEBUG   SenderThread:3042423 [sender.py:send():382] send: stats
2024-01-26 17:11:19,742 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:24,811 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:29,861 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:32,172 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:11:32,172 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:32,214 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:11:35,532 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:40,533 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:45,534 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:47,172 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:11:47,172 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:47,214 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:11:47,706 DEBUG   SenderThread:3042423 [sender.py:send():382] send: stats
2024-01-26 17:11:50,708 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:55,709 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:00,710 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:02,172 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:12:02,172 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:12:02,214 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:12:06,546 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:11,587 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:16,714 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:17,261 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:12:17,261 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:12:17,261 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:12:17,708 DEBUG   SenderThread:3042423 [sender.py:send():382] send: stats
2024-01-26 17:12:21,787 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:26,854 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:31,875 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:32,172 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:12:32,172 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:12:32,176 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:12:37,514 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:42,790 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:47,172 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:12:47,172 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:12:47,176 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:12:47,711 DEBUG   SenderThread:3042423 [sender.py:send():382] send: stats
2024-01-26 17:12:48,712 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:53,713 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:58,714 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:02,172 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:13:02,173 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:13:02,176 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:13:04,499 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:09,500 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:14,501 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:17,172 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:13:17,173 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:13:17,176 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:13:17,723 DEBUG   SenderThread:3042423 [sender.py:send():382] send: stats
2024-01-26 17:13:19,724 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:24,911 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:29,912 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:30,565 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/36lzu9m5/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S5heqgzp0xoicCobJR3AEkRGEKD5qivEoeW9yeHHMvkp0RfgjqZtvgV8WxZzUBJJSwVNyTxJp%2BMabFalIjIllIm2Dciwc86dcBYQVhFpLHl5FcFad38ORK2wjkAx8pomWH9FkYu1swLdy3CRMnpKf%2B9ccuTTTf9M9ZZ7BVc3uTtV3ww5sPa3qkNf2M1k6uwVgtLfhxCEVN5TSR7QG03BRJDuLy3FYfOUClnt%2B%2FWImad9h7KZMyPsXfgAVZHDZK2HlVQ6EhKGVABkKx8BLEAgacPgS3u0Wt49IoDkOd7K%2BLuk7cGyqTjrcB9fQ%2Fb%2Bs6odEbzo9CnGiWOw1ynQ2MYwFg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/36lzu9m5/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S5heqgzp0xoicCobJR3AEkRGEKD5qivEoeW9yeHHMvkp0RfgjqZtvgV8WxZzUBJJSwVNyTxJp%2BMabFalIjIllIm2Dciwc86dcBYQVhFpLHl5FcFad38ORK2wjkAx8pomWH9FkYu1swLdy3CRMnpKf%2B9ccuTTTf9M9ZZ7BVc3uTtV3ww5sPa3qkNf2M1k6uwVgtLfhxCEVN5TSR7QG03BRJDuLy3FYfOUClnt%2B%2FWImad9h7KZMyPsXfgAVZHDZK2HlVQ6EhKGVABkKx8BLEAgacPgS3u0Wt49IoDkOd7K%2BLuk7cGyqTjrcB9fQ%2Fb%2Bs6odEbzo9CnGiWOw1ynQ2MYwFg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c70373b20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:13:30,565 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15648'}
2024-01-26 17:13:30,565 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:13:32,235 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:13:32,235 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:13:32,236 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:13:35,772 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:40,884 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:45,914 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:47,242 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:13:47,242 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:13:47,242 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:13:47,725 DEBUG   SenderThread:3042423 [sender.py:send():382] send: stats
2024-01-26 17:13:51,884 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:56,922 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:01,927 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:02,173 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:14:02,173 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:14:02,176 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:14:07,524 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:12,525 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:17,173 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:14:17,173 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:14:17,177 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:14:17,727 DEBUG   SenderThread:3042423 [sender.py:send():382] send: stats
2024-01-26 17:14:17,731 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:22,730 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:27,730 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:32,236 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:14:32,236 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:14:32,236 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:14:33,535 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:38,589 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:43,633 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:47,173 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:14:47,173 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:14:47,177 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:14:47,729 DEBUG   SenderThread:3042423 [sender.py:send():382] send: stats
2024-01-26 17:14:48,732 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:53,804 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:58,914 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:02,173 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:15:02,173 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:15:02,177 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:15:04,559 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:09,559 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:14,560 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:17,173 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:15:17,173 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:15:17,177 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:15:17,732 DEBUG   SenderThread:3042423 [sender.py:send():382] send: stats
2024-01-26 17:15:19,736 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:24,742 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:27,050 DEBUG   SenderThread:3042423 [sender.py:send():382] send: exit
2024-01-26 17:15:27,051 INFO    SenderThread:3042423 [sender.py:send_exit():589] handling exit code: 1
2024-01-26 17:15:27,051 INFO    SenderThread:3042423 [sender.py:send_exit():591] handling runtime: 399
2024-01-26 17:15:27,051 INFO    SenderThread:3042423 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-01-26 17:15:27,051 INFO    SenderThread:3042423 [sender.py:send_exit():597] send defer
2024-01-26 17:15:27,052 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:27,052 INFO    HandlerThread:3042423 [handler.py:handle_request_defer():172] handle defer: 0
2024-01-26 17:15:27,052 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:27,052 INFO    SenderThread:3042423 [sender.py:send_request_defer():613] handle sender defer: 0
2024-01-26 17:15:27,052 INFO    SenderThread:3042423 [sender.py:transition_state():617] send defer: 1
2024-01-26 17:15:27,052 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:27,052 INFO    HandlerThread:3042423 [handler.py:handle_request_defer():172] handle defer: 1
2024-01-26 17:15:27,052 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:27,052 INFO    SenderThread:3042423 [sender.py:send_request_defer():613] handle sender defer: 1
2024-01-26 17:15:27,052 INFO    SenderThread:3042423 [sender.py:transition_state():617] send defer: 2
2024-01-26 17:15:27,052 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:27,052 INFO    HandlerThread:3042423 [handler.py:handle_request_defer():172] handle defer: 2
2024-01-26 17:15:27,052 INFO    HandlerThread:3042423 [system_monitor.py:finish():203] Stopping system monitor
2024-01-26 17:15:27,052 DEBUG   SystemMonitor:3042423 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-01-26 17:15:27,052 DEBUG   SystemMonitor:3042423 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-01-26 17:15:27,058 INFO    HandlerThread:3042423 [interfaces.py:finish():202] Joined cpu monitor
2024-01-26 17:15:27,058 INFO    HandlerThread:3042423 [interfaces.py:finish():202] Joined disk monitor
2024-01-26 17:15:27,395 INFO    Thread-12 :3042423 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/files/wandb-summary.json
2024-01-26 17:15:29,406 INFO    Thread-12 :3042423 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/files/output.log
2024-01-26 17:15:38,998 INFO    HandlerThread:3042423 [interfaces.py:finish():202] Joined gpu monitor
2024-01-26 17:15:38,998 INFO    HandlerThread:3042423 [interfaces.py:finish():202] Joined memory monitor
2024-01-26 17:15:38,998 INFO    HandlerThread:3042423 [interfaces.py:finish():202] Joined network monitor
2024-01-26 17:15:38,999 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:15:38,999 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:38,999 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:38,999 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:38,999 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:39,000 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:39,000 INFO    SenderThread:3042423 [sender.py:send_request_defer():613] handle sender defer: 2
2024-01-26 17:15:39,000 INFO    SenderThread:3042423 [sender.py:transition_state():617] send defer: 3
2024-01-26 17:15:39,000 DEBUG   SenderThread:3042423 [sender.py:send():382] send: stats
2024-01-26 17:15:39,001 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:15:39,002 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:39,002 INFO    HandlerThread:3042423 [handler.py:handle_request_defer():172] handle defer: 3
2024-01-26 17:15:39,002 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:39,002 INFO    SenderThread:3042423 [sender.py:send_request_defer():613] handle sender defer: 3
2024-01-26 17:15:39,002 INFO    SenderThread:3042423 [sender.py:transition_state():617] send defer: 4
2024-01-26 17:15:39,002 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:39,002 INFO    HandlerThread:3042423 [handler.py:handle_request_defer():172] handle defer: 4
2024-01-26 17:15:39,002 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:39,002 INFO    SenderThread:3042423 [sender.py:send_request_defer():613] handle sender defer: 4
2024-01-26 17:15:39,002 INFO    SenderThread:3042423 [sender.py:transition_state():617] send defer: 5
2024-01-26 17:15:39,002 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:39,002 INFO    HandlerThread:3042423 [handler.py:handle_request_defer():172] handle defer: 5
2024-01-26 17:15:39,003 DEBUG   SenderThread:3042423 [sender.py:send():382] send: summary
2024-01-26 17:15:39,003 INFO    SenderThread:3042423 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-01-26 17:15:39,003 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:39,003 INFO    SenderThread:3042423 [sender.py:send_request_defer():613] handle sender defer: 5
2024-01-26 17:15:39,003 INFO    SenderThread:3042423 [sender.py:transition_state():617] send defer: 6
2024-01-26 17:15:39,003 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:39,004 INFO    HandlerThread:3042423 [handler.py:handle_request_defer():172] handle defer: 6
2024-01-26 17:15:39,004 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:39,004 INFO    SenderThread:3042423 [sender.py:send_request_defer():613] handle sender defer: 6
2024-01-26 17:15:39,004 INFO    SenderThread:3042423 [sender.py:transition_state():617] send defer: 7
2024-01-26 17:15:39,004 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:39,004 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:39,004 INFO    HandlerThread:3042423 [handler.py:handle_request_defer():172] handle defer: 7
2024-01-26 17:15:39,004 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:39,004 INFO    SenderThread:3042423 [sender.py:send_request_defer():613] handle sender defer: 7
2024-01-26 17:15:39,083 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:15:39,469 INFO    Thread-12 :3042423 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/files/wandb-summary.json
2024-01-26 17:15:39,472 INFO    SenderThread:3042423 [sender.py:transition_state():617] send defer: 8
2024-01-26 17:15:39,472 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:15:39,472 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:39,472 INFO    HandlerThread:3042423 [handler.py:handle_request_defer():172] handle defer: 8
2024-01-26 17:15:39,472 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:39,472 INFO    SenderThread:3042423 [sender.py:send_request_defer():613] handle sender defer: 8
2024-01-26 17:15:39,473 INFO    SenderThread:3042423 [job_builder.py:build():296] Attempting to build job artifact
2024-01-26 17:15:39,473 INFO    SenderThread:3042423 [job_builder.py:_get_source_type():426] is repo sourced job
2024-01-26 17:15:39,623 INFO    SenderThread:3042423 [job_builder.py:build():402] adding wandb-job metadata file
2024-01-26 17:15:39,626 INFO    SenderThread:3042423 [sender.py:transition_state():617] send defer: 9
2024-01-26 17:15:39,627 DEBUG   SenderThread:3042423 [sender.py:send():382] send: artifact
2024-01-26 17:15:39,627 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:39,630 INFO    HandlerThread:3042423 [handler.py:handle_request_defer():172] handle defer: 9
2024-01-26 17:15:40,083 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:15:40,469 INFO    Thread-12 :3042423 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/files/output.log
2024-01-26 17:15:41,441 ERROR   wandb-upload_1:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789711/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ATKJHFHv2D9EL5HD3F22FtJsJLe1F1lVR1aYa3ahDJ4OCgxuMM40srrLP4HLhSkRHblLCmagJb3iRQ%2B5wmcVlWGODXG%2FTI0lZ9A3Elwyks5OD4yyueMdNHF9lcbU0w0pjs4%2Fz89sOEouKUr7QCo6Llxj95NgcBXae8McbfnnRUdj9kgLtEdbWmTAPl23M0h60DXoYfcjohNQ7pIVolUiuL2dIZ%2Fx6yhFoa9TdkINnwIyMF6a%2BaV8kEoa5tAbaQCFcuQMxpRiiH%2BG5RRUYLoECKnn7PjUpl0Hjbb0UzlPQ3ezg%2FMdpwypQZTObK0ZLWqg%2BHQXNoH3Aw5a8LtAJ2ZnaA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789711/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ATKJHFHv2D9EL5HD3F22FtJsJLe1F1lVR1aYa3ahDJ4OCgxuMM40srrLP4HLhSkRHblLCmagJb3iRQ%2B5wmcVlWGODXG%2FTI0lZ9A3Elwyks5OD4yyueMdNHF9lcbU0w0pjs4%2Fz89sOEouKUr7QCo6Llxj95NgcBXae8McbfnnRUdj9kgLtEdbWmTAPl23M0h60DXoYfcjohNQ7pIVolUiuL2dIZ%2Fx6yhFoa9TdkINnwIyMF6a%2BaV8kEoa5tAbaQCFcuQMxpRiiH%2BG5RRUYLoECKnn7PjUpl0Hjbb0UzlPQ3ezg%2FMdpwypQZTObK0ZLWqg%2BHQXNoH3Aw5a8LtAJ2ZnaA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c701a4c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:41,441 ERROR   wandb-upload_1:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:41,441 ERROR   wandb-upload_1:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:41,979 ERROR   wandb-upload_2:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789711/6873c23a2381d1524249eb1a948a45a5?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nYUXU7iqydgEQ2IFcy1ShhaxNKYoNpYVGvHRNmDqJrJb2w2kh3Kg0mED%2FyUUsthb1S%2BzkhW0DnlP29NRuvzPGXGxf7r9hmwzPOa6WDPub0TeLHEcCi%2BshwI98OuV8w3PhoMOygq3FAj3oSmjn%2FcLG6P1BFbaZhsloxusIeQaW2QL2dkJHLbo0rSGLB4876Ng2tMxfxPpi3KfCYckuV738DKbCK9kA8yFwvmUkvkFM3D2x2J0azkZpZHWckUCTsyVqIfYIKnDRt%2BjCu0HyGCKyiEElIQDDCC6zPW1jbaPykS3LY%2FiCOvfipfmR81V6Hr%2FHikTBGqL37OZRxOMa4RsRw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789711/6873c23a2381d1524249eb1a948a45a5?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nYUXU7iqydgEQ2IFcy1ShhaxNKYoNpYVGvHRNmDqJrJb2w2kh3Kg0mED%2FyUUsthb1S%2BzkhW0DnlP29NRuvzPGXGxf7r9hmwzPOa6WDPub0TeLHEcCi%2BshwI98OuV8w3PhoMOygq3FAj3oSmjn%2FcLG6P1BFbaZhsloxusIeQaW2QL2dkJHLbo0rSGLB4876Ng2tMxfxPpi3KfCYckuV738DKbCK9kA8yFwvmUkvkFM3D2x2J0azkZpZHWckUCTsyVqIfYIKnDRt%2BjCu0HyGCKyiEElIQDDCC6zPW1jbaPykS3LY%2FiCOvfipfmR81V6Hr%2FHikTBGqL37OZRxOMa4RsRw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c701a41f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:41,979 ERROR   wandb-upload_2:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:41,979 ERROR   wandb-upload_2:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:42,691 ERROR   wandb-upload_1:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789711/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ATKJHFHv2D9EL5HD3F22FtJsJLe1F1lVR1aYa3ahDJ4OCgxuMM40srrLP4HLhSkRHblLCmagJb3iRQ%2B5wmcVlWGODXG%2FTI0lZ9A3Elwyks5OD4yyueMdNHF9lcbU0w0pjs4%2Fz89sOEouKUr7QCo6Llxj95NgcBXae8McbfnnRUdj9kgLtEdbWmTAPl23M0h60DXoYfcjohNQ7pIVolUiuL2dIZ%2Fx6yhFoa9TdkINnwIyMF6a%2BaV8kEoa5tAbaQCFcuQMxpRiiH%2BG5RRUYLoECKnn7PjUpl0Hjbb0UzlPQ3ezg%2FMdpwypQZTObK0ZLWqg%2BHQXNoH3Aw5a8LtAJ2ZnaA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789711/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ATKJHFHv2D9EL5HD3F22FtJsJLe1F1lVR1aYa3ahDJ4OCgxuMM40srrLP4HLhSkRHblLCmagJb3iRQ%2B5wmcVlWGODXG%2FTI0lZ9A3Elwyks5OD4yyueMdNHF9lcbU0w0pjs4%2Fz89sOEouKUr7QCo6Llxj95NgcBXae8McbfnnRUdj9kgLtEdbWmTAPl23M0h60DXoYfcjohNQ7pIVolUiuL2dIZ%2Fx6yhFoa9TdkINnwIyMF6a%2BaV8kEoa5tAbaQCFcuQMxpRiiH%2BG5RRUYLoECKnn7PjUpl0Hjbb0UzlPQ3ezg%2FMdpwypQZTObK0ZLWqg%2BHQXNoH3Aw5a8LtAJ2ZnaA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c7020c250>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:42,692 ERROR   wandb-upload_1:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:42,692 ERROR   wandb-upload_1:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:43,208 ERROR   wandb-upload_2:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789711/6873c23a2381d1524249eb1a948a45a5?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nYUXU7iqydgEQ2IFcy1ShhaxNKYoNpYVGvHRNmDqJrJb2w2kh3Kg0mED%2FyUUsthb1S%2BzkhW0DnlP29NRuvzPGXGxf7r9hmwzPOa6WDPub0TeLHEcCi%2BshwI98OuV8w3PhoMOygq3FAj3oSmjn%2FcLG6P1BFbaZhsloxusIeQaW2QL2dkJHLbo0rSGLB4876Ng2tMxfxPpi3KfCYckuV738DKbCK9kA8yFwvmUkvkFM3D2x2J0azkZpZHWckUCTsyVqIfYIKnDRt%2BjCu0HyGCKyiEElIQDDCC6zPW1jbaPykS3LY%2FiCOvfipfmR81V6Hr%2FHikTBGqL37OZRxOMa4RsRw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789711/6873c23a2381d1524249eb1a948a45a5?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nYUXU7iqydgEQ2IFcy1ShhaxNKYoNpYVGvHRNmDqJrJb2w2kh3Kg0mED%2FyUUsthb1S%2BzkhW0DnlP29NRuvzPGXGxf7r9hmwzPOa6WDPub0TeLHEcCi%2BshwI98OuV8w3PhoMOygq3FAj3oSmjn%2FcLG6P1BFbaZhsloxusIeQaW2QL2dkJHLbo0rSGLB4876Ng2tMxfxPpi3KfCYckuV738DKbCK9kA8yFwvmUkvkFM3D2x2J0azkZpZHWckUCTsyVqIfYIKnDRt%2BjCu0HyGCKyiEElIQDDCC6zPW1jbaPykS3LY%2FiCOvfipfmR81V6Hr%2FHikTBGqL37OZRxOMa4RsRw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c7020c4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:43,208 ERROR   wandb-upload_2:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:43,208 ERROR   wandb-upload_2:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:43,209 INFO    wandb-upload_2:3042423 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8c7020c4f0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789711/6873c23a2381d1524249eb1a948a45a5?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nYUXU7iqydgEQ2IFcy1ShhaxNKYoNpYVGvHRNmDqJrJb2w2kh3Kg0mED%2FyUUsthb1S%2BzkhW0DnlP29NRuvzPGXGxf7r9hmwzPOa6WDPub0TeLHEcCi%2BshwI98OuV8w3PhoMOygq3FAj3oSmjn%2FcLG6P1BFbaZhsloxusIeQaW2QL2dkJHLbo0rSGLB4876Ng2tMxfxPpi3KfCYckuV738DKbCK9kA8yFwvmUkvkFM3D2x2J0azkZpZHWckUCTsyVqIfYIKnDRt%2BjCu0HyGCKyiEElIQDDCC6zPW1jbaPykS3LY%2FiCOvfipfmR81V6Hr%2FHikTBGqL37OZRxOMa4RsRw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c7020c4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789711/6873c23a2381d1524249eb1a948a45a5?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nYUXU7iqydgEQ2IFcy1ShhaxNKYoNpYVGvHRNmDqJrJb2w2kh3Kg0mED%2FyUUsthb1S%2BzkhW0DnlP29NRuvzPGXGxf7r9hmwzPOa6WDPub0TeLHEcCi%2BshwI98OuV8w3PhoMOygq3FAj3oSmjn%2FcLG6P1BFbaZhsloxusIeQaW2QL2dkJHLbo0rSGLB4876Ng2tMxfxPpi3KfCYckuV738DKbCK9kA8yFwvmUkvkFM3D2x2J0azkZpZHWckUCTsyVqIfYIKnDRt%2BjCu0HyGCKyiEElIQDDCC6zPW1jbaPykS3LY%2FiCOvfipfmR81V6Hr%2FHikTBGqL37OZRxOMa4RsRw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c7020c4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2789, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-01-26 17:15:45,024 ERROR   wandb-upload_1:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789711/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ATKJHFHv2D9EL5HD3F22FtJsJLe1F1lVR1aYa3ahDJ4OCgxuMM40srrLP4HLhSkRHblLCmagJb3iRQ%2B5wmcVlWGODXG%2FTI0lZ9A3Elwyks5OD4yyueMdNHF9lcbU0w0pjs4%2Fz89sOEouKUr7QCo6Llxj95NgcBXae8McbfnnRUdj9kgLtEdbWmTAPl23M0h60DXoYfcjohNQ7pIVolUiuL2dIZ%2Fx6yhFoa9TdkINnwIyMF6a%2BaV8kEoa5tAbaQCFcuQMxpRiiH%2BG5RRUYLoECKnn7PjUpl0Hjbb0UzlPQ3ezg%2FMdpwypQZTObK0ZLWqg%2BHQXNoH3Aw5a8LtAJ2ZnaA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789711/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ATKJHFHv2D9EL5HD3F22FtJsJLe1F1lVR1aYa3ahDJ4OCgxuMM40srrLP4HLhSkRHblLCmagJb3iRQ%2B5wmcVlWGODXG%2FTI0lZ9A3Elwyks5OD4yyueMdNHF9lcbU0w0pjs4%2Fz89sOEouKUr7QCo6Llxj95NgcBXae8McbfnnRUdj9kgLtEdbWmTAPl23M0h60DXoYfcjohNQ7pIVolUiuL2dIZ%2Fx6yhFoa9TdkINnwIyMF6a%2BaV8kEoa5tAbaQCFcuQMxpRiiH%2BG5RRUYLoECKnn7PjUpl0Hjbb0UzlPQ3ezg%2FMdpwypQZTObK0ZLWqg%2BHQXNoH3Aw5a8LtAJ2ZnaA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c70384c40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:45,024 ERROR   wandb-upload_1:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:45,024 ERROR   wandb-upload_1:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:45,087 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:45,313 ERROR   wandb-upload_2:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789711/6873c23a2381d1524249eb1a948a45a5?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nYUXU7iqydgEQ2IFcy1ShhaxNKYoNpYVGvHRNmDqJrJb2w2kh3Kg0mED%2FyUUsthb1S%2BzkhW0DnlP29NRuvzPGXGxf7r9hmwzPOa6WDPub0TeLHEcCi%2BshwI98OuV8w3PhoMOygq3FAj3oSmjn%2FcLG6P1BFbaZhsloxusIeQaW2QL2dkJHLbo0rSGLB4876Ng2tMxfxPpi3KfCYckuV738DKbCK9kA8yFwvmUkvkFM3D2x2J0azkZpZHWckUCTsyVqIfYIKnDRt%2BjCu0HyGCKyiEElIQDDCC6zPW1jbaPykS3LY%2FiCOvfipfmR81V6Hr%2FHikTBGqL37OZRxOMa4RsRw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789711/6873c23a2381d1524249eb1a948a45a5?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nYUXU7iqydgEQ2IFcy1ShhaxNKYoNpYVGvHRNmDqJrJb2w2kh3Kg0mED%2FyUUsthb1S%2BzkhW0DnlP29NRuvzPGXGxf7r9hmwzPOa6WDPub0TeLHEcCi%2BshwI98OuV8w3PhoMOygq3FAj3oSmjn%2FcLG6P1BFbaZhsloxusIeQaW2QL2dkJHLbo0rSGLB4876Ng2tMxfxPpi3KfCYckuV738DKbCK9kA8yFwvmUkvkFM3D2x2J0azkZpZHWckUCTsyVqIfYIKnDRt%2BjCu0HyGCKyiEElIQDDCC6zPW1jbaPykS3LY%2FiCOvfipfmR81V6Hr%2FHikTBGqL37OZRxOMa4RsRw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c7020c850>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:45,313 ERROR   wandb-upload_2:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:45,313 ERROR   wandb-upload_2:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:49,062 ERROR   wandb-upload_1:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789711/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ATKJHFHv2D9EL5HD3F22FtJsJLe1F1lVR1aYa3ahDJ4OCgxuMM40srrLP4HLhSkRHblLCmagJb3iRQ%2B5wmcVlWGODXG%2FTI0lZ9A3Elwyks5OD4yyueMdNHF9lcbU0w0pjs4%2Fz89sOEouKUr7QCo6Llxj95NgcBXae8McbfnnRUdj9kgLtEdbWmTAPl23M0h60DXoYfcjohNQ7pIVolUiuL2dIZ%2Fx6yhFoa9TdkINnwIyMF6a%2BaV8kEoa5tAbaQCFcuQMxpRiiH%2BG5RRUYLoECKnn7PjUpl0Hjbb0UzlPQ3ezg%2FMdpwypQZTObK0ZLWqg%2BHQXNoH3Aw5a8LtAJ2ZnaA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789711/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ATKJHFHv2D9EL5HD3F22FtJsJLe1F1lVR1aYa3ahDJ4OCgxuMM40srrLP4HLhSkRHblLCmagJb3iRQ%2B5wmcVlWGODXG%2FTI0lZ9A3Elwyks5OD4yyueMdNHF9lcbU0w0pjs4%2Fz89sOEouKUr7QCo6Llxj95NgcBXae8McbfnnRUdj9kgLtEdbWmTAPl23M0h60DXoYfcjohNQ7pIVolUiuL2dIZ%2Fx6yhFoa9TdkINnwIyMF6a%2BaV8kEoa5tAbaQCFcuQMxpRiiH%2BG5RRUYLoECKnn7PjUpl0Hjbb0UzlPQ3ezg%2FMdpwypQZTObK0ZLWqg%2BHQXNoH3Aw5a8LtAJ2ZnaA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c7020c670>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:49,062 ERROR   wandb-upload_1:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:49,062 ERROR   wandb-upload_1:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:50,059 ERROR   wandb-upload_2:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789711/6873c23a2381d1524249eb1a948a45a5?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nYUXU7iqydgEQ2IFcy1ShhaxNKYoNpYVGvHRNmDqJrJb2w2kh3Kg0mED%2FyUUsthb1S%2BzkhW0DnlP29NRuvzPGXGxf7r9hmwzPOa6WDPub0TeLHEcCi%2BshwI98OuV8w3PhoMOygq3FAj3oSmjn%2FcLG6P1BFbaZhsloxusIeQaW2QL2dkJHLbo0rSGLB4876Ng2tMxfxPpi3KfCYckuV738DKbCK9kA8yFwvmUkvkFM3D2x2J0azkZpZHWckUCTsyVqIfYIKnDRt%2BjCu0HyGCKyiEElIQDDCC6zPW1jbaPykS3LY%2FiCOvfipfmR81V6Hr%2FHikTBGqL37OZRxOMa4RsRw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789711/6873c23a2381d1524249eb1a948a45a5?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nYUXU7iqydgEQ2IFcy1ShhaxNKYoNpYVGvHRNmDqJrJb2w2kh3Kg0mED%2FyUUsthb1S%2BzkhW0DnlP29NRuvzPGXGxf7r9hmwzPOa6WDPub0TeLHEcCi%2BshwI98OuV8w3PhoMOygq3FAj3oSmjn%2FcLG6P1BFbaZhsloxusIeQaW2QL2dkJHLbo0rSGLB4876Ng2tMxfxPpi3KfCYckuV738DKbCK9kA8yFwvmUkvkFM3D2x2J0azkZpZHWckUCTsyVqIfYIKnDRt%2BjCu0HyGCKyiEElIQDDCC6zPW1jbaPykS3LY%2FiCOvfipfmR81V6Hr%2FHikTBGqL37OZRxOMa4RsRw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c701a4f70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:50,059 ERROR   wandb-upload_2:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:50,059 ERROR   wandb-upload_2:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:50,089 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:55,091 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:57,987 ERROR   wandb-upload_1:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789711/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ATKJHFHv2D9EL5HD3F22FtJsJLe1F1lVR1aYa3ahDJ4OCgxuMM40srrLP4HLhSkRHblLCmagJb3iRQ%2B5wmcVlWGODXG%2FTI0lZ9A3Elwyks5OD4yyueMdNHF9lcbU0w0pjs4%2Fz89sOEouKUr7QCo6Llxj95NgcBXae8McbfnnRUdj9kgLtEdbWmTAPl23M0h60DXoYfcjohNQ7pIVolUiuL2dIZ%2Fx6yhFoa9TdkINnwIyMF6a%2BaV8kEoa5tAbaQCFcuQMxpRiiH%2BG5RRUYLoECKnn7PjUpl0Hjbb0UzlPQ3ezg%2FMdpwypQZTObK0ZLWqg%2BHQXNoH3Aw5a8LtAJ2ZnaA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789711/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ATKJHFHv2D9EL5HD3F22FtJsJLe1F1lVR1aYa3ahDJ4OCgxuMM40srrLP4HLhSkRHblLCmagJb3iRQ%2B5wmcVlWGODXG%2FTI0lZ9A3Elwyks5OD4yyueMdNHF9lcbU0w0pjs4%2Fz89sOEouKUr7QCo6Llxj95NgcBXae8McbfnnRUdj9kgLtEdbWmTAPl23M0h60DXoYfcjohNQ7pIVolUiuL2dIZ%2Fx6yhFoa9TdkINnwIyMF6a%2BaV8kEoa5tAbaQCFcuQMxpRiiH%2BG5RRUYLoECKnn7PjUpl0Hjbb0UzlPQ3ezg%2FMdpwypQZTObK0ZLWqg%2BHQXNoH3Aw5a8LtAJ2ZnaA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c70384310>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:57,987 ERROR   wandb-upload_1:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:57,987 ERROR   wandb-upload_1:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:59,663 ERROR   wandb-upload_2:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789711/6873c23a2381d1524249eb1a948a45a5?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nYUXU7iqydgEQ2IFcy1ShhaxNKYoNpYVGvHRNmDqJrJb2w2kh3Kg0mED%2FyUUsthb1S%2BzkhW0DnlP29NRuvzPGXGxf7r9hmwzPOa6WDPub0TeLHEcCi%2BshwI98OuV8w3PhoMOygq3FAj3oSmjn%2FcLG6P1BFbaZhsloxusIeQaW2QL2dkJHLbo0rSGLB4876Ng2tMxfxPpi3KfCYckuV738DKbCK9kA8yFwvmUkvkFM3D2x2J0azkZpZHWckUCTsyVqIfYIKnDRt%2BjCu0HyGCKyiEElIQDDCC6zPW1jbaPykS3LY%2FiCOvfipfmR81V6Hr%2FHikTBGqL37OZRxOMa4RsRw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789711/6873c23a2381d1524249eb1a948a45a5?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nYUXU7iqydgEQ2IFcy1ShhaxNKYoNpYVGvHRNmDqJrJb2w2kh3Kg0mED%2FyUUsthb1S%2BzkhW0DnlP29NRuvzPGXGxf7r9hmwzPOa6WDPub0TeLHEcCi%2BshwI98OuV8w3PhoMOygq3FAj3oSmjn%2FcLG6P1BFbaZhsloxusIeQaW2QL2dkJHLbo0rSGLB4876Ng2tMxfxPpi3KfCYckuV738DKbCK9kA8yFwvmUkvkFM3D2x2J0azkZpZHWckUCTsyVqIfYIKnDRt%2BjCu0HyGCKyiEElIQDDCC6zPW1jbaPykS3LY%2FiCOvfipfmR81V6Hr%2FHikTBGqL37OZRxOMa4RsRw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c70384370>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:59,663 ERROR   wandb-upload_2:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:59,663 ERROR   wandb-upload_2:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:00,093 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:05,098 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:10,100 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:15,103 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:16,210 ERROR   wandb-upload_2:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789711/6873c23a2381d1524249eb1a948a45a5?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nYUXU7iqydgEQ2IFcy1ShhaxNKYoNpYVGvHRNmDqJrJb2w2kh3Kg0mED%2FyUUsthb1S%2BzkhW0DnlP29NRuvzPGXGxf7r9hmwzPOa6WDPub0TeLHEcCi%2BshwI98OuV8w3PhoMOygq3FAj3oSmjn%2FcLG6P1BFbaZhsloxusIeQaW2QL2dkJHLbo0rSGLB4876Ng2tMxfxPpi3KfCYckuV738DKbCK9kA8yFwvmUkvkFM3D2x2J0azkZpZHWckUCTsyVqIfYIKnDRt%2BjCu0HyGCKyiEElIQDDCC6zPW1jbaPykS3LY%2FiCOvfipfmR81V6Hr%2FHikTBGqL37OZRxOMa4RsRw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789711/6873c23a2381d1524249eb1a948a45a5?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nYUXU7iqydgEQ2IFcy1ShhaxNKYoNpYVGvHRNmDqJrJb2w2kh3Kg0mED%2FyUUsthb1S%2BzkhW0DnlP29NRuvzPGXGxf7r9hmwzPOa6WDPub0TeLHEcCi%2BshwI98OuV8w3PhoMOygq3FAj3oSmjn%2FcLG6P1BFbaZhsloxusIeQaW2QL2dkJHLbo0rSGLB4876Ng2tMxfxPpi3KfCYckuV738DKbCK9kA8yFwvmUkvkFM3D2x2J0azkZpZHWckUCTsyVqIfYIKnDRt%2BjCu0HyGCKyiEElIQDDCC6zPW1jbaPykS3LY%2FiCOvfipfmR81V6Hr%2FHikTBGqL37OZRxOMa4RsRw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c701cca30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:16:16,211 ERROR   wandb-upload_2:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:16:16,211 ERROR   wandb-upload_2:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:17,256 ERROR   wandb-upload_1:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789711/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ATKJHFHv2D9EL5HD3F22FtJsJLe1F1lVR1aYa3ahDJ4OCgxuMM40srrLP4HLhSkRHblLCmagJb3iRQ%2B5wmcVlWGODXG%2FTI0lZ9A3Elwyks5OD4yyueMdNHF9lcbU0w0pjs4%2Fz89sOEouKUr7QCo6Llxj95NgcBXae8McbfnnRUdj9kgLtEdbWmTAPl23M0h60DXoYfcjohNQ7pIVolUiuL2dIZ%2Fx6yhFoa9TdkINnwIyMF6a%2BaV8kEoa5tAbaQCFcuQMxpRiiH%2BG5RRUYLoECKnn7PjUpl0Hjbb0UzlPQ3ezg%2FMdpwypQZTObK0ZLWqg%2BHQXNoH3Aw5a8LtAJ2ZnaA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789711/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ATKJHFHv2D9EL5HD3F22FtJsJLe1F1lVR1aYa3ahDJ4OCgxuMM40srrLP4HLhSkRHblLCmagJb3iRQ%2B5wmcVlWGODXG%2FTI0lZ9A3Elwyks5OD4yyueMdNHF9lcbU0w0pjs4%2Fz89sOEouKUr7QCo6Llxj95NgcBXae8McbfnnRUdj9kgLtEdbWmTAPl23M0h60DXoYfcjohNQ7pIVolUiuL2dIZ%2Fx6yhFoa9TdkINnwIyMF6a%2BaV8kEoa5tAbaQCFcuQMxpRiiH%2BG5RRUYLoECKnn7PjUpl0Hjbb0UzlPQ3ezg%2FMdpwypQZTObK0ZLWqg%2BHQXNoH3Aw5a8LtAJ2ZnaA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c701cd1f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:16:17,256 ERROR   wandb-upload_1:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:16:17,256 ERROR   wandb-upload_1:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:20,105 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:25,107 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:30,109 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:35,111 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:40,113 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:45,115 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:50,117 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:50,837 ERROR   wandb-upload_2:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789711/6873c23a2381d1524249eb1a948a45a5?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nYUXU7iqydgEQ2IFcy1ShhaxNKYoNpYVGvHRNmDqJrJb2w2kh3Kg0mED%2FyUUsthb1S%2BzkhW0DnlP29NRuvzPGXGxf7r9hmwzPOa6WDPub0TeLHEcCi%2BshwI98OuV8w3PhoMOygq3FAj3oSmjn%2FcLG6P1BFbaZhsloxusIeQaW2QL2dkJHLbo0rSGLB4876Ng2tMxfxPpi3KfCYckuV738DKbCK9kA8yFwvmUkvkFM3D2x2J0azkZpZHWckUCTsyVqIfYIKnDRt%2BjCu0HyGCKyiEElIQDDCC6zPW1jbaPykS3LY%2FiCOvfipfmR81V6Hr%2FHikTBGqL37OZRxOMa4RsRw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789711/6873c23a2381d1524249eb1a948a45a5?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nYUXU7iqydgEQ2IFcy1ShhaxNKYoNpYVGvHRNmDqJrJb2w2kh3Kg0mED%2FyUUsthb1S%2BzkhW0DnlP29NRuvzPGXGxf7r9hmwzPOa6WDPub0TeLHEcCi%2BshwI98OuV8w3PhoMOygq3FAj3oSmjn%2FcLG6P1BFbaZhsloxusIeQaW2QL2dkJHLbo0rSGLB4876Ng2tMxfxPpi3KfCYckuV738DKbCK9kA8yFwvmUkvkFM3D2x2J0azkZpZHWckUCTsyVqIfYIKnDRt%2BjCu0HyGCKyiEElIQDDCC6zPW1jbaPykS3LY%2FiCOvfipfmR81V6Hr%2FHikTBGqL37OZRxOMa4RsRw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c701ccfd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:16:50,837 ERROR   wandb-upload_2:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:16:50,837 ERROR   wandb-upload_2:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:54,903 ERROR   wandb-upload_1:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789711/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ATKJHFHv2D9EL5HD3F22FtJsJLe1F1lVR1aYa3ahDJ4OCgxuMM40srrLP4HLhSkRHblLCmagJb3iRQ%2B5wmcVlWGODXG%2FTI0lZ9A3Elwyks5OD4yyueMdNHF9lcbU0w0pjs4%2Fz89sOEouKUr7QCo6Llxj95NgcBXae8McbfnnRUdj9kgLtEdbWmTAPl23M0h60DXoYfcjohNQ7pIVolUiuL2dIZ%2Fx6yhFoa9TdkINnwIyMF6a%2BaV8kEoa5tAbaQCFcuQMxpRiiH%2BG5RRUYLoECKnn7PjUpl0Hjbb0UzlPQ3ezg%2FMdpwypQZTObK0ZLWqg%2BHQXNoH3Aw5a8LtAJ2ZnaA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789711/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ATKJHFHv2D9EL5HD3F22FtJsJLe1F1lVR1aYa3ahDJ4OCgxuMM40srrLP4HLhSkRHblLCmagJb3iRQ%2B5wmcVlWGODXG%2FTI0lZ9A3Elwyks5OD4yyueMdNHF9lcbU0w0pjs4%2Fz89sOEouKUr7QCo6Llxj95NgcBXae8McbfnnRUdj9kgLtEdbWmTAPl23M0h60DXoYfcjohNQ7pIVolUiuL2dIZ%2Fx6yhFoa9TdkINnwIyMF6a%2BaV8kEoa5tAbaQCFcuQMxpRiiH%2BG5RRUYLoECKnn7PjUpl0Hjbb0UzlPQ3ezg%2FMdpwypQZTObK0ZLWqg%2BHQXNoH3Aw5a8LtAJ2ZnaA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c701a4700>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:16:54,903 ERROR   wandb-upload_1:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:16:54,903 ERROR   wandb-upload_1:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:55,119 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:00,121 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:05,123 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:10,126 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:15,128 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:20,130 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:25,132 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:30,134 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:35,136 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:40,138 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:45,141 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:50,143 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:55,145 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:00,146 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:00,717 ERROR   wandb-upload_2:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789711/6873c23a2381d1524249eb1a948a45a5?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nYUXU7iqydgEQ2IFcy1ShhaxNKYoNpYVGvHRNmDqJrJb2w2kh3Kg0mED%2FyUUsthb1S%2BzkhW0DnlP29NRuvzPGXGxf7r9hmwzPOa6WDPub0TeLHEcCi%2BshwI98OuV8w3PhoMOygq3FAj3oSmjn%2FcLG6P1BFbaZhsloxusIeQaW2QL2dkJHLbo0rSGLB4876Ng2tMxfxPpi3KfCYckuV738DKbCK9kA8yFwvmUkvkFM3D2x2J0azkZpZHWckUCTsyVqIfYIKnDRt%2BjCu0HyGCKyiEElIQDDCC6zPW1jbaPykS3LY%2FiCOvfipfmR81V6Hr%2FHikTBGqL37OZRxOMa4RsRw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789711/6873c23a2381d1524249eb1a948a45a5?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nYUXU7iqydgEQ2IFcy1ShhaxNKYoNpYVGvHRNmDqJrJb2w2kh3Kg0mED%2FyUUsthb1S%2BzkhW0DnlP29NRuvzPGXGxf7r9hmwzPOa6WDPub0TeLHEcCi%2BshwI98OuV8w3PhoMOygq3FAj3oSmjn%2FcLG6P1BFbaZhsloxusIeQaW2QL2dkJHLbo0rSGLB4876Ng2tMxfxPpi3KfCYckuV738DKbCK9kA8yFwvmUkvkFM3D2x2J0azkZpZHWckUCTsyVqIfYIKnDRt%2BjCu0HyGCKyiEElIQDDCC6zPW1jbaPykS3LY%2FiCOvfipfmR81V6Hr%2FHikTBGqL37OZRxOMa4RsRw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c701be100>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:18:00,717 ERROR   wandb-upload_2:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:18:00,717 ERROR   wandb-upload_2:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:18:05,148 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:10,150 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:12,137 ERROR   wandb-upload_1:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789711/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ATKJHFHv2D9EL5HD3F22FtJsJLe1F1lVR1aYa3ahDJ4OCgxuMM40srrLP4HLhSkRHblLCmagJb3iRQ%2B5wmcVlWGODXG%2FTI0lZ9A3Elwyks5OD4yyueMdNHF9lcbU0w0pjs4%2Fz89sOEouKUr7QCo6Llxj95NgcBXae8McbfnnRUdj9kgLtEdbWmTAPl23M0h60DXoYfcjohNQ7pIVolUiuL2dIZ%2Fx6yhFoa9TdkINnwIyMF6a%2BaV8kEoa5tAbaQCFcuQMxpRiiH%2BG5RRUYLoECKnn7PjUpl0Hjbb0UzlPQ3ezg%2FMdpwypQZTObK0ZLWqg%2BHQXNoH3Aw5a8LtAJ2ZnaA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789711/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346941&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ATKJHFHv2D9EL5HD3F22FtJsJLe1F1lVR1aYa3ahDJ4OCgxuMM40srrLP4HLhSkRHblLCmagJb3iRQ%2B5wmcVlWGODXG%2FTI0lZ9A3Elwyks5OD4yyueMdNHF9lcbU0w0pjs4%2Fz89sOEouKUr7QCo6Llxj95NgcBXae8McbfnnRUdj9kgLtEdbWmTAPl23M0h60DXoYfcjohNQ7pIVolUiuL2dIZ%2Fx6yhFoa9TdkINnwIyMF6a%2BaV8kEoa5tAbaQCFcuQMxpRiiH%2BG5RRUYLoECKnn7PjUpl0Hjbb0UzlPQ3ezg%2FMdpwypQZTObK0ZLWqg%2BHQXNoH3Aw5a8LtAJ2ZnaA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c701c6640>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:18:12,138 ERROR   wandb-upload_1:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:18:12,138 ERROR   wandb-upload_1:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:18:15,153 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:20,155 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:25,158 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:29,277 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/36lzu9m5/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S5heqgzp0xoicCobJR3AEkRGEKD5qivEoeW9yeHHMvkp0RfgjqZtvgV8WxZzUBJJSwVNyTxJp%2BMabFalIjIllIm2Dciwc86dcBYQVhFpLHl5FcFad38ORK2wjkAx8pomWH9FkYu1swLdy3CRMnpKf%2B9ccuTTTf9M9ZZ7BVc3uTtV3ww5sPa3qkNf2M1k6uwVgtLfhxCEVN5TSR7QG03BRJDuLy3FYfOUClnt%2B%2FWImad9h7KZMyPsXfgAVZHDZK2HlVQ6EhKGVABkKx8BLEAgacPgS3u0Wt49IoDkOd7K%2BLuk7cGyqTjrcB9fQ%2Fb%2Bs6odEbzo9CnGiWOw1ynQ2MYwFg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/36lzu9m5/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S5heqgzp0xoicCobJR3AEkRGEKD5qivEoeW9yeHHMvkp0RfgjqZtvgV8WxZzUBJJSwVNyTxJp%2BMabFalIjIllIm2Dciwc86dcBYQVhFpLHl5FcFad38ORK2wjkAx8pomWH9FkYu1swLdy3CRMnpKf%2B9ccuTTTf9M9ZZ7BVc3uTtV3ww5sPa3qkNf2M1k6uwVgtLfhxCEVN5TSR7QG03BRJDuLy3FYfOUClnt%2B%2FWImad9h7KZMyPsXfgAVZHDZK2HlVQ6EhKGVABkKx8BLEAgacPgS3u0Wt49IoDkOd7K%2BLuk7cGyqTjrcB9fQ%2Fb%2Bs6odEbzo9CnGiWOw1ynQ2MYwFg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c7020cfd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:18:29,277 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15648'}
2024-01-26 17:18:29,277 ERROR   wandb-upload_0:3042423 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:18:30,160 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:35,162 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:40,164 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:45,166 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:50,168 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:55,171 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:00,173 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:05,175 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:10,177 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:15,179 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:20,181 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:25,183 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:30,186 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:35,188 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:40,190 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:45,192 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:50,194 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:55,195 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:00,197 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:05,199 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:10,201 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:15,203 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:20,205 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:23,223 INFO    wandb-upload_2:3042423 [upload_job.py:push():89] Uploaded file /home/yanxindong/.local/share/wandb/artifacts/staging/tmpdz21v4fg
2024-01-26 17:20:25,208 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:30,210 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:35,212 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:39,848 INFO    wandb-upload_1:3042423 [upload_job.py:push():89] Uploaded file /home/yanxindong/.local/share/wandb/artifacts/staging/tmpkaok99ct
2024-01-26 17:20:40,214 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:45,217 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:46,150 INFO    SenderThread:3042423 [sender.py:send_artifact():1494] sent artifact job-https___github.com_kkkjj-d_mkor.git_bert_run_pretraining.py - {'id': 'QXJ0aWZhY3Q6NzAzNzg5NzEx', 'state': 'PENDING', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjEzMzk4MTIwMA==', 'latestArtifact': None}}
2024-01-26 17:20:46,150 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: defer
2024-01-26 17:20:46,150 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:20:46,150 INFO    SenderThread:3042423 [sender.py:send_request_defer():613] handle sender defer: 9
2024-01-26 17:20:46,151 INFO    SenderThread:3042423 [dir_watcher.py:finish():358] shutting down directory watcher
2024-01-26 17:20:46,513 INFO    SenderThread:3042423 [dir_watcher.py:finish():388] scan: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/files
2024-01-26 17:20:46,513 INFO    SenderThread:3042423 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/files/wandb-summary.json wandb-summary.json
2024-01-26 17:20:46,513 INFO    SenderThread:3042423 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/files/conda-environment.yaml conda-environment.yaml
2024-01-26 17:20:46,514 INFO    SenderThread:3042423 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/files/wandb-metadata.json wandb-metadata.json
2024-01-26 17:20:46,519 INFO    SenderThread:3042423 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/files/output.log output.log
2024-01-26 17:20:46,519 INFO    SenderThread:3042423 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/files/requirements.txt requirements.txt
2024-01-26 17:20:46,519 INFO    SenderThread:3042423 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/files/config.yaml config.yaml
2024-01-26 17:20:46,522 INFO    SenderThread:3042423 [sender.py:transition_state():617] send defer: 10
2024-01-26 17:20:46,524 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:46,527 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:20:46,527 INFO    HandlerThread:3042423 [handler.py:handle_request_defer():172] handle defer: 10
2024-01-26 17:20:46,528 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: defer
2024-01-26 17:20:46,528 INFO    SenderThread:3042423 [sender.py:send_request_defer():613] handle sender defer: 10
2024-01-26 17:20:46,528 INFO    SenderThread:3042423 [file_pusher.py:finish():175] shutting down file pusher
2024-01-26 17:20:47,217 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:47,218 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:47,693 INFO    wandb-upload_5:3042423 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/files/config.yaml
2024-01-26 17:20:47,733 INFO    wandb-upload_3:3042423 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/files/output.log
2024-01-26 17:20:47,783 INFO    wandb-upload_2:3042423 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/files/wandb-summary.json
2024-01-26 17:20:48,218 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:48,219 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:48,307 INFO    wandb-upload_1:3042423 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/files/conda-environment.yaml
2024-01-26 17:20:48,333 INFO    wandb-upload_4:3042423 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/files/requirements.txt
2024-01-26 17:20:49,219 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:49,221 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:50,220 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:50,220 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:51,221 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:20:51,222 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:51,222 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:52,223 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:52,223 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:53,224 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:53,224 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:54,224 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:54,224 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:55,225 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:55,225 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:56,225 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:56,226 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:56,226 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:20:57,226 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:57,226 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:58,227 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:58,228 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:59,228 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:59,228 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:00,229 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:00,229 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:01,229 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:01,229 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:01,230 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:02,230 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:02,231 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:03,231 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:03,231 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:04,233 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:04,233 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:05,234 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:05,234 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:06,236 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:06,236 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:06,237 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:07,237 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:07,238 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:08,238 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:08,238 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:09,238 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:09,239 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:10,240 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:10,241 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:11,241 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:11,242 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:11,243 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:12,243 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:12,243 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:13,243 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:13,244 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:14,245 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:14,245 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:15,245 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:15,246 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:16,247 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:16,247 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:16,248 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:17,247 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:17,248 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:18,249 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:18,249 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:19,250 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:19,251 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:20,252 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:20,252 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:21,253 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:21,253 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:21,254 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:22,255 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:22,255 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:23,256 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:23,257 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:24,258 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:24,258 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:25,259 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:25,260 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:26,261 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:26,261 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:26,262 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:27,261 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:27,262 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:28,262 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:28,263 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:29,263 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:29,264 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:30,264 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:30,264 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:31,265 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:31,266 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:31,266 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:32,268 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:32,268 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:33,269 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:33,270 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:34,270 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:34,271 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:35,271 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:35,272 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:36,273 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:36,273 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:36,274 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:37,274 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:37,274 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:38,275 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:38,276 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:39,276 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:39,277 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:40,278 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:40,278 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:41,279 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:41,279 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:41,280 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:42,281 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:42,282 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:43,282 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:43,282 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:44,283 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:44,284 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:45,284 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:45,284 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:46,285 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:46,286 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:46,286 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:47,286 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:47,287 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:48,288 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:48,288 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:49,289 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:49,290 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:50,291 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:50,291 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:51,291 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:51,292 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:51,292 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:52,292 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:52,292 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:53,292 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:53,293 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:54,293 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:54,293 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:55,294 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:55,294 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:56,295 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:56,295 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:56,295 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:57,296 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:57,297 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:58,297 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:58,298 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:59,298 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:59,299 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:00,300 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:00,300 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:01,301 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:01,301 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:01,302 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:02,302 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:02,303 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:03,303 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:03,304 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:04,304 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:04,305 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:05,306 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:05,306 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:06,307 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:06,307 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:06,310 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:07,308 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:07,309 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:08,308 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:08,309 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:09,309 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:09,310 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:10,310 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:10,310 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:11,310 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:11,311 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:11,311 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:12,311 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:12,311 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:13,312 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:13,313 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:14,313 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:14,313 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:15,314 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:15,314 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:16,314 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:16,314 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:16,314 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:17,314 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:17,315 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:18,316 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:18,316 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:19,317 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:19,317 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:20,317 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:20,318 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:21,318 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:21,319 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:21,319 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:22,319 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:22,320 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:23,320 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:23,321 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:24,322 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:24,323 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:25,323 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:25,324 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:26,324 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:26,324 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:26,324 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:27,324 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:27,325 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:28,326 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:28,326 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:29,327 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:29,327 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:30,327 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:30,327 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:31,328 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:31,328 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:31,328 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:32,328 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:32,328 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:33,329 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:33,330 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:34,330 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:34,331 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:35,331 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:35,331 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:36,332 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:36,332 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:36,332 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:37,332 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:37,333 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:38,333 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:38,334 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:39,334 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:39,335 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:40,335 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:40,336 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:41,336 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:41,336 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:41,337 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:42,338 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:42,338 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:43,339 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:43,340 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:44,340 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:44,341 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:45,341 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:45,341 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:46,342 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:46,342 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:46,343 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:47,343 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:47,344 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:48,345 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:48,345 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:49,346 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:49,347 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:50,347 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:50,347 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:51,348 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:51,348 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:51,349 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:52,350 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:52,350 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:53,351 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:53,351 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:54,353 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:54,353 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:55,354 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:55,355 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:56,355 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:56,356 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:56,356 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:57,356 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:57,357 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:58,358 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:58,358 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:59,358 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:59,358 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:00,359 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:00,360 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:01,361 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:01,362 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:01,362 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:02,362 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:02,363 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:03,363 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:03,363 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:04,364 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:04,364 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:05,364 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:05,365 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:06,366 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:06,367 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:06,367 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:07,367 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:07,368 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:08,368 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:08,368 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:09,369 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:09,369 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:10,369 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:10,370 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:11,370 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:11,370 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:11,371 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:12,371 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:12,371 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:13,372 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:13,373 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:14,373 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:14,373 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:15,374 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:15,374 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:16,375 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:16,375 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:16,376 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:17,375 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:17,376 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:18,376 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:18,377 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:19,377 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:19,378 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:20,379 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:20,380 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:21,380 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:21,381 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:21,382 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:22,381 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:22,382 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:23,382 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:23,382 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:24,382 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:24,383 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:25,383 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:25,383 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:26,383 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:26,384 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:26,384 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:27,384 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:27,384 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:28,384 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:28,385 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:29,385 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:29,386 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:30,386 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:30,386 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:31,387 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:31,387 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:31,387 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:32,387 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:32,388 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:33,388 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:33,388 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:34,389 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:34,389 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:35,389 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:35,390 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:36,391 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:36,391 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:36,391 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:37,392 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:37,392 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:38,392 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:38,393 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:39,394 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:39,394 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:40,394 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:40,395 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:41,395 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:41,396 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:41,396 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:42,396 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:42,396 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:43,397 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:43,398 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:44,398 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:44,399 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:45,399 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:45,400 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:46,400 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:46,400 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:46,400 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:47,400 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:47,401 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:48,401 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:48,401 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:49,402 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:49,402 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:50,402 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:50,403 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:51,404 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:51,404 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:51,404 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:52,404 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:52,405 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:53,405 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:53,406 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:54,406 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:54,407 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:55,407 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:55,407 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:56,407 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:56,408 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:56,408 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:57,408 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:57,409 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:58,409 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:58,409 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:59,409 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:59,409 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:00,410 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:00,411 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:01,411 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:01,412 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:01,412 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:24:02,412 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:02,412 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:03,413 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:03,414 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:04,415 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:04,415 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:05,415 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:05,416 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:06,417 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:24:06,417 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:06,418 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:07,417 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:07,418 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:08,419 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:08,419 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:09,420 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:09,421 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:10,421 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:10,421 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:11,422 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:11,422 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:11,422 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:24:12,422 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:12,422 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:13,423 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:13,423 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:14,423 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:14,423 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:15,424 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:15,424 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:16,424 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:16,425 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:16,425 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:24:17,425 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:17,425 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:18,425 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:18,426 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:19,426 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:19,426 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:20,427 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:20,427 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:21,428 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:21,428 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:24:21,429 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:22,430 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:22,430 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:23,431 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:23,432 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:24,432 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:24,433 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:25,433 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:25,435 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:26,435 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:26,436 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:24:26,436 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:27,436 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:27,437 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:28,437 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:28,437 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:29,438 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:29,439 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:30,439 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:30,439 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:31,439 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:31,440 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:31,440 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:24:32,440 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:32,441 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:33,440 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:33,441 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:34,442 DEBUG   HandlerThread:3042423 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:34,443 DEBUG   SenderThread:3042423 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:34,978 WARNING StreamThr :3042423 [internal.py:is_dead():414] Internal process exiting, parent pid 3042149 disappeared
2024-01-26 17:24:34,978 ERROR   StreamThr :3042423 [internal.py:wandb_internal():152] Internal process shutdown.
2024-01-26 17:24:35,443 INFO    HandlerThread:3042423 [handler.py:finish():869] shutting down handler
2024-01-26 17:24:35,443 INFO    WriterThread:3042423 [datastore.py:close():296] close: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-36lzu9m5/run-36lzu9m5.wandb
2024-01-26 17:24:35,443 INFO    SenderThread:3042423 [sender.py:finish():1572] shutting down sender
2024-01-26 17:24:35,443 INFO    SenderThread:3042423 [file_pusher.py:finish():175] shutting down file pusher
2024-01-26 17:24:35,443 INFO    SenderThread:3042423 [file_pusher.py:join():181] waiting for file pusher
2024-01-26 17:24:42,641 INFO    wandb-upload_0:3042423 [upload_job.py:push():131] Uploaded file /tmp/tmpkdmbo5xbwandb/ryjjx6pg-wandb-metadata.json
2024-01-26 17:24:42,842 INFO    Thread-11 :3042423 [sender.py:transition_state():617] send defer: 11
2024-01-26 17:24:42,952 INFO    SenderThread:3042423 [file_stream.py:finish():595] file stream finish called
2024-01-26 17:24:44,768 INFO    SenderThread:3042423 [file_stream.py:finish():599] file stream finish is done
