2024-01-26 17:34:42,247 INFO    StreamThr :3081776 [internal.py:wandb_internal():86] W&B internal server running at pid: 3081776, started at: 2024-01-26 17:34:42.240944
2024-01-26 17:34:42,291 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status
2024-01-26 17:34:42,298 INFO    WriterThread:3081776 [datastore.py:open_for_write():87] open: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-zc29aazf/run-zc29aazf.wandb
2024-01-26 17:34:42,299 DEBUG   SenderThread:3081776 [sender.py:send():382] send: header
2024-01-26 17:34:42,304 DEBUG   SenderThread:3081776 [sender.py:send():382] send: run
2024-01-26 17:34:45,419 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: check_version
2024-01-26 17:34:45,426 INFO    SenderThread:3081776 [dir_watcher.py:__init__():211] watching files in: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-zc29aazf/files
2024-01-26 17:34:45,426 INFO    SenderThread:3081776 [sender.py:_start_run_threads():1136] run started: zc29aazf with start time 1706261682.16951
2024-01-26 17:34:45,427 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: check_version
2024-01-26 17:34:45,924 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: run_start
2024-01-26 17:34:45,993 DEBUG   HandlerThread:3081776 [system_info.py:__init__():27] System info init
2024-01-26 17:34:45,993 DEBUG   HandlerThread:3081776 [system_info.py:__init__():42] System info init done
2024-01-26 17:34:45,993 INFO    HandlerThread:3081776 [system_monitor.py:start():194] Starting system monitor
2024-01-26 17:34:45,996 INFO    SystemMonitor:3081776 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-01-26 17:34:45,997 INFO    HandlerThread:3081776 [system_monitor.py:probe():214] Collecting system info
2024-01-26 17:34:46,016 INFO    SystemMonitor:3081776 [interfaces.py:start():190] Started cpu monitoring
2024-01-26 17:34:46,089 INFO    SystemMonitor:3081776 [interfaces.py:start():190] Started disk monitoring
2024-01-26 17:34:46,131 INFO    SystemMonitor:3081776 [interfaces.py:start():190] Started gpu monitoring
2024-01-26 17:34:46,136 INFO    SystemMonitor:3081776 [interfaces.py:start():190] Started memory monitoring
2024-01-26 17:34:46,190 INFO    SystemMonitor:3081776 [interfaces.py:start():190] Started network monitoring
2024-01-26 17:34:46,217 DEBUG   HandlerThread:3081776 [system_info.py:probe():151] Probing system
2024-01-26 17:34:46,267 DEBUG   HandlerThread:3081776 [system_info.py:_probe_git():136] Probing git
2024-01-26 17:34:46,330 DEBUG   HandlerThread:3081776 [system_info.py:_probe_git():144] Probing git done
2024-01-26 17:34:46,330 DEBUG   HandlerThread:3081776 [system_info.py:probe():199] Probing system done
2024-01-26 17:34:46,330 DEBUG   HandlerThread:3081776 [system_monitor.py:probe():223] {'os': 'Linux-5.15.0-91-generic-x86_64-with-glibc2.17', 'python': '3.8.17', 'heartbeatAt': '2024-01-26T09:34:46.217949', 'startedAt': '2024-01-26T09:34:42.163600', 'docker': None, 'cuda': None, 'args': ('--local_rank=7', '--config_file', 'config/bert_pretraining_phase2_config.json', '--input_dir', '/home/yanxindong/mkor/bert/data/encoded/sequences_lowercase_max_seq_len_512_next_seq_task_true', '--output_dir', 'results/adam', '--weight_decay', '0.01', '--num_steps_per_checkpoint', '200'), 'state': 'running', 'program': 'run_pretraining.py', 'codePathLocal': 'run_pretraining.py', 'codePath': 'bert/run_pretraining.py', 'git': {'remote': 'https://github.com/kkkjj-d/mkor.git', 'commit': 'efe99e84fef5594780cfb1df6d6a1f61da4ebba0'}, 'email': '1262670315@qq.com', 'root': '/home/yanxindong/mkor', 'host': 'a6000-X640-G40', 'username': 'yanxindong', 'executable': '/home/yanxindong/anaconda/envs/eva/bin/python', 'cpu_count': 64, 'cpu_count_logical': 128, 'cpu_freq': {'current': 2982.6549531249993, 'min': 800.0, 'max': 3400.0}, 'cpu_freq_per_core': [{'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2578.04, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2963.172, 'min': 800.0, 'max': 3400.0}, {'current': 2915.105, 'min': 800.0, 'max': 3400.0}, {'current': 2000.0, 'min': 800.0, 'max': 3400.0}, {'current': 2707.683, 'min': 800.0, 'max': 3400.0}, {'current': 3247.98, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3251.864, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2915.45, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3123.315, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 1100.0, 'min': 800.0, 'max': 3400.0}, {'current': 2771.535, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2427.508, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3100.0, 'min': 800.0, 'max': 3400.0}, {'current': 2386.128, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 2260.266, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 1900.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2582.714, 'min': 800.0, 'max': 3400.0}, {'current': 3280.397, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 2370.9, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2724.317, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2000.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 1073.591, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 1800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 2000.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2920.629, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2389.485, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 2500.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 2459.372, 'min': 800.0, 'max': 3400.0}, {'current': 1300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 2199.997, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 1100.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1000.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}], 'disk': {'/': {'total': 438.05088806152344, 'used': 28.072593688964844}}, 'gpu': 'NVIDIA RTX A6000', 'gpu_count': 8, 'gpu_devices': [{'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}], 'memory': {'total': 503.51250076293945}}
2024-01-26 17:34:46,330 INFO    HandlerThread:3081776 [system_monitor.py:probe():224] Finished collecting system info
2024-01-26 17:34:46,330 INFO    HandlerThread:3081776 [system_monitor.py:probe():227] Publishing system info
2024-01-26 17:34:46,331 DEBUG   HandlerThread:3081776 [system_info.py:_save_conda():208] Saving list of conda packages installed into the current environment
2024-01-26 17:34:46,430 INFO    Thread-12 :3081776 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-zc29aazf/files/conda-environment.yaml
2024-01-26 17:34:56,429 INFO    Thread-12 :3081776 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-zc29aazf/files/conda-environment.yaml
2024-01-26 17:34:56,819 DEBUG   HandlerThread:3081776 [system_info.py:_save_conda():220] Saving conda packages done
2024-01-26 17:34:56,821 INFO    HandlerThread:3081776 [system_monitor.py:probe():229] Finished publishing system info
2024-01-26 17:34:56,832 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:34:56,837 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:34:56,838 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:34:56,838 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:34:56,838 DEBUG   SenderThread:3081776 [sender.py:send():382] send: files
2024-01-26 17:34:56,838 INFO    SenderThread:3081776 [sender.py:_save_file():1403] saving file wandb-metadata.json with policy now
2024-01-26 17:34:56,842 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: python_packages
2024-01-26 17:34:56,843 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: python_packages
2024-01-26 17:34:56,903 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:34:56,904 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:34:57,008 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:34:57,403 ERROR   wandb-upload_0:3081776 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/zc29aazf/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XZr95jKpKGJjfVoZ8s4%2FJxV9LHcwI%2FmHsXHrOlPqW14J4w9JMM9ZliVbMUwdJ%2FNhRz6TeLejJyzA3yZ6IKuzehiHf5RaqwzaFAGU6T2nLkW5k4QOW1nu9lGrasnZzJfpAApIQdDvGoJZsvifYINf9%2Fp0LfysY7ztx5yuodxDFZnrEFWLIIMd1pZ%2FvEomdwk%2BrhOiTKnfEmKoJhDwcMyuVk1o1tEwzdsfUZB7LOgIZm6UGT1bK9b%2BvgVAAhNFJJg11fc32KR4MjVQiYq8k9UMCXoPz2KqWATJjVWEaV%2BRhvgDXOcuwPkmXj3SORdpJYgsd8ta33bEvZXrPpSgbuzt%2Fw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/zc29aazf/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XZr95jKpKGJjfVoZ8s4%2FJxV9LHcwI%2FmHsXHrOlPqW14J4w9JMM9ZliVbMUwdJ%2FNhRz6TeLejJyzA3yZ6IKuzehiHf5RaqwzaFAGU6T2nLkW5k4QOW1nu9lGrasnZzJfpAApIQdDvGoJZsvifYINf9%2Fp0LfysY7ztx5yuodxDFZnrEFWLIIMd1pZ%2FvEomdwk%2BrhOiTKnfEmKoJhDwcMyuVk1o1tEwzdsfUZB7LOgIZm6UGT1bK9b%2BvgVAAhNFJJg11fc32KR4MjVQiYq8k9UMCXoPz2KqWATJjVWEaV%2BRhvgDXOcuwPkmXj3SORdpJYgsd8ta33bEvZXrPpSgbuzt%2Fw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff7dc351430>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:34:57,403 ERROR   wandb-upload_0:3081776 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15653'}
2024-01-26 17:34:57,403 ERROR   wandb-upload_0:3081776 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:34:57,431 INFO    Thread-12 :3081776 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-zc29aazf/files/wandb-metadata.json
2024-01-26 17:34:57,431 INFO    Thread-12 :3081776 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-zc29aazf/files/requirements.txt
2024-01-26 17:34:57,583 DEBUG   SenderThread:3081776 [sender.py:send():382] send: telemetry
2024-01-26 17:34:58,583 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:34:58,652 ERROR   wandb-upload_0:3081776 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/zc29aazf/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XZr95jKpKGJjfVoZ8s4%2FJxV9LHcwI%2FmHsXHrOlPqW14J4w9JMM9ZliVbMUwdJ%2FNhRz6TeLejJyzA3yZ6IKuzehiHf5RaqwzaFAGU6T2nLkW5k4QOW1nu9lGrasnZzJfpAApIQdDvGoJZsvifYINf9%2Fp0LfysY7ztx5yuodxDFZnrEFWLIIMd1pZ%2FvEomdwk%2BrhOiTKnfEmKoJhDwcMyuVk1o1tEwzdsfUZB7LOgIZm6UGT1bK9b%2BvgVAAhNFJJg11fc32KR4MjVQiYq8k9UMCXoPz2KqWATJjVWEaV%2BRhvgDXOcuwPkmXj3SORdpJYgsd8ta33bEvZXrPpSgbuzt%2Fw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/zc29aazf/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XZr95jKpKGJjfVoZ8s4%2FJxV9LHcwI%2FmHsXHrOlPqW14J4w9JMM9ZliVbMUwdJ%2FNhRz6TeLejJyzA3yZ6IKuzehiHf5RaqwzaFAGU6T2nLkW5k4QOW1nu9lGrasnZzJfpAApIQdDvGoJZsvifYINf9%2Fp0LfysY7ztx5yuodxDFZnrEFWLIIMd1pZ%2FvEomdwk%2BrhOiTKnfEmKoJhDwcMyuVk1o1tEwzdsfUZB7LOgIZm6UGT1bK9b%2BvgVAAhNFJJg11fc32KR4MjVQiYq8k9UMCXoPz2KqWATJjVWEaV%2BRhvgDXOcuwPkmXj3SORdpJYgsd8ta33bEvZXrPpSgbuzt%2Fw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff7dc33fb20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:34:58,652 ERROR   wandb-upload_0:3081776 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15653'}
2024-01-26 17:34:58,652 ERROR   wandb-upload_0:3081776 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:35:01,070 ERROR   wandb-upload_0:3081776 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/zc29aazf/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XZr95jKpKGJjfVoZ8s4%2FJxV9LHcwI%2FmHsXHrOlPqW14J4w9JMM9ZliVbMUwdJ%2FNhRz6TeLejJyzA3yZ6IKuzehiHf5RaqwzaFAGU6T2nLkW5k4QOW1nu9lGrasnZzJfpAApIQdDvGoJZsvifYINf9%2Fp0LfysY7ztx5yuodxDFZnrEFWLIIMd1pZ%2FvEomdwk%2BrhOiTKnfEmKoJhDwcMyuVk1o1tEwzdsfUZB7LOgIZm6UGT1bK9b%2BvgVAAhNFJJg11fc32KR4MjVQiYq8k9UMCXoPz2KqWATJjVWEaV%2BRhvgDXOcuwPkmXj3SORdpJYgsd8ta33bEvZXrPpSgbuzt%2Fw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/zc29aazf/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XZr95jKpKGJjfVoZ8s4%2FJxV9LHcwI%2FmHsXHrOlPqW14J4w9JMM9ZliVbMUwdJ%2FNhRz6TeLejJyzA3yZ6IKuzehiHf5RaqwzaFAGU6T2nLkW5k4QOW1nu9lGrasnZzJfpAApIQdDvGoJZsvifYINf9%2Fp0LfysY7ztx5yuodxDFZnrEFWLIIMd1pZ%2FvEomdwk%2BrhOiTKnfEmKoJhDwcMyuVk1o1tEwzdsfUZB7LOgIZm6UGT1bK9b%2BvgVAAhNFJJg11fc32KR4MjVQiYq8k9UMCXoPz2KqWATJjVWEaV%2BRhvgDXOcuwPkmXj3SORdpJYgsd8ta33bEvZXrPpSgbuzt%2Fw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff7dc351340>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:35:01,070 ERROR   wandb-upload_0:3081776 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15653'}
2024-01-26 17:35:01,070 ERROR   wandb-upload_0:3081776 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:35:01,070 INFO    wandb-upload_0:3081776 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7ff7dc351340>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/zc29aazf/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XZr95jKpKGJjfVoZ8s4%2FJxV9LHcwI%2FmHsXHrOlPqW14J4w9JMM9ZliVbMUwdJ%2FNhRz6TeLejJyzA3yZ6IKuzehiHf5RaqwzaFAGU6T2nLkW5k4QOW1nu9lGrasnZzJfpAApIQdDvGoJZsvifYINf9%2Fp0LfysY7ztx5yuodxDFZnrEFWLIIMd1pZ%2FvEomdwk%2BrhOiTKnfEmKoJhDwcMyuVk1o1tEwzdsfUZB7LOgIZm6UGT1bK9b%2BvgVAAhNFJJg11fc32KR4MjVQiYq8k9UMCXoPz2KqWATJjVWEaV%2BRhvgDXOcuwPkmXj3SORdpJYgsd8ta33bEvZXrPpSgbuzt%2Fw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff7dc351340>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/zc29aazf/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XZr95jKpKGJjfVoZ8s4%2FJxV9LHcwI%2FmHsXHrOlPqW14J4w9JMM9ZliVbMUwdJ%2FNhRz6TeLejJyzA3yZ6IKuzehiHf5RaqwzaFAGU6T2nLkW5k4QOW1nu9lGrasnZzJfpAApIQdDvGoJZsvifYINf9%2Fp0LfysY7ztx5yuodxDFZnrEFWLIIMd1pZ%2FvEomdwk%2BrhOiTKnfEmKoJhDwcMyuVk1o1tEwzdsfUZB7LOgIZm6UGT1bK9b%2BvgVAAhNFJJg11fc32KR4MjVQiYq8k9UMCXoPz2KqWATJjVWEaV%2BRhvgDXOcuwPkmXj3SORdpJYgsd8ta33bEvZXrPpSgbuzt%2Fw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff7dc351340>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2789, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-01-26 17:35:03,585 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:35:05,366 ERROR   wandb-upload_0:3081776 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/zc29aazf/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XZr95jKpKGJjfVoZ8s4%2FJxV9LHcwI%2FmHsXHrOlPqW14J4w9JMM9ZliVbMUwdJ%2FNhRz6TeLejJyzA3yZ6IKuzehiHf5RaqwzaFAGU6T2nLkW5k4QOW1nu9lGrasnZzJfpAApIQdDvGoJZsvifYINf9%2Fp0LfysY7ztx5yuodxDFZnrEFWLIIMd1pZ%2FvEomdwk%2BrhOiTKnfEmKoJhDwcMyuVk1o1tEwzdsfUZB7LOgIZm6UGT1bK9b%2BvgVAAhNFJJg11fc32KR4MjVQiYq8k9UMCXoPz2KqWATJjVWEaV%2BRhvgDXOcuwPkmXj3SORdpJYgsd8ta33bEvZXrPpSgbuzt%2Fw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/zc29aazf/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XZr95jKpKGJjfVoZ8s4%2FJxV9LHcwI%2FmHsXHrOlPqW14J4w9JMM9ZliVbMUwdJ%2FNhRz6TeLejJyzA3yZ6IKuzehiHf5RaqwzaFAGU6T2nLkW5k4QOW1nu9lGrasnZzJfpAApIQdDvGoJZsvifYINf9%2Fp0LfysY7ztx5yuodxDFZnrEFWLIIMd1pZ%2FvEomdwk%2BrhOiTKnfEmKoJhDwcMyuVk1o1tEwzdsfUZB7LOgIZm6UGT1bK9b%2BvgVAAhNFJJg11fc32KR4MjVQiYq8k9UMCXoPz2KqWATJjVWEaV%2BRhvgDXOcuwPkmXj3SORdpJYgsd8ta33bEvZXrPpSgbuzt%2Fw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff7dc351b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:35:05,367 ERROR   wandb-upload_0:3081776 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15653'}
2024-01-26 17:35:05,367 ERROR   wandb-upload_0:3081776 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:35:08,585 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:35:11,899 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:35:11,899 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:35:12,006 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:35:15,129 ERROR   wandb-upload_0:3081776 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/zc29aazf/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XZr95jKpKGJjfVoZ8s4%2FJxV9LHcwI%2FmHsXHrOlPqW14J4w9JMM9ZliVbMUwdJ%2FNhRz6TeLejJyzA3yZ6IKuzehiHf5RaqwzaFAGU6T2nLkW5k4QOW1nu9lGrasnZzJfpAApIQdDvGoJZsvifYINf9%2Fp0LfysY7ztx5yuodxDFZnrEFWLIIMd1pZ%2FvEomdwk%2BrhOiTKnfEmKoJhDwcMyuVk1o1tEwzdsfUZB7LOgIZm6UGT1bK9b%2BvgVAAhNFJJg11fc32KR4MjVQiYq8k9UMCXoPz2KqWATJjVWEaV%2BRhvgDXOcuwPkmXj3SORdpJYgsd8ta33bEvZXrPpSgbuzt%2Fw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/zc29aazf/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XZr95jKpKGJjfVoZ8s4%2FJxV9LHcwI%2FmHsXHrOlPqW14J4w9JMM9ZliVbMUwdJ%2FNhRz6TeLejJyzA3yZ6IKuzehiHf5RaqwzaFAGU6T2nLkW5k4QOW1nu9lGrasnZzJfpAApIQdDvGoJZsvifYINf9%2Fp0LfysY7ztx5yuodxDFZnrEFWLIIMd1pZ%2FvEomdwk%2BrhOiTKnfEmKoJhDwcMyuVk1o1tEwzdsfUZB7LOgIZm6UGT1bK9b%2BvgVAAhNFJJg11fc32KR4MjVQiYq8k9UMCXoPz2KqWATJjVWEaV%2BRhvgDXOcuwPkmXj3SORdpJYgsd8ta33bEvZXrPpSgbuzt%2Fw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff7dc33f220>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:35:15,129 ERROR   wandb-upload_0:3081776 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15653'}
2024-01-26 17:35:15,129 ERROR   wandb-upload_0:3081776 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:35:15,491 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:35:17,449 INFO    Thread-12 :3081776 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-zc29aazf/files/config.yaml
2024-01-26 17:35:22,268 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:35:26,899 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:35:26,900 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:35:27,046 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:35:27,273 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:35:32,275 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:35:32,803 ERROR   wandb-upload_0:3081776 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/zc29aazf/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XZr95jKpKGJjfVoZ8s4%2FJxV9LHcwI%2FmHsXHrOlPqW14J4w9JMM9ZliVbMUwdJ%2FNhRz6TeLejJyzA3yZ6IKuzehiHf5RaqwzaFAGU6T2nLkW5k4QOW1nu9lGrasnZzJfpAApIQdDvGoJZsvifYINf9%2Fp0LfysY7ztx5yuodxDFZnrEFWLIIMd1pZ%2FvEomdwk%2BrhOiTKnfEmKoJhDwcMyuVk1o1tEwzdsfUZB7LOgIZm6UGT1bK9b%2BvgVAAhNFJJg11fc32KR4MjVQiYq8k9UMCXoPz2KqWATJjVWEaV%2BRhvgDXOcuwPkmXj3SORdpJYgsd8ta33bEvZXrPpSgbuzt%2Fw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/zc29aazf/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XZr95jKpKGJjfVoZ8s4%2FJxV9LHcwI%2FmHsXHrOlPqW14J4w9JMM9ZliVbMUwdJ%2FNhRz6TeLejJyzA3yZ6IKuzehiHf5RaqwzaFAGU6T2nLkW5k4QOW1nu9lGrasnZzJfpAApIQdDvGoJZsvifYINf9%2Fp0LfysY7ztx5yuodxDFZnrEFWLIIMd1pZ%2FvEomdwk%2BrhOiTKnfEmKoJhDwcMyuVk1o1tEwzdsfUZB7LOgIZm6UGT1bK9b%2BvgVAAhNFJJg11fc32KR4MjVQiYq8k9UMCXoPz2KqWATJjVWEaV%2BRhvgDXOcuwPkmXj3SORdpJYgsd8ta33bEvZXrPpSgbuzt%2Fw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff7dc2984c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:35:32,803 ERROR   wandb-upload_0:3081776 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15653'}
2024-01-26 17:35:32,803 ERROR   wandb-upload_0:3081776 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:35:37,275 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:35:41,899 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:35:41,899 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:35:42,006 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:35:43,192 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:35:46,191 DEBUG   SystemMonitor:3081776 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-01-26 17:35:46,195 DEBUG   SenderThread:3081776 [sender.py:send():382] send: stats
2024-01-26 17:35:48,196 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:35:53,198 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:35:56,899 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:35:56,899 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:35:57,006 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:35:58,207 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:36:03,217 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:36:07,387 ERROR   wandb-upload_0:3081776 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/zc29aazf/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XZr95jKpKGJjfVoZ8s4%2FJxV9LHcwI%2FmHsXHrOlPqW14J4w9JMM9ZliVbMUwdJ%2FNhRz6TeLejJyzA3yZ6IKuzehiHf5RaqwzaFAGU6T2nLkW5k4QOW1nu9lGrasnZzJfpAApIQdDvGoJZsvifYINf9%2Fp0LfysY7ztx5yuodxDFZnrEFWLIIMd1pZ%2FvEomdwk%2BrhOiTKnfEmKoJhDwcMyuVk1o1tEwzdsfUZB7LOgIZm6UGT1bK9b%2BvgVAAhNFJJg11fc32KR4MjVQiYq8k9UMCXoPz2KqWATJjVWEaV%2BRhvgDXOcuwPkmXj3SORdpJYgsd8ta33bEvZXrPpSgbuzt%2Fw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/zc29aazf/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XZr95jKpKGJjfVoZ8s4%2FJxV9LHcwI%2FmHsXHrOlPqW14J4w9JMM9ZliVbMUwdJ%2FNhRz6TeLejJyzA3yZ6IKuzehiHf5RaqwzaFAGU6T2nLkW5k4QOW1nu9lGrasnZzJfpAApIQdDvGoJZsvifYINf9%2Fp0LfysY7ztx5yuodxDFZnrEFWLIIMd1pZ%2FvEomdwk%2BrhOiTKnfEmKoJhDwcMyuVk1o1tEwzdsfUZB7LOgIZm6UGT1bK9b%2BvgVAAhNFJJg11fc32KR4MjVQiYq8k9UMCXoPz2KqWATJjVWEaV%2BRhvgDXOcuwPkmXj3SORdpJYgsd8ta33bEvZXrPpSgbuzt%2Fw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff7dc33fcd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:36:07,387 ERROR   wandb-upload_0:3081776 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15653'}
2024-01-26 17:36:07,387 ERROR   wandb-upload_0:3081776 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:36:08,238 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:36:11,901 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:36:11,901 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:36:12,006 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:36:13,266 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:36:16,198 DEBUG   SenderThread:3081776 [sender.py:send():382] send: stats
2024-01-26 17:36:19,199 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:36:24,200 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:36:26,900 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:36:26,901 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:36:27,006 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:36:29,262 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:36:32,607 INFO    Thread-12 :3081776 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-zc29aazf/files/output.log
2024-01-26 17:36:34,608 INFO    Thread-12 :3081776 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-zc29aazf/files/output.log
2024-01-26 17:36:35,145 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:36:40,145 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:36:45,146 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:36:46,199 DEBUG   SenderThread:3081776 [sender.py:send():382] send: stats
2024-01-26 17:36:46,340 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:36:46,340 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:36:46,344 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:36:51,052 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:36:56,130 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:37:01,130 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:37:01,339 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:37:01,340 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:37:01,382 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:37:06,687 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:37:11,688 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:37:16,201 DEBUG   SenderThread:3081776 [sender.py:send():382] send: stats
2024-01-26 17:37:16,362 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:37:16,366 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:37:16,381 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:37:16,796 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:37:21,330 INFO    wandb-upload_0:3081776 [upload_job.py:push():131] Uploaded file /tmp/tmphvq6lymtwandb/3v052pte-wandb-metadata.json
2024-01-26 17:37:21,810 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:37:26,822 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:37:31,342 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:37:31,342 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:37:31,382 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:37:32,712 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:37:37,713 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:37:42,714 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:37:46,204 DEBUG   SenderThread:3081776 [sender.py:send():382] send: stats
2024-01-26 17:37:46,341 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:37:46,342 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:37:46,382 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:37:48,700 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:37:53,701 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:37:58,706 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:38:01,341 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:38:01,342 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:38:01,382 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:38:04,709 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:38:09,814 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:38:14,961 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:38:16,206 DEBUG   SenderThread:3081776 [sender.py:send():382] send: stats
2024-01-26 17:38:16,341 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:38:16,342 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:38:16,382 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:38:20,646 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:38:25,698 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:38:30,749 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:38:31,341 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:38:31,342 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:38:31,382 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:38:36,810 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:38:41,811 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:38:46,213 DEBUG   SenderThread:3081776 [sender.py:send():382] send: stats
2024-01-26 17:38:46,418 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:38:46,418 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:38:46,418 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:38:47,771 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:38:52,772 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:38:57,773 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:39:01,342 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:39:01,342 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:39:01,390 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:39:03,657 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:39:08,658 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:39:13,659 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:39:16,210 DEBUG   SenderThread:3081776 [sender.py:send():382] send: stats
2024-01-26 17:39:16,342 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:39:16,342 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:39:16,386 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:39:19,686 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:39:24,790 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:39:29,792 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:39:31,357 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:39:31,358 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:39:31,386 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:39:35,661 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:39:40,662 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:39:45,742 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:39:46,276 DEBUG   SenderThread:3081776 [sender.py:send():382] send: stats
2024-01-26 17:39:46,342 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:39:46,342 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:39:46,386 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:39:51,702 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:39:56,796 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:40:01,390 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:40:01,390 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:40:01,390 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:40:02,692 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:40:07,692 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:40:12,693 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:40:16,275 DEBUG   SenderThread:3081776 [sender.py:send():382] send: stats
2024-01-26 17:40:16,342 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:40:16,342 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:40:16,386 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:40:18,589 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:40:23,591 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:40:28,596 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:40:31,342 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:40:31,343 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:40:31,385 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:40:33,701 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:40:38,828 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:40:43,829 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:40:46,277 DEBUG   SenderThread:3081776 [sender.py:send():382] send: stats
2024-01-26 17:40:46,394 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:40:46,394 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:40:46,396 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:40:48,895 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:40:53,910 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:40:58,918 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:41:01,342 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:41:01,343 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:41:01,402 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:41:04,690 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:41:09,690 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:41:14,691 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:41:16,279 DEBUG   SenderThread:3081776 [sender.py:send():382] send: stats
2024-01-26 17:41:16,342 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:41:16,343 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:41:16,385 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:41:19,703 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:41:24,703 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:41:29,704 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:41:31,343 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:41:31,343 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:41:31,386 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:41:35,686 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:41:40,758 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:41:45,830 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:41:46,345 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:41:46,348 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:41:46,385 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:41:46,690 DEBUG   SenderThread:3081776 [sender.py:send():382] send: stats
2024-01-26 17:41:51,707 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:41:56,708 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:42:01,343 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:42:01,343 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:42:01,385 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:42:02,697 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:42:07,701 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:42:12,701 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:42:16,343 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:42:16,343 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:42:16,385 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:42:16,649 DEBUG   SenderThread:3081776 [sender.py:send():382] send: stats
2024-01-26 17:42:18,650 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:42:23,651 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:42:28,652 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:42:31,343 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:42:31,343 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:42:31,385 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:42:34,650 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:42:39,694 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:42:44,732 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:42:46,355 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:42:46,358 DEBUG   SenderThread:3081776 [sender.py:send():382] send: stats
2024-01-26 17:42:46,359 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:42:46,433 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:42:50,814 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:42:55,814 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:43:00,815 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:43:01,343 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:43:01,343 DEBUG   SenderThread:3081776 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:43:01,350 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:43:06,701 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:43:11,702 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:43:13,960 INFO    cpu       :3081776 [interfaces.py:monitor():140] Process cpu has exited.
2024-01-26 17:43:13,960 DEBUG   SystemMonitor:3081776 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-01-26 17:43:13,961 DEBUG   SystemMonitor:3081776 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-01-26 17:43:13,964 DEBUG   SenderThread:3081776 [sender.py:send():382] send: stats
2024-01-26 17:43:16,462 INFO    MainThread:3081776 [internal.py:handle_exit():76] Internal process exited
2024-01-26 17:43:16,965 DEBUG   HandlerThread:3081776 [handler.py:handle_request():146] handle_request: status_report
