2024-01-26 17:08:45,855 INFO    StreamThr :3042420 [internal.py:wandb_internal():86] W&B internal server running at pid: 3042420, started at: 2024-01-26 17:08:45.854783
2024-01-26 17:08:45,894 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status
2024-01-26 17:08:45,904 INFO    WriterThread:3042420 [datastore.py:open_for_write():87] open: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/run-0zgo4ysj.wandb
2024-01-26 17:08:45,905 DEBUG   SenderThread:3042420 [sender.py:send():382] send: header
2024-01-26 17:08:45,905 DEBUG   SenderThread:3042420 [sender.py:send():382] send: run
2024-01-26 17:08:46,860 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: check_version
2024-01-26 17:08:46,865 INFO    SenderThread:3042420 [dir_watcher.py:__init__():211] watching files in: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/files
2024-01-26 17:08:46,865 INFO    SenderThread:3042420 [sender.py:_start_run_threads():1136] run started: 0zgo4ysj with start time 1706260125.820221
2024-01-26 17:08:46,865 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: check_version
2024-01-26 17:08:47,343 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: run_start
2024-01-26 17:08:47,353 DEBUG   HandlerThread:3042420 [system_info.py:__init__():27] System info init
2024-01-26 17:08:47,353 DEBUG   HandlerThread:3042420 [system_info.py:__init__():42] System info init done
2024-01-26 17:08:47,353 INFO    HandlerThread:3042420 [system_monitor.py:start():194] Starting system monitor
2024-01-26 17:08:47,382 INFO    SystemMonitor:3042420 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-01-26 17:08:47,383 INFO    HandlerThread:3042420 [system_monitor.py:probe():214] Collecting system info
2024-01-26 17:08:47,398 INFO    SystemMonitor:3042420 [interfaces.py:start():190] Started cpu monitoring
2024-01-26 17:08:47,414 INFO    SystemMonitor:3042420 [interfaces.py:start():190] Started disk monitoring
2024-01-26 17:08:47,439 INFO    SystemMonitor:3042420 [interfaces.py:start():190] Started gpu monitoring
2024-01-26 17:08:47,474 INFO    SystemMonitor:3042420 [interfaces.py:start():190] Started memory monitoring
2024-01-26 17:08:47,485 INFO    SystemMonitor:3042420 [interfaces.py:start():190] Started network monitoring
2024-01-26 17:08:47,533 DEBUG   HandlerThread:3042420 [system_info.py:probe():151] Probing system
2024-01-26 17:08:47,581 DEBUG   HandlerThread:3042420 [system_info.py:_probe_git():136] Probing git
2024-01-26 17:08:47,658 DEBUG   HandlerThread:3042420 [system_info.py:_probe_git():144] Probing git done
2024-01-26 17:08:47,658 DEBUG   HandlerThread:3042420 [system_info.py:probe():199] Probing system done
2024-01-26 17:08:47,658 DEBUG   HandlerThread:3042420 [system_monitor.py:probe():223] {'os': 'Linux-5.15.0-91-generic-x86_64-with-glibc2.17', 'python': '3.8.17', 'heartbeatAt': '2024-01-26T09:08:47.534019', 'startedAt': '2024-01-26T09:08:45.785625', 'docker': None, 'cuda': None, 'args': ('--local_rank=1', '--config_file', 'config/bert_pretraining_phase2_config.json', '--input_dir', '/home/yanxindong/mkor/bert/data/encoded/sequences_lowercase_max_seq_len_512_next_seq_task_true', '--output_dir', 'results/adam', '--weight_decay', '0.01', '--num_steps_per_checkpoint', '200'), 'state': 'running', 'program': 'run_pretraining.py', 'codePathLocal': 'run_pretraining.py', 'codePath': 'bert/run_pretraining.py', 'git': {'remote': 'https://github.com/kkkjj-d/mkor.git', 'commit': 'efe99e84fef5594780cfb1df6d6a1f61da4ebba0'}, 'email': '1262670315@qq.com', 'root': '/home/yanxindong/mkor', 'host': 'a6000-X640-G40', 'username': 'yanxindong', 'executable': '/home/yanxindong/anaconda/envs/eva/bin/python', 'cpu_count': 64, 'cpu_count_logical': 128, 'cpu_freq': {'current': 2053.125, 'min': 800.0, 'max': 3400.0}, 'cpu_freq_per_core': [{'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 1400.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3100.0, 'min': 800.0, 'max': 3400.0}, {'current': 1300.0, 'min': 800.0, 'max': 3400.0}, {'current': 1400.0, 'min': 800.0, 'max': 3400.0}, {'current': 1700.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2700.0, 'min': 800.0, 'max': 3400.0}, {'current': 3000.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 1800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 840.809, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2700.0, 'min': 800.0, 'max': 3400.0}, {'current': 1225.787, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3092.752, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2420.398, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 1800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 1700.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2494.828, 'min': 800.0, 'max': 3400.0}, {'current': 2418.222, 'min': 800.0, 'max': 3400.0}, {'current': 1700.0, 'min': 800.0, 'max': 3400.0}, {'current': 1900.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.002, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 1400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1100.0, 'min': 800.0, 'max': 3400.0}, {'current': 1300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 2000.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 1500.0, 'min': 800.0, 'max': 3400.0}, {'current': 1600.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1776.029, 'min': 800.0, 'max': 3400.0}, {'current': 2200.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1600.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2000.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2356.696, 'min': 800.0, 'max': 3400.0}, {'current': 2645.145, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2200.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1506.111, 'min': 800.0, 'max': 3400.0}, {'current': 2281.499, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1700.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}], 'disk': {'/': {'total': 438.05088806152344, 'used': 28.042720794677734}}, 'gpu': 'NVIDIA RTX A6000', 'gpu_count': 8, 'gpu_devices': [{'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}], 'memory': {'total': 503.51250076293945}}
2024-01-26 17:08:47,658 INFO    HandlerThread:3042420 [system_monitor.py:probe():224] Finished collecting system info
2024-01-26 17:08:47,658 INFO    HandlerThread:3042420 [system_monitor.py:probe():227] Publishing system info
2024-01-26 17:08:47,659 DEBUG   HandlerThread:3042420 [system_info.py:_save_conda():208] Saving list of conda packages installed into the current environment
2024-01-26 17:08:47,867 INFO    Thread-12 :3042420 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/files/conda-environment.yaml
2024-01-26 17:08:57,868 INFO    Thread-12 :3042420 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/files/conda-environment.yaml
2024-01-26 17:08:58,187 DEBUG   HandlerThread:3042420 [system_info.py:_save_conda():220] Saving conda packages done
2024-01-26 17:08:58,189 INFO    HandlerThread:3042420 [system_monitor.py:probe():229] Finished publishing system info
2024-01-26 17:08:58,194 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:08:58,200 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:08:58,200 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:08:58,200 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:08:58,200 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: python_packages
2024-01-26 17:08:58,200 DEBUG   SenderThread:3042420 [sender.py:send():382] send: files
2024-01-26 17:08:58,200 INFO    SenderThread:3042420 [sender.py:_save_file():1403] saving file wandb-metadata.json with policy now
2024-01-26 17:08:58,201 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: python_packages
2024-01-26 17:08:58,235 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:08:58,235 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:08:58,269 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:08:58,597 DEBUG   SenderThread:3042420 [sender.py:send():382] send: telemetry
2024-01-26 17:08:58,868 INFO    Thread-12 :3042420 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/files/wandb-metadata.json
2024-01-26 17:08:58,868 INFO    Thread-12 :3042420 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/files/requirements.txt
2024-01-26 17:08:59,135 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/0zgo4ysj/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KjsCnUqBsjb5jQ%2BCPq0XmXuamMJA8mnI%2FUsm4CCzoSMjz8EV3wtWEeATS4p9gFOLxU%2FJuin%2F%2BDkDoPRibcKmFSX5htbrSphUbY%2BW%2BGp7u2MPW%2Fy5wKfAQ%2BX1s2HqQn%2F3t8728jewpsD%2Fz9vDD1r9KskWD8z8mx0rXRrUOVvgZegB0q%2FGsV8WjwhlkimY26j1zXpqZaLlE7uAjrsrA2DQqFapVGjTRg9xAzCMaYe0iH3Fkil%2F27VSNYxw%2FpV2aq8jBVC4w5ljvqJdCK9xUcUsrnI6WlIzt6h1Oxz%2B6b7BEQ8ofSh4ZpL5XizEOBCIewpmfgA6h%2B4KpKHgb%2Bp2Up5fAQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/0zgo4ysj/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KjsCnUqBsjb5jQ%2BCPq0XmXuamMJA8mnI%2FUsm4CCzoSMjz8EV3wtWEeATS4p9gFOLxU%2FJuin%2F%2BDkDoPRibcKmFSX5htbrSphUbY%2BW%2BGp7u2MPW%2Fy5wKfAQ%2BX1s2HqQn%2F3t8728jewpsD%2Fz9vDD1r9KskWD8z8mx0rXRrUOVvgZegB0q%2FGsV8WjwhlkimY26j1zXpqZaLlE7uAjrsrA2DQqFapVGjTRg9xAzCMaYe0iH3Fkil%2F27VSNYxw%2FpV2aq8jBVC4w5ljvqJdCK9xUcUsrnI6WlIzt6h1Oxz%2B6b7BEQ8ofSh4ZpL5XizEOBCIewpmfgA6h%2B4KpKHgb%2Bp2Up5fAQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde18550f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:08:59,135 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15622'}
2024-01-26 17:08:59,135 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:00,319 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/0zgo4ysj/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KjsCnUqBsjb5jQ%2BCPq0XmXuamMJA8mnI%2FUsm4CCzoSMjz8EV3wtWEeATS4p9gFOLxU%2FJuin%2F%2BDkDoPRibcKmFSX5htbrSphUbY%2BW%2BGp7u2MPW%2Fy5wKfAQ%2BX1s2HqQn%2F3t8728jewpsD%2Fz9vDD1r9KskWD8z8mx0rXRrUOVvgZegB0q%2FGsV8WjwhlkimY26j1zXpqZaLlE7uAjrsrA2DQqFapVGjTRg9xAzCMaYe0iH3Fkil%2F27VSNYxw%2FpV2aq8jBVC4w5ljvqJdCK9xUcUsrnI6WlIzt6h1Oxz%2B6b7BEQ8ofSh4ZpL5XizEOBCIewpmfgA6h%2B4KpKHgb%2Bp2Up5fAQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/0zgo4ysj/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KjsCnUqBsjb5jQ%2BCPq0XmXuamMJA8mnI%2FUsm4CCzoSMjz8EV3wtWEeATS4p9gFOLxU%2FJuin%2F%2BDkDoPRibcKmFSX5htbrSphUbY%2BW%2BGp7u2MPW%2Fy5wKfAQ%2BX1s2HqQn%2F3t8728jewpsD%2Fz9vDD1r9KskWD8z8mx0rXRrUOVvgZegB0q%2FGsV8WjwhlkimY26j1zXpqZaLlE7uAjrsrA2DQqFapVGjTRg9xAzCMaYe0iH3Fkil%2F27VSNYxw%2FpV2aq8jBVC4w5ljvqJdCK9xUcUsrnI6WlIzt6h1Oxz%2B6b7BEQ8ofSh4ZpL5XizEOBCIewpmfgA6h%2B4KpKHgb%2Bp2Up5fAQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde18550880>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:00,319 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15622'}
2024-01-26 17:09:00,319 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:01,598 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:02,387 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/0zgo4ysj/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KjsCnUqBsjb5jQ%2BCPq0XmXuamMJA8mnI%2FUsm4CCzoSMjz8EV3wtWEeATS4p9gFOLxU%2FJuin%2F%2BDkDoPRibcKmFSX5htbrSphUbY%2BW%2BGp7u2MPW%2Fy5wKfAQ%2BX1s2HqQn%2F3t8728jewpsD%2Fz9vDD1r9KskWD8z8mx0rXRrUOVvgZegB0q%2FGsV8WjwhlkimY26j1zXpqZaLlE7uAjrsrA2DQqFapVGjTRg9xAzCMaYe0iH3Fkil%2F27VSNYxw%2FpV2aq8jBVC4w5ljvqJdCK9xUcUsrnI6WlIzt6h1Oxz%2B6b7BEQ8ofSh4ZpL5XizEOBCIewpmfgA6h%2B4KpKHgb%2Bp2Up5fAQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/0zgo4ysj/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KjsCnUqBsjb5jQ%2BCPq0XmXuamMJA8mnI%2FUsm4CCzoSMjz8EV3wtWEeATS4p9gFOLxU%2FJuin%2F%2BDkDoPRibcKmFSX5htbrSphUbY%2BW%2BGp7u2MPW%2Fy5wKfAQ%2BX1s2HqQn%2F3t8728jewpsD%2Fz9vDD1r9KskWD8z8mx0rXRrUOVvgZegB0q%2FGsV8WjwhlkimY26j1zXpqZaLlE7uAjrsrA2DQqFapVGjTRg9xAzCMaYe0iH3Fkil%2F27VSNYxw%2FpV2aq8jBVC4w5ljvqJdCK9xUcUsrnI6WlIzt6h1Oxz%2B6b7BEQ8ofSh4ZpL5XizEOBCIewpmfgA6h%2B4KpKHgb%2Bp2Up5fAQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde18562040>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:02,388 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15622'}
2024-01-26 17:09:02,388 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:02,388 INFO    wandb-upload_0:3042420 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fde18562040>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/0zgo4ysj/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KjsCnUqBsjb5jQ%2BCPq0XmXuamMJA8mnI%2FUsm4CCzoSMjz8EV3wtWEeATS4p9gFOLxU%2FJuin%2F%2BDkDoPRibcKmFSX5htbrSphUbY%2BW%2BGp7u2MPW%2Fy5wKfAQ%2BX1s2HqQn%2F3t8728jewpsD%2Fz9vDD1r9KskWD8z8mx0rXRrUOVvgZegB0q%2FGsV8WjwhlkimY26j1zXpqZaLlE7uAjrsrA2DQqFapVGjTRg9xAzCMaYe0iH3Fkil%2F27VSNYxw%2FpV2aq8jBVC4w5ljvqJdCK9xUcUsrnI6WlIzt6h1Oxz%2B6b7BEQ8ofSh4ZpL5XizEOBCIewpmfgA6h%2B4KpKHgb%2Bp2Up5fAQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde18562040>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/0zgo4ysj/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KjsCnUqBsjb5jQ%2BCPq0XmXuamMJA8mnI%2FUsm4CCzoSMjz8EV3wtWEeATS4p9gFOLxU%2FJuin%2F%2BDkDoPRibcKmFSX5htbrSphUbY%2BW%2BGp7u2MPW%2Fy5wKfAQ%2BX1s2HqQn%2F3t8728jewpsD%2Fz9vDD1r9KskWD8z8mx0rXRrUOVvgZegB0q%2FGsV8WjwhlkimY26j1zXpqZaLlE7uAjrsrA2DQqFapVGjTRg9xAzCMaYe0iH3Fkil%2F27VSNYxw%2FpV2aq8jBVC4w5ljvqJdCK9xUcUsrnI6WlIzt6h1Oxz%2B6b7BEQ8ofSh4ZpL5XizEOBCIewpmfgA6h%2B4KpKHgb%2Bp2Up5fAQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde18562040>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2789, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-01-26 17:09:06,599 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:06,963 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/0zgo4ysj/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KjsCnUqBsjb5jQ%2BCPq0XmXuamMJA8mnI%2FUsm4CCzoSMjz8EV3wtWEeATS4p9gFOLxU%2FJuin%2F%2BDkDoPRibcKmFSX5htbrSphUbY%2BW%2BGp7u2MPW%2Fy5wKfAQ%2BX1s2HqQn%2F3t8728jewpsD%2Fz9vDD1r9KskWD8z8mx0rXRrUOVvgZegB0q%2FGsV8WjwhlkimY26j1zXpqZaLlE7uAjrsrA2DQqFapVGjTRg9xAzCMaYe0iH3Fkil%2F27VSNYxw%2FpV2aq8jBVC4w5ljvqJdCK9xUcUsrnI6WlIzt6h1Oxz%2B6b7BEQ8ofSh4ZpL5XizEOBCIewpmfgA6h%2B4KpKHgb%2Bp2Up5fAQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/0zgo4ysj/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KjsCnUqBsjb5jQ%2BCPq0XmXuamMJA8mnI%2FUsm4CCzoSMjz8EV3wtWEeATS4p9gFOLxU%2FJuin%2F%2BDkDoPRibcKmFSX5htbrSphUbY%2BW%2BGp7u2MPW%2Fy5wKfAQ%2BX1s2HqQn%2F3t8728jewpsD%2Fz9vDD1r9KskWD8z8mx0rXRrUOVvgZegB0q%2FGsV8WjwhlkimY26j1zXpqZaLlE7uAjrsrA2DQqFapVGjTRg9xAzCMaYe0iH3Fkil%2F27VSNYxw%2FpV2aq8jBVC4w5ljvqJdCK9xUcUsrnI6WlIzt6h1Oxz%2B6b7BEQ8ofSh4ZpL5XizEOBCIewpmfgA6h%2B4KpKHgb%2Bp2Up5fAQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde18599730>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:06,964 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15622'}
2024-01-26 17:09:06,964 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:11,600 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:13,235 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:09:13,236 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:09:13,278 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:09:16,618 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:16,642 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/0zgo4ysj/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KjsCnUqBsjb5jQ%2BCPq0XmXuamMJA8mnI%2FUsm4CCzoSMjz8EV3wtWEeATS4p9gFOLxU%2FJuin%2F%2BDkDoPRibcKmFSX5htbrSphUbY%2BW%2BGp7u2MPW%2Fy5wKfAQ%2BX1s2HqQn%2F3t8728jewpsD%2Fz9vDD1r9KskWD8z8mx0rXRrUOVvgZegB0q%2FGsV8WjwhlkimY26j1zXpqZaLlE7uAjrsrA2DQqFapVGjTRg9xAzCMaYe0iH3Fkil%2F27VSNYxw%2FpV2aq8jBVC4w5ljvqJdCK9xUcUsrnI6WlIzt6h1Oxz%2B6b7BEQ8ofSh4ZpL5XizEOBCIewpmfgA6h%2B4KpKHgb%2Bp2Up5fAQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/0zgo4ysj/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KjsCnUqBsjb5jQ%2BCPq0XmXuamMJA8mnI%2FUsm4CCzoSMjz8EV3wtWEeATS4p9gFOLxU%2FJuin%2F%2BDkDoPRibcKmFSX5htbrSphUbY%2BW%2BGp7u2MPW%2Fy5wKfAQ%2BX1s2HqQn%2F3t8728jewpsD%2Fz9vDD1r9KskWD8z8mx0rXRrUOVvgZegB0q%2FGsV8WjwhlkimY26j1zXpqZaLlE7uAjrsrA2DQqFapVGjTRg9xAzCMaYe0iH3Fkil%2F27VSNYxw%2FpV2aq8jBVC4w5ljvqJdCK9xUcUsrnI6WlIzt6h1Oxz%2B6b7BEQ8ofSh4ZpL5XizEOBCIewpmfgA6h%2B4KpKHgb%2Bp2Up5fAQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde18550820>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:16,642 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15622'}
2024-01-26 17:09:16,642 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:17,873 INFO    Thread-12 :3042420 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/files/config.yaml
2024-01-26 17:09:21,992 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:27,026 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:28,237 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:09:28,238 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:09:28,278 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:09:32,569 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:34,215 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/0zgo4ysj/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KjsCnUqBsjb5jQ%2BCPq0XmXuamMJA8mnI%2FUsm4CCzoSMjz8EV3wtWEeATS4p9gFOLxU%2FJuin%2F%2BDkDoPRibcKmFSX5htbrSphUbY%2BW%2BGp7u2MPW%2Fy5wKfAQ%2BX1s2HqQn%2F3t8728jewpsD%2Fz9vDD1r9KskWD8z8mx0rXRrUOVvgZegB0q%2FGsV8WjwhlkimY26j1zXpqZaLlE7uAjrsrA2DQqFapVGjTRg9xAzCMaYe0iH3Fkil%2F27VSNYxw%2FpV2aq8jBVC4w5ljvqJdCK9xUcUsrnI6WlIzt6h1Oxz%2B6b7BEQ8ofSh4ZpL5XizEOBCIewpmfgA6h%2B4KpKHgb%2Bp2Up5fAQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/0zgo4ysj/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KjsCnUqBsjb5jQ%2BCPq0XmXuamMJA8mnI%2FUsm4CCzoSMjz8EV3wtWEeATS4p9gFOLxU%2FJuin%2F%2BDkDoPRibcKmFSX5htbrSphUbY%2BW%2BGp7u2MPW%2Fy5wKfAQ%2BX1s2HqQn%2F3t8728jewpsD%2Fz9vDD1r9KskWD8z8mx0rXRrUOVvgZegB0q%2FGsV8WjwhlkimY26j1zXpqZaLlE7uAjrsrA2DQqFapVGjTRg9xAzCMaYe0iH3Fkil%2F27VSNYxw%2FpV2aq8jBVC4w5ljvqJdCK9xUcUsrnI6WlIzt6h1Oxz%2B6b7BEQ8ofSh4ZpL5XizEOBCIewpmfgA6h%2B4KpKHgb%2Bp2Up5fAQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde18562dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:34,215 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15622'}
2024-01-26 17:09:34,215 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:37,572 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:42,574 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:43,235 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:09:43,236 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:09:43,278 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:09:47,485 DEBUG   SystemMonitor:3042420 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-01-26 17:09:47,489 DEBUG   SenderThread:3042420 [sender.py:send():382] send: stats
2024-01-26 17:09:48,490 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:53,491 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:58,236 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:09:58,236 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:09:58,278 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:09:58,529 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:03,575 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:08,585 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:11,233 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/0zgo4ysj/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KjsCnUqBsjb5jQ%2BCPq0XmXuamMJA8mnI%2FUsm4CCzoSMjz8EV3wtWEeATS4p9gFOLxU%2FJuin%2F%2BDkDoPRibcKmFSX5htbrSphUbY%2BW%2BGp7u2MPW%2Fy5wKfAQ%2BX1s2HqQn%2F3t8728jewpsD%2Fz9vDD1r9KskWD8z8mx0rXRrUOVvgZegB0q%2FGsV8WjwhlkimY26j1zXpqZaLlE7uAjrsrA2DQqFapVGjTRg9xAzCMaYe0iH3Fkil%2F27VSNYxw%2FpV2aq8jBVC4w5ljvqJdCK9xUcUsrnI6WlIzt6h1Oxz%2B6b7BEQ8ofSh4ZpL5XizEOBCIewpmfgA6h%2B4KpKHgb%2Bp2Up5fAQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/0zgo4ysj/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KjsCnUqBsjb5jQ%2BCPq0XmXuamMJA8mnI%2FUsm4CCzoSMjz8EV3wtWEeATS4p9gFOLxU%2FJuin%2F%2BDkDoPRibcKmFSX5htbrSphUbY%2BW%2BGp7u2MPW%2Fy5wKfAQ%2BX1s2HqQn%2F3t8728jewpsD%2Fz9vDD1r9KskWD8z8mx0rXRrUOVvgZegB0q%2FGsV8WjwhlkimY26j1zXpqZaLlE7uAjrsrA2DQqFapVGjTRg9xAzCMaYe0iH3Fkil%2F27VSNYxw%2FpV2aq8jBVC4w5ljvqJdCK9xUcUsrnI6WlIzt6h1Oxz%2B6b7BEQ8ofSh4ZpL5XizEOBCIewpmfgA6h%2B4KpKHgb%2Bp2Up5fAQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde183c0640>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:10:11,233 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15622'}
2024-01-26 17:10:11,233 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:10:13,246 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:10:13,246 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:10:13,314 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:10:14,567 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:17,491 DEBUG   SenderThread:3042420 [sender.py:send():382] send: stats
2024-01-26 17:10:20,493 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:25,494 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:28,236 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:10:28,236 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:10:28,277 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:10:30,564 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:34,062 INFO    Thread-12 :3042420 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/files/output.log
2024-01-26 17:10:36,062 INFO    Thread-12 :3042420 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/files/output.log
2024-01-26 17:10:36,215 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:41,216 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:46,216 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:46,687 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:10:46,687 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:10:46,688 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:10:47,493 DEBUG   SenderThread:3042420 [sender.py:send():382] send: stats
2024-01-26 17:10:52,035 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:57,036 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:01,686 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:11:01,686 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:11:01,687 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:03,001 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:08,002 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:13,003 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:16,686 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:11:16,686 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:11:16,687 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:17,508 DEBUG   SenderThread:3042420 [sender.py:send():382] send: stats
2024-01-26 17:11:18,509 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:23,539 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:26,423 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/0zgo4ysj/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KjsCnUqBsjb5jQ%2BCPq0XmXuamMJA8mnI%2FUsm4CCzoSMjz8EV3wtWEeATS4p9gFOLxU%2FJuin%2F%2BDkDoPRibcKmFSX5htbrSphUbY%2BW%2BGp7u2MPW%2Fy5wKfAQ%2BX1s2HqQn%2F3t8728jewpsD%2Fz9vDD1r9KskWD8z8mx0rXRrUOVvgZegB0q%2FGsV8WjwhlkimY26j1zXpqZaLlE7uAjrsrA2DQqFapVGjTRg9xAzCMaYe0iH3Fkil%2F27VSNYxw%2FpV2aq8jBVC4w5ljvqJdCK9xUcUsrnI6WlIzt6h1Oxz%2B6b7BEQ8ofSh4ZpL5XizEOBCIewpmfgA6h%2B4KpKHgb%2Bp2Up5fAQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/0zgo4ysj/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KjsCnUqBsjb5jQ%2BCPq0XmXuamMJA8mnI%2FUsm4CCzoSMjz8EV3wtWEeATS4p9gFOLxU%2FJuin%2F%2BDkDoPRibcKmFSX5htbrSphUbY%2BW%2BGp7u2MPW%2Fy5wKfAQ%2BX1s2HqQn%2F3t8728jewpsD%2Fz9vDD1r9KskWD8z8mx0rXRrUOVvgZegB0q%2FGsV8WjwhlkimY26j1zXpqZaLlE7uAjrsrA2DQqFapVGjTRg9xAzCMaYe0iH3Fkil%2F27VSNYxw%2FpV2aq8jBVC4w5ljvqJdCK9xUcUsrnI6WlIzt6h1Oxz%2B6b7BEQ8ofSh4ZpL5XizEOBCIewpmfgA6h%2B4KpKHgb%2Bp2Up5fAQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde185395e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:11:26,423 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15622'}
2024-01-26 17:11:26,423 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:11:28,605 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:31,686 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:11:31,687 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:11:31,687 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:33,978 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:38,978 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:43,979 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:46,686 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:11:46,688 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:11:46,688 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:47,511 DEBUG   SenderThread:3042420 [sender.py:send():382] send: stats
2024-01-26 17:11:49,512 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:54,513 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:59,514 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:01,686 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:12:01,687 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:12:01,687 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:12:04,977 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:10,089 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:15,373 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:16,686 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:12:16,687 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:12:16,687 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:12:17,513 DEBUG   SenderThread:3042420 [sender.py:send():382] send: stats
2024-01-26 17:12:20,614 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:25,668 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:30,797 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:31,790 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:12:31,790 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:12:31,790 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:12:36,306 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:41,308 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:46,311 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:46,687 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:12:46,689 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:12:46,689 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:12:47,516 DEBUG   SenderThread:3042420 [sender.py:send():382] send: stats
2024-01-26 17:12:51,517 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:56,518 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:01,519 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:01,687 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:13:01,689 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:13:01,689 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:13:06,972 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:11,973 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:16,687 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:13:16,689 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:13:16,689 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:13:17,083 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:17,517 DEBUG   SenderThread:3042420 [sender.py:send():382] send: stats
2024-01-26 17:13:22,563 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:27,726 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:31,687 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:13:31,689 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:13:31,689 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:13:33,070 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:38,151 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:39,934 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/0zgo4ysj/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KjsCnUqBsjb5jQ%2BCPq0XmXuamMJA8mnI%2FUsm4CCzoSMjz8EV3wtWEeATS4p9gFOLxU%2FJuin%2F%2BDkDoPRibcKmFSX5htbrSphUbY%2BW%2BGp7u2MPW%2Fy5wKfAQ%2BX1s2HqQn%2F3t8728jewpsD%2Fz9vDD1r9KskWD8z8mx0rXRrUOVvgZegB0q%2FGsV8WjwhlkimY26j1zXpqZaLlE7uAjrsrA2DQqFapVGjTRg9xAzCMaYe0iH3Fkil%2F27VSNYxw%2FpV2aq8jBVC4w5ljvqJdCK9xUcUsrnI6WlIzt6h1Oxz%2B6b7BEQ8ofSh4ZpL5XizEOBCIewpmfgA6h%2B4KpKHgb%2Bp2Up5fAQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/0zgo4ysj/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KjsCnUqBsjb5jQ%2BCPq0XmXuamMJA8mnI%2FUsm4CCzoSMjz8EV3wtWEeATS4p9gFOLxU%2FJuin%2F%2BDkDoPRibcKmFSX5htbrSphUbY%2BW%2BGp7u2MPW%2Fy5wKfAQ%2BX1s2HqQn%2F3t8728jewpsD%2Fz9vDD1r9KskWD8z8mx0rXRrUOVvgZegB0q%2FGsV8WjwhlkimY26j1zXpqZaLlE7uAjrsrA2DQqFapVGjTRg9xAzCMaYe0iH3Fkil%2F27VSNYxw%2FpV2aq8jBVC4w5ljvqJdCK9xUcUsrnI6WlIzt6h1Oxz%2B6b7BEQ8ofSh4ZpL5XizEOBCIewpmfgA6h%2B4KpKHgb%2Bp2Up5fAQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde183c04c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:13:39,934 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15622'}
2024-01-26 17:13:39,934 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:13:43,206 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:46,687 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:13:46,689 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:13:46,689 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:13:47,519 DEBUG   SenderThread:3042420 [sender.py:send():382] send: stats
2024-01-26 17:13:48,548 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:53,549 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:58,550 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:01,687 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:14:01,689 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:14:01,690 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:14:03,998 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:08,998 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:13,999 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:16,687 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:14:16,689 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:14:16,689 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:14:17,522 DEBUG   SenderThread:3042420 [sender.py:send():382] send: stats
2024-01-26 17:14:19,523 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:24,524 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:29,525 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:31,687 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:14:31,689 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:14:31,689 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:14:35,054 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:40,055 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:45,181 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:46,762 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:14:46,762 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:14:46,762 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:14:47,524 DEBUG   SenderThread:3042420 [sender.py:send():382] send: stats
2024-01-26 17:14:50,542 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:55,545 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:00,580 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:01,687 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:15:01,689 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:15:01,690 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:15:05,990 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:10,990 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:15,991 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:16,687 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:15:16,689 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:15:16,690 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:15:17,526 DEBUG   SenderThread:3042420 [sender.py:send():382] send: stats
2024-01-26 17:15:20,234 DEBUG   SenderThread:3042420 [sender.py:send():382] send: exit
2024-01-26 17:15:20,234 INFO    SenderThread:3042420 [sender.py:send_exit():589] handling exit code: 1
2024-01-26 17:15:20,235 INFO    SenderThread:3042420 [sender.py:send_exit():591] handling runtime: 392
2024-01-26 17:15:20,235 INFO    SenderThread:3042420 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-01-26 17:15:20,235 INFO    SenderThread:3042420 [sender.py:send_exit():597] send defer
2024-01-26 17:15:20,236 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:20,236 INFO    HandlerThread:3042420 [handler.py:handle_request_defer():172] handle defer: 0
2024-01-26 17:15:20,236 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:20,236 INFO    SenderThread:3042420 [sender.py:send_request_defer():613] handle sender defer: 0
2024-01-26 17:15:20,236 INFO    SenderThread:3042420 [sender.py:transition_state():617] send defer: 1
2024-01-26 17:15:20,236 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:20,236 INFO    HandlerThread:3042420 [handler.py:handle_request_defer():172] handle defer: 1
2024-01-26 17:15:20,236 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:20,236 INFO    SenderThread:3042420 [sender.py:send_request_defer():613] handle sender defer: 1
2024-01-26 17:15:20,236 INFO    SenderThread:3042420 [sender.py:transition_state():617] send defer: 2
2024-01-26 17:15:20,236 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:20,236 INFO    HandlerThread:3042420 [handler.py:handle_request_defer():172] handle defer: 2
2024-01-26 17:15:20,236 INFO    HandlerThread:3042420 [system_monitor.py:finish():203] Stopping system monitor
2024-01-26 17:15:20,237 DEBUG   SystemMonitor:3042420 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-01-26 17:15:20,237 DEBUG   SystemMonitor:3042420 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-01-26 17:15:20,239 INFO    HandlerThread:3042420 [interfaces.py:finish():202] Joined cpu monitor
2024-01-26 17:15:20,239 INFO    HandlerThread:3042420 [interfaces.py:finish():202] Joined disk monitor
2024-01-26 17:15:20,948 INFO    Thread-12 :3042420 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/files/wandb-summary.json
2024-01-26 17:15:21,962 INFO    Thread-12 :3042420 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/files/output.log
2024-01-26 17:15:33,972 INFO    HandlerThread:3042420 [interfaces.py:finish():202] Joined gpu monitor
2024-01-26 17:15:33,973 INFO    HandlerThread:3042420 [interfaces.py:finish():202] Joined memory monitor
2024-01-26 17:15:33,973 INFO    HandlerThread:3042420 [interfaces.py:finish():202] Joined network monitor
2024-01-26 17:15:33,973 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:15:33,973 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:33,973 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:33,973 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:33,973 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:33,973 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:33,974 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:33,975 INFO    SenderThread:3042420 [sender.py:send_request_defer():613] handle sender defer: 2
2024-01-26 17:15:33,975 INFO    SenderThread:3042420 [sender.py:transition_state():617] send defer: 3
2024-01-26 17:15:33,975 DEBUG   SenderThread:3042420 [sender.py:send():382] send: stats
2024-01-26 17:15:33,976 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:15:33,976 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:33,976 INFO    HandlerThread:3042420 [handler.py:handle_request_defer():172] handle defer: 3
2024-01-26 17:15:33,976 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:33,976 INFO    SenderThread:3042420 [sender.py:send_request_defer():613] handle sender defer: 3
2024-01-26 17:15:33,976 INFO    SenderThread:3042420 [sender.py:transition_state():617] send defer: 4
2024-01-26 17:15:33,977 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:33,977 INFO    HandlerThread:3042420 [handler.py:handle_request_defer():172] handle defer: 4
2024-01-26 17:15:33,977 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:33,977 INFO    SenderThread:3042420 [sender.py:send_request_defer():613] handle sender defer: 4
2024-01-26 17:15:33,977 INFO    SenderThread:3042420 [sender.py:transition_state():617] send defer: 5
2024-01-26 17:15:33,977 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:33,977 INFO    HandlerThread:3042420 [handler.py:handle_request_defer():172] handle defer: 5
2024-01-26 17:15:33,977 DEBUG   SenderThread:3042420 [sender.py:send():382] send: summary
2024-01-26 17:15:33,978 INFO    SenderThread:3042420 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-01-26 17:15:33,978 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:33,978 INFO    SenderThread:3042420 [sender.py:send_request_defer():613] handle sender defer: 5
2024-01-26 17:15:33,978 INFO    SenderThread:3042420 [sender.py:transition_state():617] send defer: 6
2024-01-26 17:15:33,978 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:33,978 INFO    HandlerThread:3042420 [handler.py:handle_request_defer():172] handle defer: 6
2024-01-26 17:15:33,978 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:33,978 INFO    SenderThread:3042420 [sender.py:send_request_defer():613] handle sender defer: 6
2024-01-26 17:15:33,978 INFO    SenderThread:3042420 [sender.py:transition_state():617] send defer: 7
2024-01-26 17:15:33,979 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:33,979 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:33,979 INFO    HandlerThread:3042420 [handler.py:handle_request_defer():172] handle defer: 7
2024-01-26 17:15:33,979 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:33,979 INFO    SenderThread:3042420 [sender.py:send_request_defer():613] handle sender defer: 7
2024-01-26 17:15:33,994 INFO    Thread-12 :3042420 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/files/wandb-summary.json
2024-01-26 17:15:34,294 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:15:35,199 INFO    SenderThread:3042420 [sender.py:transition_state():617] send defer: 8
2024-01-26 17:15:35,199 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:15:35,200 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:35,200 INFO    HandlerThread:3042420 [handler.py:handle_request_defer():172] handle defer: 8
2024-01-26 17:15:35,200 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:35,200 INFO    SenderThread:3042420 [sender.py:send_request_defer():613] handle sender defer: 8
2024-01-26 17:15:35,200 INFO    SenderThread:3042420 [job_builder.py:build():296] Attempting to build job artifact
2024-01-26 17:15:35,201 INFO    SenderThread:3042420 [job_builder.py:_get_source_type():426] is repo sourced job
2024-01-26 17:15:35,296 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:15:35,390 INFO    SenderThread:3042420 [job_builder.py:build():402] adding wandb-job metadata file
2024-01-26 17:15:35,393 INFO    SenderThread:3042420 [sender.py:transition_state():617] send defer: 9
2024-01-26 17:15:35,393 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:15:35,393 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:35,393 INFO    HandlerThread:3042420 [handler.py:handle_request_defer():172] handle defer: 9
2024-01-26 17:15:35,394 DEBUG   SenderThread:3042420 [sender.py:send():382] send: artifact
2024-01-26 17:15:35,996 INFO    Thread-12 :3042420 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/files/output.log
2024-01-26 17:15:36,296 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:15:37,217 ERROR   wandb-upload_1:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789632/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BpLfb4ffrf0SBdVT2CqYq790J4I8zytm6vNyXp%2FZ8tO%2FFFHdwU9tjGrjr4xrTrUyZbKmPPr8w1Ctr448LR6yElA9xcGflkDxxOj6fGuY%2FBu%2BtSNhbeCv66VnXhAJSK%2B4m0Q7%2FRLlwFlk5qk50Usu7i1gp9giW1KooaBWPxrr9hNyE5qnXGcyNmu3sZJDhymZtx1s00%2F%2FBpXzFI03tbJ6wPBM0Y%2FvARaokmdNcUQzTuZCXzD15MEhmooNe9FtgbsaCvixRN94AIqPcd%2BWlT1mIVsDpZ6LOuHYnKzHJ9aJ0LwpwYa24B7BUIL5UireH3CX%2BcRIXjLjDlDj4F7SggZiA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789632/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BpLfb4ffrf0SBdVT2CqYq790J4I8zytm6vNyXp%2FZ8tO%2FFFHdwU9tjGrjr4xrTrUyZbKmPPr8w1Ctr448LR6yElA9xcGflkDxxOj6fGuY%2FBu%2BtSNhbeCv66VnXhAJSK%2B4m0Q7%2FRLlwFlk5qk50Usu7i1gp9giW1KooaBWPxrr9hNyE5qnXGcyNmu3sZJDhymZtx1s00%2F%2FBpXzFI03tbJ6wPBM0Y%2FvARaokmdNcUQzTuZCXzD15MEhmooNe9FtgbsaCvixRN94AIqPcd%2BWlT1mIVsDpZ6LOuHYnKzHJ9aJ0LwpwYa24B7BUIL5UireH3CX%2BcRIXjLjDlDj4F7SggZiA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde18562a00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:37,217 ERROR   wandb-upload_1:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:37,217 ERROR   wandb-upload_1:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:37,217 ERROR   wandb-upload_2:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789632/6873c23a2381d1524249eb1a948a45a5?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=m4WpBBgNwyDD0O2xopN8%2FwrrO%2B7395HW%2BApN3MDhgVgSJFGu7nvhQMlm6hLGXxP8usY7iOX3NAg6xxoU1dUU68zAJXNvi0X3Td5UO4qW2WjmNqXHFPurfzpdLeg4qVS4kDd81hLQZycfDX5MG5181NpUXjyUHuYuP88eBj9Ibq6rexzLy4wCFdjVRUEAmQZo04e4lTu0OlFg6qfkWv6E1YB91r9s9SPM9FsUfXc6EdXpfsGZdhHSA31lIWTlHerS5p5s0zeLxMRtkJ6hSnOmuSLdHDv4JBqe5qagxhQNvMHRi8xCYYvzv7H1x3kfussTbtC%2BTFy6OLMs72FhzDGQPA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789632/6873c23a2381d1524249eb1a948a45a5?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=m4WpBBgNwyDD0O2xopN8%2FwrrO%2B7395HW%2BApN3MDhgVgSJFGu7nvhQMlm6hLGXxP8usY7iOX3NAg6xxoU1dUU68zAJXNvi0X3Td5UO4qW2WjmNqXHFPurfzpdLeg4qVS4kDd81hLQZycfDX5MG5181NpUXjyUHuYuP88eBj9Ibq6rexzLy4wCFdjVRUEAmQZo04e4lTu0OlFg6qfkWv6E1YB91r9s9SPM9FsUfXc6EdXpfsGZdhHSA31lIWTlHerS5p5s0zeLxMRtkJ6hSnOmuSLdHDv4JBqe5qagxhQNvMHRi8xCYYvzv7H1x3kfussTbtC%2BTFy6OLMs72FhzDGQPA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde18391b50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:37,217 ERROR   wandb-upload_2:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:37,217 ERROR   wandb-upload_2:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:38,378 ERROR   wandb-upload_2:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789632/6873c23a2381d1524249eb1a948a45a5?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=m4WpBBgNwyDD0O2xopN8%2FwrrO%2B7395HW%2BApN3MDhgVgSJFGu7nvhQMlm6hLGXxP8usY7iOX3NAg6xxoU1dUU68zAJXNvi0X3Td5UO4qW2WjmNqXHFPurfzpdLeg4qVS4kDd81hLQZycfDX5MG5181NpUXjyUHuYuP88eBj9Ibq6rexzLy4wCFdjVRUEAmQZo04e4lTu0OlFg6qfkWv6E1YB91r9s9SPM9FsUfXc6EdXpfsGZdhHSA31lIWTlHerS5p5s0zeLxMRtkJ6hSnOmuSLdHDv4JBqe5qagxhQNvMHRi8xCYYvzv7H1x3kfussTbtC%2BTFy6OLMs72FhzDGQPA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789632/6873c23a2381d1524249eb1a948a45a5?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=m4WpBBgNwyDD0O2xopN8%2FwrrO%2B7395HW%2BApN3MDhgVgSJFGu7nvhQMlm6hLGXxP8usY7iOX3NAg6xxoU1dUU68zAJXNvi0X3Td5UO4qW2WjmNqXHFPurfzpdLeg4qVS4kDd81hLQZycfDX5MG5181NpUXjyUHuYuP88eBj9Ibq6rexzLy4wCFdjVRUEAmQZo04e4lTu0OlFg6qfkWv6E1YB91r9s9SPM9FsUfXc6EdXpfsGZdhHSA31lIWTlHerS5p5s0zeLxMRtkJ6hSnOmuSLdHDv4JBqe5qagxhQNvMHRi8xCYYvzv7H1x3kfussTbtC%2BTFy6OLMs72FhzDGQPA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde185996a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:38,378 ERROR   wandb-upload_2:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:38,378 ERROR   wandb-upload_2:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:38,405 ERROR   wandb-upload_1:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789632/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BpLfb4ffrf0SBdVT2CqYq790J4I8zytm6vNyXp%2FZ8tO%2FFFHdwU9tjGrjr4xrTrUyZbKmPPr8w1Ctr448LR6yElA9xcGflkDxxOj6fGuY%2FBu%2BtSNhbeCv66VnXhAJSK%2B4m0Q7%2FRLlwFlk5qk50Usu7i1gp9giW1KooaBWPxrr9hNyE5qnXGcyNmu3sZJDhymZtx1s00%2F%2FBpXzFI03tbJ6wPBM0Y%2FvARaokmdNcUQzTuZCXzD15MEhmooNe9FtgbsaCvixRN94AIqPcd%2BWlT1mIVsDpZ6LOuHYnKzHJ9aJ0LwpwYa24B7BUIL5UireH3CX%2BcRIXjLjDlDj4F7SggZiA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789632/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BpLfb4ffrf0SBdVT2CqYq790J4I8zytm6vNyXp%2FZ8tO%2FFFHdwU9tjGrjr4xrTrUyZbKmPPr8w1Ctr448LR6yElA9xcGflkDxxOj6fGuY%2FBu%2BtSNhbeCv66VnXhAJSK%2B4m0Q7%2FRLlwFlk5qk50Usu7i1gp9giW1KooaBWPxrr9hNyE5qnXGcyNmu3sZJDhymZtx1s00%2F%2FBpXzFI03tbJ6wPBM0Y%2FvARaokmdNcUQzTuZCXzD15MEhmooNe9FtgbsaCvixRN94AIqPcd%2BWlT1mIVsDpZ6LOuHYnKzHJ9aJ0LwpwYa24B7BUIL5UireH3CX%2BcRIXjLjDlDj4F7SggZiA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde183ae0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:38,405 ERROR   wandb-upload_1:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:38,405 ERROR   wandb-upload_1:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:38,405 INFO    wandb-upload_1:3042420 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fde183ae0d0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789632/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BpLfb4ffrf0SBdVT2CqYq790J4I8zytm6vNyXp%2FZ8tO%2FFFHdwU9tjGrjr4xrTrUyZbKmPPr8w1Ctr448LR6yElA9xcGflkDxxOj6fGuY%2FBu%2BtSNhbeCv66VnXhAJSK%2B4m0Q7%2FRLlwFlk5qk50Usu7i1gp9giW1KooaBWPxrr9hNyE5qnXGcyNmu3sZJDhymZtx1s00%2F%2FBpXzFI03tbJ6wPBM0Y%2FvARaokmdNcUQzTuZCXzD15MEhmooNe9FtgbsaCvixRN94AIqPcd%2BWlT1mIVsDpZ6LOuHYnKzHJ9aJ0LwpwYa24B7BUIL5UireH3CX%2BcRIXjLjDlDj4F7SggZiA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde183ae0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789632/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BpLfb4ffrf0SBdVT2CqYq790J4I8zytm6vNyXp%2FZ8tO%2FFFHdwU9tjGrjr4xrTrUyZbKmPPr8w1Ctr448LR6yElA9xcGflkDxxOj6fGuY%2FBu%2BtSNhbeCv66VnXhAJSK%2B4m0Q7%2FRLlwFlk5qk50Usu7i1gp9giW1KooaBWPxrr9hNyE5qnXGcyNmu3sZJDhymZtx1s00%2F%2FBpXzFI03tbJ6wPBM0Y%2FvARaokmdNcUQzTuZCXzD15MEhmooNe9FtgbsaCvixRN94AIqPcd%2BWlT1mIVsDpZ6LOuHYnKzHJ9aJ0LwpwYa24B7BUIL5UireH3CX%2BcRIXjLjDlDj4F7SggZiA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde183ae0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2789, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-01-26 17:15:40,623 ERROR   wandb-upload_2:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789632/6873c23a2381d1524249eb1a948a45a5?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=m4WpBBgNwyDD0O2xopN8%2FwrrO%2B7395HW%2BApN3MDhgVgSJFGu7nvhQMlm6hLGXxP8usY7iOX3NAg6xxoU1dUU68zAJXNvi0X3Td5UO4qW2WjmNqXHFPurfzpdLeg4qVS4kDd81hLQZycfDX5MG5181NpUXjyUHuYuP88eBj9Ibq6rexzLy4wCFdjVRUEAmQZo04e4lTu0OlFg6qfkWv6E1YB91r9s9SPM9FsUfXc6EdXpfsGZdhHSA31lIWTlHerS5p5s0zeLxMRtkJ6hSnOmuSLdHDv4JBqe5qagxhQNvMHRi8xCYYvzv7H1x3kfussTbtC%2BTFy6OLMs72FhzDGQPA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789632/6873c23a2381d1524249eb1a948a45a5?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=m4WpBBgNwyDD0O2xopN8%2FwrrO%2B7395HW%2BApN3MDhgVgSJFGu7nvhQMlm6hLGXxP8usY7iOX3NAg6xxoU1dUU68zAJXNvi0X3Td5UO4qW2WjmNqXHFPurfzpdLeg4qVS4kDd81hLQZycfDX5MG5181NpUXjyUHuYuP88eBj9Ibq6rexzLy4wCFdjVRUEAmQZo04e4lTu0OlFg6qfkWv6E1YB91r9s9SPM9FsUfXc6EdXpfsGZdhHSA31lIWTlHerS5p5s0zeLxMRtkJ6hSnOmuSLdHDv4JBqe5qagxhQNvMHRi8xCYYvzv7H1x3kfussTbtC%2BTFy6OLMs72FhzDGQPA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde183ae580>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:40,623 ERROR   wandb-upload_2:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:40,623 ERROR   wandb-upload_2:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:40,749 ERROR   wandb-upload_1:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789632/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BpLfb4ffrf0SBdVT2CqYq790J4I8zytm6vNyXp%2FZ8tO%2FFFHdwU9tjGrjr4xrTrUyZbKmPPr8w1Ctr448LR6yElA9xcGflkDxxOj6fGuY%2FBu%2BtSNhbeCv66VnXhAJSK%2B4m0Q7%2FRLlwFlk5qk50Usu7i1gp9giW1KooaBWPxrr9hNyE5qnXGcyNmu3sZJDhymZtx1s00%2F%2FBpXzFI03tbJ6wPBM0Y%2FvARaokmdNcUQzTuZCXzD15MEhmooNe9FtgbsaCvixRN94AIqPcd%2BWlT1mIVsDpZ6LOuHYnKzHJ9aJ0LwpwYa24B7BUIL5UireH3CX%2BcRIXjLjDlDj4F7SggZiA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789632/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BpLfb4ffrf0SBdVT2CqYq790J4I8zytm6vNyXp%2FZ8tO%2FFFHdwU9tjGrjr4xrTrUyZbKmPPr8w1Ctr448LR6yElA9xcGflkDxxOj6fGuY%2FBu%2BtSNhbeCv66VnXhAJSK%2B4m0Q7%2FRLlwFlk5qk50Usu7i1gp9giW1KooaBWPxrr9hNyE5qnXGcyNmu3sZJDhymZtx1s00%2F%2FBpXzFI03tbJ6wPBM0Y%2FvARaokmdNcUQzTuZCXzD15MEhmooNe9FtgbsaCvixRN94AIqPcd%2BWlT1mIVsDpZ6LOuHYnKzHJ9aJ0LwpwYa24B7BUIL5UireH3CX%2BcRIXjLjDlDj4F7SggZiA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde18391490>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:40,749 ERROR   wandb-upload_1:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:40,749 ERROR   wandb-upload_1:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:41,298 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:44,973 ERROR   wandb-upload_2:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789632/6873c23a2381d1524249eb1a948a45a5?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=m4WpBBgNwyDD0O2xopN8%2FwrrO%2B7395HW%2BApN3MDhgVgSJFGu7nvhQMlm6hLGXxP8usY7iOX3NAg6xxoU1dUU68zAJXNvi0X3Td5UO4qW2WjmNqXHFPurfzpdLeg4qVS4kDd81hLQZycfDX5MG5181NpUXjyUHuYuP88eBj9Ibq6rexzLy4wCFdjVRUEAmQZo04e4lTu0OlFg6qfkWv6E1YB91r9s9SPM9FsUfXc6EdXpfsGZdhHSA31lIWTlHerS5p5s0zeLxMRtkJ6hSnOmuSLdHDv4JBqe5qagxhQNvMHRi8xCYYvzv7H1x3kfussTbtC%2BTFy6OLMs72FhzDGQPA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789632/6873c23a2381d1524249eb1a948a45a5?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=m4WpBBgNwyDD0O2xopN8%2FwrrO%2B7395HW%2BApN3MDhgVgSJFGu7nvhQMlm6hLGXxP8usY7iOX3NAg6xxoU1dUU68zAJXNvi0X3Td5UO4qW2WjmNqXHFPurfzpdLeg4qVS4kDd81hLQZycfDX5MG5181NpUXjyUHuYuP88eBj9Ibq6rexzLy4wCFdjVRUEAmQZo04e4lTu0OlFg6qfkWv6E1YB91r9s9SPM9FsUfXc6EdXpfsGZdhHSA31lIWTlHerS5p5s0zeLxMRtkJ6hSnOmuSLdHDv4JBqe5qagxhQNvMHRi8xCYYvzv7H1x3kfussTbtC%2BTFy6OLMs72FhzDGQPA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde18391d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:44,973 ERROR   wandb-upload_2:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:44,973 ERROR   wandb-upload_2:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:45,577 ERROR   wandb-upload_1:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789632/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BpLfb4ffrf0SBdVT2CqYq790J4I8zytm6vNyXp%2FZ8tO%2FFFHdwU9tjGrjr4xrTrUyZbKmPPr8w1Ctr448LR6yElA9xcGflkDxxOj6fGuY%2FBu%2BtSNhbeCv66VnXhAJSK%2B4m0Q7%2FRLlwFlk5qk50Usu7i1gp9giW1KooaBWPxrr9hNyE5qnXGcyNmu3sZJDhymZtx1s00%2F%2FBpXzFI03tbJ6wPBM0Y%2FvARaokmdNcUQzTuZCXzD15MEhmooNe9FtgbsaCvixRN94AIqPcd%2BWlT1mIVsDpZ6LOuHYnKzHJ9aJ0LwpwYa24B7BUIL5UireH3CX%2BcRIXjLjDlDj4F7SggZiA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789632/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BpLfb4ffrf0SBdVT2CqYq790J4I8zytm6vNyXp%2FZ8tO%2FFFHdwU9tjGrjr4xrTrUyZbKmPPr8w1Ctr448LR6yElA9xcGflkDxxOj6fGuY%2FBu%2BtSNhbeCv66VnXhAJSK%2B4m0Q7%2FRLlwFlk5qk50Usu7i1gp9giW1KooaBWPxrr9hNyE5qnXGcyNmu3sZJDhymZtx1s00%2F%2FBpXzFI03tbJ6wPBM0Y%2FvARaokmdNcUQzTuZCXzD15MEhmooNe9FtgbsaCvixRN94AIqPcd%2BWlT1mIVsDpZ6LOuHYnKzHJ9aJ0LwpwYa24B7BUIL5UireH3CX%2BcRIXjLjDlDj4F7SggZiA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde18391cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:45,577 ERROR   wandb-upload_1:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:45,577 ERROR   wandb-upload_1:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:46,300 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:51,302 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:53,838 ERROR   wandb-upload_2:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789632/6873c23a2381d1524249eb1a948a45a5?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=m4WpBBgNwyDD0O2xopN8%2FwrrO%2B7395HW%2BApN3MDhgVgSJFGu7nvhQMlm6hLGXxP8usY7iOX3NAg6xxoU1dUU68zAJXNvi0X3Td5UO4qW2WjmNqXHFPurfzpdLeg4qVS4kDd81hLQZycfDX5MG5181NpUXjyUHuYuP88eBj9Ibq6rexzLy4wCFdjVRUEAmQZo04e4lTu0OlFg6qfkWv6E1YB91r9s9SPM9FsUfXc6EdXpfsGZdhHSA31lIWTlHerS5p5s0zeLxMRtkJ6hSnOmuSLdHDv4JBqe5qagxhQNvMHRi8xCYYvzv7H1x3kfussTbtC%2BTFy6OLMs72FhzDGQPA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789632/6873c23a2381d1524249eb1a948a45a5?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=m4WpBBgNwyDD0O2xopN8%2FwrrO%2B7395HW%2BApN3MDhgVgSJFGu7nvhQMlm6hLGXxP8usY7iOX3NAg6xxoU1dUU68zAJXNvi0X3Td5UO4qW2WjmNqXHFPurfzpdLeg4qVS4kDd81hLQZycfDX5MG5181NpUXjyUHuYuP88eBj9Ibq6rexzLy4wCFdjVRUEAmQZo04e4lTu0OlFg6qfkWv6E1YB91r9s9SPM9FsUfXc6EdXpfsGZdhHSA31lIWTlHerS5p5s0zeLxMRtkJ6hSnOmuSLdHDv4JBqe5qagxhQNvMHRi8xCYYvzv7H1x3kfussTbtC%2BTFy6OLMs72FhzDGQPA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde183ae640>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:53,838 ERROR   wandb-upload_2:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:53,838 ERROR   wandb-upload_2:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:54,616 ERROR   wandb-upload_1:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789632/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BpLfb4ffrf0SBdVT2CqYq790J4I8zytm6vNyXp%2FZ8tO%2FFFHdwU9tjGrjr4xrTrUyZbKmPPr8w1Ctr448LR6yElA9xcGflkDxxOj6fGuY%2FBu%2BtSNhbeCv66VnXhAJSK%2B4m0Q7%2FRLlwFlk5qk50Usu7i1gp9giW1KooaBWPxrr9hNyE5qnXGcyNmu3sZJDhymZtx1s00%2F%2FBpXzFI03tbJ6wPBM0Y%2FvARaokmdNcUQzTuZCXzD15MEhmooNe9FtgbsaCvixRN94AIqPcd%2BWlT1mIVsDpZ6LOuHYnKzHJ9aJ0LwpwYa24B7BUIL5UireH3CX%2BcRIXjLjDlDj4F7SggZiA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789632/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BpLfb4ffrf0SBdVT2CqYq790J4I8zytm6vNyXp%2FZ8tO%2FFFHdwU9tjGrjr4xrTrUyZbKmPPr8w1Ctr448LR6yElA9xcGflkDxxOj6fGuY%2FBu%2BtSNhbeCv66VnXhAJSK%2B4m0Q7%2FRLlwFlk5qk50Usu7i1gp9giW1KooaBWPxrr9hNyE5qnXGcyNmu3sZJDhymZtx1s00%2F%2FBpXzFI03tbJ6wPBM0Y%2FvARaokmdNcUQzTuZCXzD15MEhmooNe9FtgbsaCvixRN94AIqPcd%2BWlT1mIVsDpZ6LOuHYnKzHJ9aJ0LwpwYa24B7BUIL5UireH3CX%2BcRIXjLjDlDj4F7SggZiA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde183ae790>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:54,616 ERROR   wandb-upload_1:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:54,616 ERROR   wandb-upload_1:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:56,305 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:01,307 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:06,309 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:11,309 ERROR   wandb-upload_2:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789632/6873c23a2381d1524249eb1a948a45a5?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=m4WpBBgNwyDD0O2xopN8%2FwrrO%2B7395HW%2BApN3MDhgVgSJFGu7nvhQMlm6hLGXxP8usY7iOX3NAg6xxoU1dUU68zAJXNvi0X3Td5UO4qW2WjmNqXHFPurfzpdLeg4qVS4kDd81hLQZycfDX5MG5181NpUXjyUHuYuP88eBj9Ibq6rexzLy4wCFdjVRUEAmQZo04e4lTu0OlFg6qfkWv6E1YB91r9s9SPM9FsUfXc6EdXpfsGZdhHSA31lIWTlHerS5p5s0zeLxMRtkJ6hSnOmuSLdHDv4JBqe5qagxhQNvMHRi8xCYYvzv7H1x3kfussTbtC%2BTFy6OLMs72FhzDGQPA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789632/6873c23a2381d1524249eb1a948a45a5?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=m4WpBBgNwyDD0O2xopN8%2FwrrO%2B7395HW%2BApN3MDhgVgSJFGu7nvhQMlm6hLGXxP8usY7iOX3NAg6xxoU1dUU68zAJXNvi0X3Td5UO4qW2WjmNqXHFPurfzpdLeg4qVS4kDd81hLQZycfDX5MG5181NpUXjyUHuYuP88eBj9Ibq6rexzLy4wCFdjVRUEAmQZo04e4lTu0OlFg6qfkWv6E1YB91r9s9SPM9FsUfXc6EdXpfsGZdhHSA31lIWTlHerS5p5s0zeLxMRtkJ6hSnOmuSLdHDv4JBqe5qagxhQNvMHRi8xCYYvzv7H1x3kfussTbtC%2BTFy6OLMs72FhzDGQPA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde18387340>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:16:11,309 ERROR   wandb-upload_2:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:16:11,309 ERROR   wandb-upload_2:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:11,311 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:14,592 ERROR   wandb-upload_1:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789632/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BpLfb4ffrf0SBdVT2CqYq790J4I8zytm6vNyXp%2FZ8tO%2FFFHdwU9tjGrjr4xrTrUyZbKmPPr8w1Ctr448LR6yElA9xcGflkDxxOj6fGuY%2FBu%2BtSNhbeCv66VnXhAJSK%2B4m0Q7%2FRLlwFlk5qk50Usu7i1gp9giW1KooaBWPxrr9hNyE5qnXGcyNmu3sZJDhymZtx1s00%2F%2FBpXzFI03tbJ6wPBM0Y%2FvARaokmdNcUQzTuZCXzD15MEhmooNe9FtgbsaCvixRN94AIqPcd%2BWlT1mIVsDpZ6LOuHYnKzHJ9aJ0LwpwYa24B7BUIL5UireH3CX%2BcRIXjLjDlDj4F7SggZiA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789632/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BpLfb4ffrf0SBdVT2CqYq790J4I8zytm6vNyXp%2FZ8tO%2FFFHdwU9tjGrjr4xrTrUyZbKmPPr8w1Ctr448LR6yElA9xcGflkDxxOj6fGuY%2FBu%2BtSNhbeCv66VnXhAJSK%2B4m0Q7%2FRLlwFlk5qk50Usu7i1gp9giW1KooaBWPxrr9hNyE5qnXGcyNmu3sZJDhymZtx1s00%2F%2FBpXzFI03tbJ6wPBM0Y%2FvARaokmdNcUQzTuZCXzD15MEhmooNe9FtgbsaCvixRN94AIqPcd%2BWlT1mIVsDpZ6LOuHYnKzHJ9aJ0LwpwYa24B7BUIL5UireH3CX%2BcRIXjLjDlDj4F7SggZiA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde18387100>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:16:14,592 ERROR   wandb-upload_1:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:16:14,592 ERROR   wandb-upload_1:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:16,314 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:21,316 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:26,318 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:31,321 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:36,323 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:41,326 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:43,681 ERROR   wandb-upload_2:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789632/6873c23a2381d1524249eb1a948a45a5?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=m4WpBBgNwyDD0O2xopN8%2FwrrO%2B7395HW%2BApN3MDhgVgSJFGu7nvhQMlm6hLGXxP8usY7iOX3NAg6xxoU1dUU68zAJXNvi0X3Td5UO4qW2WjmNqXHFPurfzpdLeg4qVS4kDd81hLQZycfDX5MG5181NpUXjyUHuYuP88eBj9Ibq6rexzLy4wCFdjVRUEAmQZo04e4lTu0OlFg6qfkWv6E1YB91r9s9SPM9FsUfXc6EdXpfsGZdhHSA31lIWTlHerS5p5s0zeLxMRtkJ6hSnOmuSLdHDv4JBqe5qagxhQNvMHRi8xCYYvzv7H1x3kfussTbtC%2BTFy6OLMs72FhzDGQPA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789632/6873c23a2381d1524249eb1a948a45a5?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=m4WpBBgNwyDD0O2xopN8%2FwrrO%2B7395HW%2BApN3MDhgVgSJFGu7nvhQMlm6hLGXxP8usY7iOX3NAg6xxoU1dUU68zAJXNvi0X3Td5UO4qW2WjmNqXHFPurfzpdLeg4qVS4kDd81hLQZycfDX5MG5181NpUXjyUHuYuP88eBj9Ibq6rexzLy4wCFdjVRUEAmQZo04e4lTu0OlFg6qfkWv6E1YB91r9s9SPM9FsUfXc6EdXpfsGZdhHSA31lIWTlHerS5p5s0zeLxMRtkJ6hSnOmuSLdHDv4JBqe5qagxhQNvMHRi8xCYYvzv7H1x3kfussTbtC%2BTFy6OLMs72FhzDGQPA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde183a8bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:16:43,681 ERROR   wandb-upload_2:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:16:43,681 ERROR   wandb-upload_2:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:46,328 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:48,577 ERROR   wandb-upload_1:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789632/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BpLfb4ffrf0SBdVT2CqYq790J4I8zytm6vNyXp%2FZ8tO%2FFFHdwU9tjGrjr4xrTrUyZbKmPPr8w1Ctr448LR6yElA9xcGflkDxxOj6fGuY%2FBu%2BtSNhbeCv66VnXhAJSK%2B4m0Q7%2FRLlwFlk5qk50Usu7i1gp9giW1KooaBWPxrr9hNyE5qnXGcyNmu3sZJDhymZtx1s00%2F%2FBpXzFI03tbJ6wPBM0Y%2FvARaokmdNcUQzTuZCXzD15MEhmooNe9FtgbsaCvixRN94AIqPcd%2BWlT1mIVsDpZ6LOuHYnKzHJ9aJ0LwpwYa24B7BUIL5UireH3CX%2BcRIXjLjDlDj4F7SggZiA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789632/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BpLfb4ffrf0SBdVT2CqYq790J4I8zytm6vNyXp%2FZ8tO%2FFFHdwU9tjGrjr4xrTrUyZbKmPPr8w1Ctr448LR6yElA9xcGflkDxxOj6fGuY%2FBu%2BtSNhbeCv66VnXhAJSK%2B4m0Q7%2FRLlwFlk5qk50Usu7i1gp9giW1KooaBWPxrr9hNyE5qnXGcyNmu3sZJDhymZtx1s00%2F%2FBpXzFI03tbJ6wPBM0Y%2FvARaokmdNcUQzTuZCXzD15MEhmooNe9FtgbsaCvixRN94AIqPcd%2BWlT1mIVsDpZ6LOuHYnKzHJ9aJ0LwpwYa24B7BUIL5UireH3CX%2BcRIXjLjDlDj4F7SggZiA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde18562c70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:16:48,577 ERROR   wandb-upload_1:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:16:48,577 ERROR   wandb-upload_1:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:51,330 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:56,332 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:01,334 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:06,341 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:11,340 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:16,342 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:21,345 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:26,347 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:31,350 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:36,354 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:41,356 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:46,358 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:48,448 ERROR   wandb-upload_2:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789632/6873c23a2381d1524249eb1a948a45a5?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=m4WpBBgNwyDD0O2xopN8%2FwrrO%2B7395HW%2BApN3MDhgVgSJFGu7nvhQMlm6hLGXxP8usY7iOX3NAg6xxoU1dUU68zAJXNvi0X3Td5UO4qW2WjmNqXHFPurfzpdLeg4qVS4kDd81hLQZycfDX5MG5181NpUXjyUHuYuP88eBj9Ibq6rexzLy4wCFdjVRUEAmQZo04e4lTu0OlFg6qfkWv6E1YB91r9s9SPM9FsUfXc6EdXpfsGZdhHSA31lIWTlHerS5p5s0zeLxMRtkJ6hSnOmuSLdHDv4JBqe5qagxhQNvMHRi8xCYYvzv7H1x3kfussTbtC%2BTFy6OLMs72FhzDGQPA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789632/6873c23a2381d1524249eb1a948a45a5?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=m4WpBBgNwyDD0O2xopN8%2FwrrO%2B7395HW%2BApN3MDhgVgSJFGu7nvhQMlm6hLGXxP8usY7iOX3NAg6xxoU1dUU68zAJXNvi0X3Td5UO4qW2WjmNqXHFPurfzpdLeg4qVS4kDd81hLQZycfDX5MG5181NpUXjyUHuYuP88eBj9Ibq6rexzLy4wCFdjVRUEAmQZo04e4lTu0OlFg6qfkWv6E1YB91r9s9SPM9FsUfXc6EdXpfsGZdhHSA31lIWTlHerS5p5s0zeLxMRtkJ6hSnOmuSLdHDv4JBqe5qagxhQNvMHRi8xCYYvzv7H1x3kfussTbtC%2BTFy6OLMs72FhzDGQPA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde183a3730>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:17:48,448 ERROR   wandb-upload_2:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:17:48,448 ERROR   wandb-upload_2:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:17:51,360 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:55,327 ERROR   wandb-upload_1:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789632/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BpLfb4ffrf0SBdVT2CqYq790J4I8zytm6vNyXp%2FZ8tO%2FFFHdwU9tjGrjr4xrTrUyZbKmPPr8w1Ctr448LR6yElA9xcGflkDxxOj6fGuY%2FBu%2BtSNhbeCv66VnXhAJSK%2B4m0Q7%2FRLlwFlk5qk50Usu7i1gp9giW1KooaBWPxrr9hNyE5qnXGcyNmu3sZJDhymZtx1s00%2F%2FBpXzFI03tbJ6wPBM0Y%2FvARaokmdNcUQzTuZCXzD15MEhmooNe9FtgbsaCvixRN94AIqPcd%2BWlT1mIVsDpZ6LOuHYnKzHJ9aJ0LwpwYa24B7BUIL5UireH3CX%2BcRIXjLjDlDj4F7SggZiA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789632/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346937&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BpLfb4ffrf0SBdVT2CqYq790J4I8zytm6vNyXp%2FZ8tO%2FFFHdwU9tjGrjr4xrTrUyZbKmPPr8w1Ctr448LR6yElA9xcGflkDxxOj6fGuY%2FBu%2BtSNhbeCv66VnXhAJSK%2B4m0Q7%2FRLlwFlk5qk50Usu7i1gp9giW1KooaBWPxrr9hNyE5qnXGcyNmu3sZJDhymZtx1s00%2F%2FBpXzFI03tbJ6wPBM0Y%2FvARaokmdNcUQzTuZCXzD15MEhmooNe9FtgbsaCvixRN94AIqPcd%2BWlT1mIVsDpZ6LOuHYnKzHJ9aJ0LwpwYa24B7BUIL5UireH3CX%2BcRIXjLjDlDj4F7SggZiA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde183a70a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:17:55,328 ERROR   wandb-upload_1:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:17:55,328 ERROR   wandb-upload_1:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:17:56,362 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:01,364 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:06,366 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:11,369 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:16,371 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:21,373 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:26,331 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/0zgo4ysj/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KjsCnUqBsjb5jQ%2BCPq0XmXuamMJA8mnI%2FUsm4CCzoSMjz8EV3wtWEeATS4p9gFOLxU%2FJuin%2F%2BDkDoPRibcKmFSX5htbrSphUbY%2BW%2BGp7u2MPW%2Fy5wKfAQ%2BX1s2HqQn%2F3t8728jewpsD%2Fz9vDD1r9KskWD8z8mx0rXRrUOVvgZegB0q%2FGsV8WjwhlkimY26j1zXpqZaLlE7uAjrsrA2DQqFapVGjTRg9xAzCMaYe0iH3Fkil%2F27VSNYxw%2FpV2aq8jBVC4w5ljvqJdCK9xUcUsrnI6WlIzt6h1Oxz%2B6b7BEQ8ofSh4ZpL5XizEOBCIewpmfgA6h%2B4KpKHgb%2Bp2Up5fAQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/0zgo4ysj/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KjsCnUqBsjb5jQ%2BCPq0XmXuamMJA8mnI%2FUsm4CCzoSMjz8EV3wtWEeATS4p9gFOLxU%2FJuin%2F%2BDkDoPRibcKmFSX5htbrSphUbY%2BW%2BGp7u2MPW%2Fy5wKfAQ%2BX1s2HqQn%2F3t8728jewpsD%2Fz9vDD1r9KskWD8z8mx0rXRrUOVvgZegB0q%2FGsV8WjwhlkimY26j1zXpqZaLlE7uAjrsrA2DQqFapVGjTRg9xAzCMaYe0iH3Fkil%2F27VSNYxw%2FpV2aq8jBVC4w5ljvqJdCK9xUcUsrnI6WlIzt6h1Oxz%2B6b7BEQ8ofSh4ZpL5XizEOBCIewpmfgA6h%2B4KpKHgb%2Bp2Up5fAQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde18391ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:18:26,331 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15622'}
2024-01-26 17:18:26,331 ERROR   wandb-upload_0:3042420 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:18:26,375 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:31,377 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:36,379 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:41,380 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:46,382 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:51,385 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:56,387 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:01,390 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:06,392 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:11,394 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:16,396 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:21,399 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:26,401 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:31,403 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:36,404 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:41,407 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:46,409 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:51,411 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:56,413 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:01,416 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:01,521 INFO    wandb-upload_2:3042420 [upload_job.py:push():89] Uploaded file /home/yanxindong/.local/share/wandb/artifacts/staging/tmpy3d4fhdu
2024-01-26 17:20:06,418 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:11,420 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:16,422 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:20,028 INFO    wandb-upload_1:3042420 [upload_job.py:push():89] Uploaded file /home/yanxindong/.local/share/wandb/artifacts/staging/tmpe1t62oid
2024-01-26 17:20:21,425 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:21,973 INFO    SenderThread:3042420 [sender.py:send_artifact():1494] sent artifact job-https___github.com_kkkjj-d_mkor.git_bert_run_pretraining.py - {'id': 'QXJ0aWZhY3Q6NzAzNzg5NjMy', 'state': 'PENDING', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjEzMzk4MTIwMA==', 'latestArtifact': None}}
2024-01-26 17:20:21,974 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: defer
2024-01-26 17:20:21,974 INFO    SenderThread:3042420 [sender.py:send_request_defer():613] handle sender defer: 9
2024-01-26 17:20:21,974 INFO    SenderThread:3042420 [dir_watcher.py:finish():358] shutting down directory watcher
2024-01-26 17:20:21,974 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:20:22,044 INFO    SenderThread:3042420 [dir_watcher.py:finish():388] scan: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/files
2024-01-26 17:20:22,044 INFO    SenderThread:3042420 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/files/wandb-summary.json wandb-summary.json
2024-01-26 17:20:22,044 INFO    SenderThread:3042420 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/files/conda-environment.yaml conda-environment.yaml
2024-01-26 17:20:22,044 INFO    SenderThread:3042420 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/files/wandb-metadata.json wandb-metadata.json
2024-01-26 17:20:22,044 INFO    SenderThread:3042420 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/files/output.log output.log
2024-01-26 17:20:22,044 INFO    SenderThread:3042420 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/files/requirements.txt requirements.txt
2024-01-26 17:20:22,044 INFO    SenderThread:3042420 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/files/config.yaml config.yaml
2024-01-26 17:20:22,045 INFO    SenderThread:3042420 [sender.py:transition_state():617] send defer: 10
2024-01-26 17:20:22,045 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:22,045 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:20:22,045 INFO    HandlerThread:3042420 [handler.py:handle_request_defer():172] handle defer: 10
2024-01-26 17:20:22,051 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: defer
2024-01-26 17:20:22,053 INFO    SenderThread:3042420 [sender.py:send_request_defer():613] handle sender defer: 10
2024-01-26 17:20:22,053 INFO    SenderThread:3042420 [file_pusher.py:finish():175] shutting down file pusher
2024-01-26 17:20:22,425 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:22,426 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:22,706 INFO    wandb-upload_2:3042420 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/files/conda-environment.yaml
2024-01-26 17:20:23,280 INFO    wandb-upload_4:3042420 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/files/requirements.txt
2024-01-26 17:20:23,427 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:23,427 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:23,861 INFO    wandb-upload_5:3042420 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/files/config.yaml
2024-01-26 17:20:23,875 INFO    wandb-upload_3:3042420 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/files/wandb-summary.json
2024-01-26 17:20:23,941 INFO    wandb-upload_1:3042420 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/files/output.log
2024-01-26 17:20:24,427 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:24,428 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:25,428 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:25,428 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:26,429 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:26,430 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:27,430 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:27,431 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:20:27,431 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:28,431 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:28,432 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:29,432 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:29,433 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:30,433 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:30,433 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:31,434 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:31,435 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:32,434 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:32,435 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:32,435 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:20:33,435 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:33,435 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:34,435 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:34,436 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:35,437 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:35,438 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:36,440 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:36,441 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:37,441 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:37,441 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:37,442 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:20:38,442 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:38,442 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:39,443 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:39,443 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:40,445 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:40,445 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:41,445 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:41,446 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:42,447 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:42,448 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:42,449 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:20:43,447 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:43,448 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:44,447 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:44,448 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:45,449 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:45,449 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:46,449 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:46,450 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:47,450 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:47,451 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:47,451 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:20:48,451 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:48,452 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:49,452 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:49,452 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:50,453 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:50,453 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:51,453 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:51,454 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:52,454 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:52,455 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:52,455 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:20:53,454 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:53,455 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:54,455 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:54,456 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:55,457 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:55,457 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:56,457 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:56,458 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:57,459 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:57,459 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:20:57,460 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:58,459 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:58,460 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:59,461 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:59,461 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:00,461 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:00,462 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:01,463 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:01,463 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:02,463 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:02,464 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:02,464 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:03,464 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:03,464 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:04,465 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:04,465 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:05,467 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:05,467 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:06,467 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:06,468 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:07,469 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:07,469 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:07,470 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:08,470 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:08,471 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:09,471 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:09,471 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:10,471 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:10,472 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:11,474 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:11,474 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:12,475 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:12,476 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:12,477 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:13,477 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:13,478 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:14,478 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:14,479 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:15,479 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:15,479 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:16,480 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:16,480 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:17,481 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:17,481 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:17,482 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:18,481 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:18,481 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:19,481 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:19,482 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:20,483 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:20,483 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:21,483 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:21,484 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:22,484 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:22,485 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:22,486 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:23,485 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:23,486 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:24,486 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:24,487 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:25,487 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:25,488 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:26,488 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:26,488 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:27,488 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:27,488 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:27,489 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:28,489 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:28,490 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:29,490 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:29,491 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:30,491 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:30,492 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:31,491 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:31,492 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:32,492 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:32,493 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:32,494 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:33,493 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:33,494 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:34,493 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:34,494 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:35,494 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:35,495 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:36,495 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:36,495 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:37,495 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:37,496 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:37,496 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:38,496 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:38,497 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:39,497 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:39,498 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:40,498 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:40,499 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:41,499 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:41,501 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:42,499 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:42,499 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:42,500 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:43,499 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:43,500 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:44,500 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:44,500 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:45,500 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:45,501 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:46,501 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:46,502 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:47,502 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:47,503 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:47,504 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:48,503 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:48,504 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:49,504 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:49,505 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:50,505 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:50,506 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:51,505 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:51,506 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:52,506 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:52,506 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:52,506 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:53,507 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:53,507 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:54,507 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:54,508 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:55,509 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:55,510 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:56,510 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:56,511 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:57,511 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:57,512 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:57,513 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:58,513 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:58,514 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:59,514 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:59,514 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:00,515 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:00,516 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:01,515 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:01,516 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:02,516 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:02,517 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:02,518 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:03,517 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:03,517 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:04,517 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:04,518 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:05,518 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:05,518 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:06,519 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:06,520 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:07,520 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:07,520 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:07,522 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:08,520 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:08,522 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:09,522 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:09,522 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:10,523 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:10,523 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:11,523 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:11,524 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:12,525 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:12,526 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:12,527 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:13,527 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:13,528 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:14,528 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:14,528 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:15,528 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:15,529 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:16,529 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:16,530 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:17,530 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:17,531 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:17,531 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:18,530 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:18,531 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:19,531 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:19,532 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:20,532 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:20,533 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:21,533 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:21,534 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:22,534 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:22,534 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:22,535 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:23,534 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:23,535 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:24,536 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:24,536 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:25,536 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:25,537 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:26,537 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:26,538 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:27,537 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:27,538 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:27,538 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:28,538 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:28,539 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:29,539 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:29,539 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:30,540 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:30,541 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:31,540 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:31,541 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:32,541 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:32,541 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:32,542 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:33,542 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:33,542 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:34,542 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:34,543 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:35,543 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:35,543 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:36,544 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:36,545 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:37,545 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:37,545 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:37,546 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:38,545 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:38,545 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:39,546 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:39,547 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:40,548 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:40,548 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:41,549 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:41,550 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:42,550 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:42,551 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:42,551 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:43,551 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:43,552 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:44,551 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:44,552 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:45,554 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:45,554 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:46,555 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:46,555 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:47,556 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:47,556 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:47,557 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:48,557 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:48,557 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:49,558 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:49,559 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:50,558 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:50,559 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:51,558 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:51,559 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:52,560 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:52,560 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:52,561 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:53,560 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:53,561 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:54,561 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:54,562 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:55,561 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:55,562 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:56,563 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:56,563 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:57,563 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:57,564 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:57,564 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:58,564 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:58,564 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:59,564 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:59,565 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:00,565 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:00,566 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:01,567 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:01,567 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:02,568 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:02,568 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:02,569 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:03,569 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:03,570 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:04,570 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:04,570 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:05,570 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:05,570 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:06,571 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:06,571 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:07,572 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:07,572 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:07,572 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:08,572 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:08,572 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:09,573 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:09,574 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:10,573 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:10,574 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:11,575 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:11,575 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:12,576 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:12,576 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:12,577 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:13,576 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:13,577 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:14,577 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:14,577 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:15,577 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:15,577 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:16,578 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:16,579 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:17,578 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:17,579 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:17,579 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:18,579 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:18,580 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:19,580 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:19,581 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:20,581 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:20,582 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:21,582 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:21,582 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:22,582 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:22,583 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:22,584 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:23,583 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:23,584 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:24,584 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:24,585 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:25,586 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:25,586 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:26,587 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:26,587 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:27,587 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:27,588 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:27,589 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:28,588 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:28,588 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:29,588 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:29,589 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:30,589 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:30,589 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:31,589 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:31,589 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:32,591 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:32,591 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:32,592 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:33,591 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:33,592 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:34,591 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:34,592 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:35,592 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:35,593 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:36,593 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:36,594 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:37,594 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:37,595 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:37,595 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:38,594 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:38,595 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:39,597 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:39,597 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:40,598 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:40,599 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:41,598 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:41,598 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:42,599 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:42,599 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:42,599 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:43,599 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:43,600 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:44,600 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:44,601 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:45,602 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:45,602 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:46,602 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:46,603 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:47,603 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:47,604 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:47,605 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:48,603 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:48,604 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:49,605 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:49,605 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:50,605 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:50,607 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:51,606 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:51,607 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:52,607 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:52,608 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:52,609 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:53,607 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:53,608 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:54,608 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:54,608 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:55,609 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:55,610 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:56,610 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:56,610 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:57,610 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:57,611 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:57,611 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:58,611 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:58,611 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:59,612 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:59,612 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:00,134 INFO    wandb-upload_0:3042420 [upload_job.py:push():131] Uploaded file /tmp/tmpk1e0f542wandb/ocby62gp-wandb-metadata.json
2024-01-26 17:24:00,334 INFO    Thread-11 :3042420 [sender.py:transition_state():617] send defer: 11
2024-01-26 17:24:00,335 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:24:00,335 INFO    HandlerThread:3042420 [handler.py:handle_request_defer():172] handle defer: 11
2024-01-26 17:24:00,335 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: defer
2024-01-26 17:24:00,335 INFO    SenderThread:3042420 [sender.py:send_request_defer():613] handle sender defer: 11
2024-01-26 17:24:00,335 INFO    SenderThread:3042420 [file_pusher.py:join():181] waiting for file pusher
2024-01-26 17:24:00,335 INFO    SenderThread:3042420 [sender.py:transition_state():617] send defer: 12
2024-01-26 17:24:00,336 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:24:00,336 INFO    HandlerThread:3042420 [handler.py:handle_request_defer():172] handle defer: 12
2024-01-26 17:24:00,336 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: defer
2024-01-26 17:24:00,336 INFO    SenderThread:3042420 [sender.py:send_request_defer():613] handle sender defer: 12
2024-01-26 17:24:00,336 INFO    SenderThread:3042420 [file_stream.py:finish():595] file stream finish called
2024-01-26 17:24:00,607 INFO    SenderThread:3042420 [file_stream.py:finish():599] file stream finish is done
2024-01-26 17:24:00,607 INFO    SenderThread:3042420 [sender.py:transition_state():617] send defer: 13
2024-01-26 17:24:00,607 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:24:00,607 INFO    HandlerThread:3042420 [handler.py:handle_request_defer():172] handle defer: 13
2024-01-26 17:24:00,608 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: defer
2024-01-26 17:24:00,608 INFO    SenderThread:3042420 [sender.py:send_request_defer():613] handle sender defer: 13
2024-01-26 17:24:00,608 INFO    SenderThread:3042420 [sender.py:transition_state():617] send defer: 14
2024-01-26 17:24:00,608 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:24:00,609 INFO    HandlerThread:3042420 [handler.py:handle_request_defer():172] handle defer: 14
2024-01-26 17:24:00,609 DEBUG   SenderThread:3042420 [sender.py:send():382] send: final
2024-01-26 17:24:00,609 DEBUG   SenderThread:3042420 [sender.py:send():382] send: footer
2024-01-26 17:24:00,610 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: defer
2024-01-26 17:24:00,610 INFO    SenderThread:3042420 [sender.py:send_request_defer():613] handle sender defer: 14
2024-01-26 17:24:00,610 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:00,610 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:00,611 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:24:00,611 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:24:00,611 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: server_info
2024-01-26 17:24:00,612 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: get_summary
2024-01-26 17:24:00,612 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: server_info
2024-01-26 17:24:00,616 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: sampled_history
2024-01-26 17:24:00,616 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:24:00,616 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: job_info
2024-01-26 17:24:00,883 DEBUG   SenderThread:3042420 [sender.py:send_request():409] send_request: job_info
2024-01-26 17:24:00,883 INFO    MainThread:3042420 [wandb_run.py:_footer_history_summary_info():3857] rendering history
2024-01-26 17:24:00,883 INFO    MainThread:3042420 [wandb_run.py:_footer_history_summary_info():3889] rendering summary
2024-01-26 17:24:00,884 INFO    MainThread:3042420 [wandb_run.py:_footer_sync_info():3816] logging synced files
2024-01-26 17:24:00,884 DEBUG   HandlerThread:3042420 [handler.py:handle_request():146] handle_request: shutdown
2024-01-26 17:24:00,884 INFO    HandlerThread:3042420 [handler.py:finish():869] shutting down handler
2024-01-26 17:24:01,617 INFO    WriterThread:3042420 [datastore.py:close():296] close: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-0zgo4ysj/run-0zgo4ysj.wandb
2024-01-26 17:24:01,883 INFO    SenderThread:3042420 [sender.py:finish():1572] shutting down sender
2024-01-26 17:24:01,883 INFO    SenderThread:3042420 [file_pusher.py:finish():175] shutting down file pusher
2024-01-26 17:24:01,883 INFO    SenderThread:3042420 [file_pusher.py:join():181] waiting for file pusher
