2024-01-26 17:08:45,615 INFO    StreamThr :3042410 [internal.py:wandb_internal():86] W&B internal server running at pid: 3042410, started at: 2024-01-26 17:08:45.615145
2024-01-26 17:08:45,620 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status
2024-01-26 17:08:45,621 INFO    WriterThread:3042410 [datastore.py:open_for_write():87] open: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/run-oda2kyd2.wandb
2024-01-26 17:08:45,621 DEBUG   SenderThread:3042410 [sender.py:send():382] send: header
2024-01-26 17:08:45,632 DEBUG   SenderThread:3042410 [sender.py:send():382] send: run
2024-01-26 17:08:46,379 ERROR   SenderThread:3042410 [internal_api.py:execute():373] 500 response executing GraphQL.
2024-01-26 17:08:46,379 ERROR   SenderThread:3042410 [internal_api.py:execute():374] {"errors":[{"message":"An internal error occurred. Please contact support.","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-01-26 17:08:47,778 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: check_version
2024-01-26 17:08:47,837 INFO    SenderThread:3042410 [dir_watcher.py:__init__():211] watching files in: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/files
2024-01-26 17:08:47,838 INFO    SenderThread:3042410 [sender.py:_start_run_threads():1136] run started: oda2kyd2 with start time 1706260125.610186
2024-01-26 17:08:47,838 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: check_version
2024-01-26 17:08:48,345 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: run_start
2024-01-26 17:08:48,375 DEBUG   HandlerThread:3042410 [system_info.py:__init__():27] System info init
2024-01-26 17:08:48,376 DEBUG   HandlerThread:3042410 [system_info.py:__init__():42] System info init done
2024-01-26 17:08:48,376 INFO    HandlerThread:3042410 [system_monitor.py:start():194] Starting system monitor
2024-01-26 17:08:48,397 INFO    SystemMonitor:3042410 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-01-26 17:08:48,398 INFO    HandlerThread:3042410 [system_monitor.py:probe():214] Collecting system info
2024-01-26 17:08:48,435 INFO    SystemMonitor:3042410 [interfaces.py:start():190] Started cpu monitoring
2024-01-26 17:08:48,449 INFO    SystemMonitor:3042410 [interfaces.py:start():190] Started disk monitoring
2024-01-26 17:08:48,473 INFO    SystemMonitor:3042410 [interfaces.py:start():190] Started gpu monitoring
2024-01-26 17:08:48,506 INFO    SystemMonitor:3042410 [interfaces.py:start():190] Started memory monitoring
2024-01-26 17:08:48,553 INFO    SystemMonitor:3042410 [interfaces.py:start():190] Started network monitoring
2024-01-26 17:08:48,585 DEBUG   HandlerThread:3042410 [system_info.py:probe():151] Probing system
2024-01-26 17:08:48,619 DEBUG   HandlerThread:3042410 [system_info.py:_probe_git():136] Probing git
2024-01-26 17:08:48,689 DEBUG   HandlerThread:3042410 [system_info.py:_probe_git():144] Probing git done
2024-01-26 17:08:48,689 DEBUG   HandlerThread:3042410 [system_info.py:probe():199] Probing system done
2024-01-26 17:08:48,689 DEBUG   HandlerThread:3042410 [system_monitor.py:probe():223] {'os': 'Linux-5.15.0-91-generic-x86_64-with-glibc2.17', 'python': '3.8.17', 'heartbeatAt': '2024-01-26T09:08:48.585127', 'startedAt': '2024-01-26T09:08:45.604675', 'docker': None, 'cuda': None, 'args': ('--local_rank=6', '--config_file', 'config/bert_pretraining_phase2_config.json', '--input_dir', '/home/yanxindong/mkor/bert/data/encoded/sequences_lowercase_max_seq_len_512_next_seq_task_true', '--output_dir', 'results/adam', '--weight_decay', '0.01', '--num_steps_per_checkpoint', '200'), 'state': 'running', 'program': 'run_pretraining.py', 'codePathLocal': 'run_pretraining.py', 'codePath': 'bert/run_pretraining.py', 'git': {'remote': 'https://github.com/kkkjj-d/mkor.git', 'commit': 'efe99e84fef5594780cfb1df6d6a1f61da4ebba0'}, 'email': '1262670315@qq.com', 'root': '/home/yanxindong/mkor', 'host': 'a6000-X640-G40', 'username': 'yanxindong', 'executable': '/home/yanxindong/anaconda/envs/eva/bin/python', 'cpu_count': 64, 'cpu_count_logical': 128, 'cpu_freq': {'current': 2102.3519765625, 'min': 800.0, 'max': 3400.0}, 'cpu_freq_per_core': [{'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3160.64, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 2200.0, 'min': 800.0, 'max': 3400.0}, {'current': 2500.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2200.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 1800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 2200.0, 'min': 800.0, 'max': 3400.0}, {'current': 1900.0, 'min': 800.0, 'max': 3400.0}, {'current': 2200.0, 'min': 800.0, 'max': 3400.0}, {'current': 2000.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2700.0, 'min': 800.0, 'max': 3400.0}, {'current': 1700.0, 'min': 800.0, 'max': 3400.0}, {'current': 1400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1700.0, 'min': 800.0, 'max': 3400.0}, {'current': 2000.0, 'min': 800.0, 'max': 3400.0}, {'current': 2300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 2300.0, 'min': 800.0, 'max': 3400.0}, {'current': 2877.126, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 2604.515, 'min': 800.0, 'max': 3400.0}, {'current': 1900.0, 'min': 800.0, 'max': 3400.0}, {'current': 2600.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2000.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 2756.836, 'min': 800.0, 'max': 3400.0}, {'current': 2400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2200.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1900.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2000.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 2832.889, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1600.0, 'min': 800.0, 'max': 3400.0}, {'current': 2600.0, 'min': 800.0, 'max': 3400.0}, {'current': 3200.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 2424.343, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 2839.348, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 1700.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2443.005, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3000.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 1900.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2401.871, 'min': 800.0, 'max': 3400.0}, {'current': 2200.0, 'min': 800.0, 'max': 3400.0}, {'current': 2593.071, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2300.0, 'min': 800.0, 'max': 3400.0}, {'current': 1300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1500.0, 'min': 800.0, 'max': 3400.0}, {'current': 1700.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1600.0, 'min': 800.0, 'max': 3400.0}, {'current': 2484.461, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1993.569, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2900.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2700.0, 'min': 800.0, 'max': 3400.0}, {'current': 2238.83, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2910.341, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3236.544, 'min': 800.0, 'max': 3400.0}, {'current': 2619.23, 'min': 800.0, 'max': 3400.0}, {'current': 3209.624, 'min': 800.0, 'max': 3400.0}, {'current': 2859.475, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}], 'disk': {'/': {'total': 438.05088806152344, 'used': 28.042728424072266}}, 'gpu': 'NVIDIA RTX A6000', 'gpu_count': 8, 'gpu_devices': [{'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}], 'memory': {'total': 503.51250076293945}}
2024-01-26 17:08:48,690 INFO    HandlerThread:3042410 [system_monitor.py:probe():224] Finished collecting system info
2024-01-26 17:08:48,690 INFO    HandlerThread:3042410 [system_monitor.py:probe():227] Publishing system info
2024-01-26 17:08:48,690 DEBUG   HandlerThread:3042410 [system_info.py:_save_conda():208] Saving list of conda packages installed into the current environment
2024-01-26 17:08:48,835 INFO    Thread-12 :3042410 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/files/conda-environment.yaml
2024-01-26 17:08:58,837 INFO    Thread-12 :3042410 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/files/conda-environment.yaml
2024-01-26 17:08:58,931 DEBUG   HandlerThread:3042410 [system_info.py:_save_conda():220] Saving conda packages done
2024-01-26 17:08:58,933 INFO    HandlerThread:3042410 [system_monitor.py:probe():229] Finished publishing system info
2024-01-26 17:08:58,938 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:08:58,938 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:08:58,941 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:08:58,941 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:08:58,944 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: python_packages
2024-01-26 17:08:58,944 DEBUG   SenderThread:3042410 [sender.py:send():382] send: files
2024-01-26 17:08:58,944 INFO    SenderThread:3042410 [sender.py:_save_file():1403] saving file wandb-metadata.json with policy now
2024-01-26 17:08:58,945 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: python_packages
2024-01-26 17:08:58,962 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:08:58,962 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:08:58,993 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:08:59,249 DEBUG   SenderThread:3042410 [sender.py:send():382] send: telemetry
2024-01-26 17:08:59,837 INFO    Thread-12 :3042410 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/files/wandb-metadata.json
2024-01-26 17:08:59,837 INFO    Thread-12 :3042410 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/files/requirements.txt
2024-01-26 17:08:59,847 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/oda2kyd2/wandb-metadata.json?Expires=1706346539&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rDnGTUPH6v9ro5qMAX8yPoUj0e0HvXUoAEEstrJL4vooRueZ%2BCvpICQYfceCargGw2sdsfKmygInUsNbr2gt%2BnSeS%2BGte35u23WF%2BOJxrjjoyqp8CzKilDkNFolktQ%2BkCW54vdtZP9aUwYQY2Y3SOutyvCuK9fmm4BQcpaTRAeL0778XsXha5xtW%2B4tlinbBSk4yFnLFWNuhOk4ZD1L7lR3tTK%2FnvuM8mDR6Vd7GGtbRMgcjQbWNDhIZ0OGil0bF1CSHmful1BLqjOV0edSqRETIy2PMgBiCJpS%2BBIVelyIEVFREMzL3cyy%2BDP9609JrW1Z9CrINmr7%2BHN83k9KUaw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/oda2kyd2/wandb-metadata.json?Expires=1706346539&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rDnGTUPH6v9ro5qMAX8yPoUj0e0HvXUoAEEstrJL4vooRueZ%2BCvpICQYfceCargGw2sdsfKmygInUsNbr2gt%2BnSeS%2BGte35u23WF%2BOJxrjjoyqp8CzKilDkNFolktQ%2BkCW54vdtZP9aUwYQY2Y3SOutyvCuK9fmm4BQcpaTRAeL0778XsXha5xtW%2B4tlinbBSk4yFnLFWNuhOk4ZD1L7lR3tTK%2FnvuM8mDR6Vd7GGtbRMgcjQbWNDhIZ0OGil0bF1CSHmful1BLqjOV0edSqRETIy2PMgBiCJpS%2BBIVelyIEVFREMzL3cyy%2BDP9609JrW1Z9CrINmr7%2BHN83k9KUaw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6000518cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:08:59,847 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15651'}
2024-01-26 17:08:59,847 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:00,933 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/oda2kyd2/wandb-metadata.json?Expires=1706346539&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rDnGTUPH6v9ro5qMAX8yPoUj0e0HvXUoAEEstrJL4vooRueZ%2BCvpICQYfceCargGw2sdsfKmygInUsNbr2gt%2BnSeS%2BGte35u23WF%2BOJxrjjoyqp8CzKilDkNFolktQ%2BkCW54vdtZP9aUwYQY2Y3SOutyvCuK9fmm4BQcpaTRAeL0778XsXha5xtW%2B4tlinbBSk4yFnLFWNuhOk4ZD1L7lR3tTK%2FnvuM8mDR6Vd7GGtbRMgcjQbWNDhIZ0OGil0bF1CSHmful1BLqjOV0edSqRETIy2PMgBiCJpS%2BBIVelyIEVFREMzL3cyy%2BDP9609JrW1Z9CrINmr7%2BHN83k9KUaw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/oda2kyd2/wandb-metadata.json?Expires=1706346539&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rDnGTUPH6v9ro5qMAX8yPoUj0e0HvXUoAEEstrJL4vooRueZ%2BCvpICQYfceCargGw2sdsfKmygInUsNbr2gt%2BnSeS%2BGte35u23WF%2BOJxrjjoyqp8CzKilDkNFolktQ%2BkCW54vdtZP9aUwYQY2Y3SOutyvCuK9fmm4BQcpaTRAeL0778XsXha5xtW%2B4tlinbBSk4yFnLFWNuhOk4ZD1L7lR3tTK%2FnvuM8mDR6Vd7GGtbRMgcjQbWNDhIZ0OGil0bF1CSHmful1BLqjOV0edSqRETIy2PMgBiCJpS%2BBIVelyIEVFREMzL3cyy%2BDP9609JrW1Z9CrINmr7%2BHN83k9KUaw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f600056af40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:00,933 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15651'}
2024-01-26 17:09:00,933 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:02,249 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:03,125 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/oda2kyd2/wandb-metadata.json?Expires=1706346539&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rDnGTUPH6v9ro5qMAX8yPoUj0e0HvXUoAEEstrJL4vooRueZ%2BCvpICQYfceCargGw2sdsfKmygInUsNbr2gt%2BnSeS%2BGte35u23WF%2BOJxrjjoyqp8CzKilDkNFolktQ%2BkCW54vdtZP9aUwYQY2Y3SOutyvCuK9fmm4BQcpaTRAeL0778XsXha5xtW%2B4tlinbBSk4yFnLFWNuhOk4ZD1L7lR3tTK%2FnvuM8mDR6Vd7GGtbRMgcjQbWNDhIZ0OGil0bF1CSHmful1BLqjOV0edSqRETIy2PMgBiCJpS%2BBIVelyIEVFREMzL3cyy%2BDP9609JrW1Z9CrINmr7%2BHN83k9KUaw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/oda2kyd2/wandb-metadata.json?Expires=1706346539&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rDnGTUPH6v9ro5qMAX8yPoUj0e0HvXUoAEEstrJL4vooRueZ%2BCvpICQYfceCargGw2sdsfKmygInUsNbr2gt%2BnSeS%2BGte35u23WF%2BOJxrjjoyqp8CzKilDkNFolktQ%2BkCW54vdtZP9aUwYQY2Y3SOutyvCuK9fmm4BQcpaTRAeL0778XsXha5xtW%2B4tlinbBSk4yFnLFWNuhOk4ZD1L7lR3tTK%2FnvuM8mDR6Vd7GGtbRMgcjQbWNDhIZ0OGil0bF1CSHmful1BLqjOV0edSqRETIy2PMgBiCJpS%2BBIVelyIEVFREMzL3cyy%2BDP9609JrW1Z9CrINmr7%2BHN83k9KUaw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6000529160>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:03,126 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15651'}
2024-01-26 17:09:03,126 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:03,126 INFO    wandb-upload_0:3042410 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f6000529160>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/oda2kyd2/wandb-metadata.json?Expires=1706346539&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rDnGTUPH6v9ro5qMAX8yPoUj0e0HvXUoAEEstrJL4vooRueZ%2BCvpICQYfceCargGw2sdsfKmygInUsNbr2gt%2BnSeS%2BGte35u23WF%2BOJxrjjoyqp8CzKilDkNFolktQ%2BkCW54vdtZP9aUwYQY2Y3SOutyvCuK9fmm4BQcpaTRAeL0778XsXha5xtW%2B4tlinbBSk4yFnLFWNuhOk4ZD1L7lR3tTK%2FnvuM8mDR6Vd7GGtbRMgcjQbWNDhIZ0OGil0bF1CSHmful1BLqjOV0edSqRETIy2PMgBiCJpS%2BBIVelyIEVFREMzL3cyy%2BDP9609JrW1Z9CrINmr7%2BHN83k9KUaw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6000529160>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/oda2kyd2/wandb-metadata.json?Expires=1706346539&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rDnGTUPH6v9ro5qMAX8yPoUj0e0HvXUoAEEstrJL4vooRueZ%2BCvpICQYfceCargGw2sdsfKmygInUsNbr2gt%2BnSeS%2BGte35u23WF%2BOJxrjjoyqp8CzKilDkNFolktQ%2BkCW54vdtZP9aUwYQY2Y3SOutyvCuK9fmm4BQcpaTRAeL0778XsXha5xtW%2B4tlinbBSk4yFnLFWNuhOk4ZD1L7lR3tTK%2FnvuM8mDR6Vd7GGtbRMgcjQbWNDhIZ0OGil0bF1CSHmful1BLqjOV0edSqRETIy2PMgBiCJpS%2BBIVelyIEVFREMzL3cyy%2BDP9609JrW1Z9CrINmr7%2BHN83k9KUaw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6000529160>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2789, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-01-26 17:09:07,250 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:07,404 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/oda2kyd2/wandb-metadata.json?Expires=1706346539&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rDnGTUPH6v9ro5qMAX8yPoUj0e0HvXUoAEEstrJL4vooRueZ%2BCvpICQYfceCargGw2sdsfKmygInUsNbr2gt%2BnSeS%2BGte35u23WF%2BOJxrjjoyqp8CzKilDkNFolktQ%2BkCW54vdtZP9aUwYQY2Y3SOutyvCuK9fmm4BQcpaTRAeL0778XsXha5xtW%2B4tlinbBSk4yFnLFWNuhOk4ZD1L7lR3tTK%2FnvuM8mDR6Vd7GGtbRMgcjQbWNDhIZ0OGil0bF1CSHmful1BLqjOV0edSqRETIy2PMgBiCJpS%2BBIVelyIEVFREMzL3cyy%2BDP9609JrW1Z9CrINmr7%2BHN83k9KUaw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/oda2kyd2/wandb-metadata.json?Expires=1706346539&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rDnGTUPH6v9ro5qMAX8yPoUj0e0HvXUoAEEstrJL4vooRueZ%2BCvpICQYfceCargGw2sdsfKmygInUsNbr2gt%2BnSeS%2BGte35u23WF%2BOJxrjjoyqp8CzKilDkNFolktQ%2BkCW54vdtZP9aUwYQY2Y3SOutyvCuK9fmm4BQcpaTRAeL0778XsXha5xtW%2B4tlinbBSk4yFnLFWNuhOk4ZD1L7lR3tTK%2FnvuM8mDR6Vd7GGtbRMgcjQbWNDhIZ0OGil0bF1CSHmful1BLqjOV0edSqRETIy2PMgBiCJpS%2BBIVelyIEVFREMzL3cyy%2BDP9609JrW1Z9CrINmr7%2BHN83k9KUaw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f600056a430>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:07,404 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15651'}
2024-01-26 17:09:07,404 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:12,251 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:13,954 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:09:13,955 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:09:14,002 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:09:16,767 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/oda2kyd2/wandb-metadata.json?Expires=1706346539&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rDnGTUPH6v9ro5qMAX8yPoUj0e0HvXUoAEEstrJL4vooRueZ%2BCvpICQYfceCargGw2sdsfKmygInUsNbr2gt%2BnSeS%2BGte35u23WF%2BOJxrjjoyqp8CzKilDkNFolktQ%2BkCW54vdtZP9aUwYQY2Y3SOutyvCuK9fmm4BQcpaTRAeL0778XsXha5xtW%2B4tlinbBSk4yFnLFWNuhOk4ZD1L7lR3tTK%2FnvuM8mDR6Vd7GGtbRMgcjQbWNDhIZ0OGil0bF1CSHmful1BLqjOV0edSqRETIy2PMgBiCJpS%2BBIVelyIEVFREMzL3cyy%2BDP9609JrW1Z9CrINmr7%2BHN83k9KUaw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/oda2kyd2/wandb-metadata.json?Expires=1706346539&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rDnGTUPH6v9ro5qMAX8yPoUj0e0HvXUoAEEstrJL4vooRueZ%2BCvpICQYfceCargGw2sdsfKmygInUsNbr2gt%2BnSeS%2BGte35u23WF%2BOJxrjjoyqp8CzKilDkNFolktQ%2BkCW54vdtZP9aUwYQY2Y3SOutyvCuK9fmm4BQcpaTRAeL0778XsXha5xtW%2B4tlinbBSk4yFnLFWNuhOk4ZD1L7lR3tTK%2FnvuM8mDR6Vd7GGtbRMgcjQbWNDhIZ0OGil0bF1CSHmful1BLqjOV0edSqRETIy2PMgBiCJpS%2BBIVelyIEVFREMzL3cyy%2BDP9609JrW1Z9CrINmr7%2BHN83k9KUaw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6000529dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:16,767 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15651'}
2024-01-26 17:09:16,767 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:18,246 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:18,843 INFO    Thread-12 :3042410 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/files/config.yaml
2024-01-26 17:09:23,566 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:28,614 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:28,958 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:09:28,958 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:09:29,002 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:09:33,752 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/oda2kyd2/wandb-metadata.json?Expires=1706346539&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rDnGTUPH6v9ro5qMAX8yPoUj0e0HvXUoAEEstrJL4vooRueZ%2BCvpICQYfceCargGw2sdsfKmygInUsNbr2gt%2BnSeS%2BGte35u23WF%2BOJxrjjoyqp8CzKilDkNFolktQ%2BkCW54vdtZP9aUwYQY2Y3SOutyvCuK9fmm4BQcpaTRAeL0778XsXha5xtW%2B4tlinbBSk4yFnLFWNuhOk4ZD1L7lR3tTK%2FnvuM8mDR6Vd7GGtbRMgcjQbWNDhIZ0OGil0bF1CSHmful1BLqjOV0edSqRETIy2PMgBiCJpS%2BBIVelyIEVFREMzL3cyy%2BDP9609JrW1Z9CrINmr7%2BHN83k9KUaw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/oda2kyd2/wandb-metadata.json?Expires=1706346539&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rDnGTUPH6v9ro5qMAX8yPoUj0e0HvXUoAEEstrJL4vooRueZ%2BCvpICQYfceCargGw2sdsfKmygInUsNbr2gt%2BnSeS%2BGte35u23WF%2BOJxrjjoyqp8CzKilDkNFolktQ%2BkCW54vdtZP9aUwYQY2Y3SOutyvCuK9fmm4BQcpaTRAeL0778XsXha5xtW%2B4tlinbBSk4yFnLFWNuhOk4ZD1L7lR3tTK%2FnvuM8mDR6Vd7GGtbRMgcjQbWNDhIZ0OGil0bF1CSHmful1BLqjOV0edSqRETIy2PMgBiCJpS%2BBIVelyIEVFREMzL3cyy%2BDP9609JrW1Z9CrINmr7%2BHN83k9KUaw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f60005292b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:33,752 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15651'}
2024-01-26 17:09:33,752 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:34,244 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:39,245 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:43,955 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:09:43,955 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:09:43,998 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:09:45,124 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:48,554 DEBUG   SystemMonitor:3042410 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-01-26 17:09:48,557 DEBUG   SenderThread:3042410 [sender.py:send():382] send: stats
2024-01-26 17:09:50,559 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:55,560 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:58,954 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:09:58,955 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:09:59,002 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:10:01,286 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:06,386 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:11,390 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:13,146 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/oda2kyd2/wandb-metadata.json?Expires=1706346539&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rDnGTUPH6v9ro5qMAX8yPoUj0e0HvXUoAEEstrJL4vooRueZ%2BCvpICQYfceCargGw2sdsfKmygInUsNbr2gt%2BnSeS%2BGte35u23WF%2BOJxrjjoyqp8CzKilDkNFolktQ%2BkCW54vdtZP9aUwYQY2Y3SOutyvCuK9fmm4BQcpaTRAeL0778XsXha5xtW%2B4tlinbBSk4yFnLFWNuhOk4ZD1L7lR3tTK%2FnvuM8mDR6Vd7GGtbRMgcjQbWNDhIZ0OGil0bF1CSHmful1BLqjOV0edSqRETIy2PMgBiCJpS%2BBIVelyIEVFREMzL3cyy%2BDP9609JrW1Z9CrINmr7%2BHN83k9KUaw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/oda2kyd2/wandb-metadata.json?Expires=1706346539&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rDnGTUPH6v9ro5qMAX8yPoUj0e0HvXUoAEEstrJL4vooRueZ%2BCvpICQYfceCargGw2sdsfKmygInUsNbr2gt%2BnSeS%2BGte35u23WF%2BOJxrjjoyqp8CzKilDkNFolktQ%2BkCW54vdtZP9aUwYQY2Y3SOutyvCuK9fmm4BQcpaTRAeL0778XsXha5xtW%2B4tlinbBSk4yFnLFWNuhOk4ZD1L7lR3tTK%2FnvuM8mDR6Vd7GGtbRMgcjQbWNDhIZ0OGil0bF1CSHmful1BLqjOV0edSqRETIy2PMgBiCJpS%2BBIVelyIEVFREMzL3cyy%2BDP9609JrW1Z9CrINmr7%2BHN83k9KUaw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f600037f7f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:10:13,146 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15651'}
2024-01-26 17:10:13,147 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:10:13,958 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:10:13,958 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:10:14,002 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:10:17,267 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:18,560 DEBUG   SenderThread:3042410 [sender.py:send():382] send: stats
2024-01-26 17:10:22,562 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:27,563 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:28,955 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:10:28,955 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:10:29,001 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:10:33,185 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:34,078 INFO    Thread-12 :3042410 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/files/output.log
2024-01-26 17:10:36,078 INFO    Thread-12 :3042410 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/files/output.log
2024-01-26 17:10:38,186 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:43,186 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:45,879 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:10:45,880 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:10:45,883 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:10:48,524 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:48,563 DEBUG   SenderThread:3042410 [sender.py:send():382] send: stats
2024-01-26 17:10:53,937 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:59,005 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:00,881 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:11:00,881 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:00,922 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:11:04,314 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:09,326 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:14,329 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:15,923 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:11:15,923 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:15,926 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:11:18,620 DEBUG   SenderThread:3042410 [sender.py:send():382] send: stats
2024-01-26 17:11:19,623 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:24,697 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:29,790 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:30,256 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/oda2kyd2/wandb-metadata.json?Expires=1706346539&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rDnGTUPH6v9ro5qMAX8yPoUj0e0HvXUoAEEstrJL4vooRueZ%2BCvpICQYfceCargGw2sdsfKmygInUsNbr2gt%2BnSeS%2BGte35u23WF%2BOJxrjjoyqp8CzKilDkNFolktQ%2BkCW54vdtZP9aUwYQY2Y3SOutyvCuK9fmm4BQcpaTRAeL0778XsXha5xtW%2B4tlinbBSk4yFnLFWNuhOk4ZD1L7lR3tTK%2FnvuM8mDR6Vd7GGtbRMgcjQbWNDhIZ0OGil0bF1CSHmful1BLqjOV0edSqRETIy2PMgBiCJpS%2BBIVelyIEVFREMzL3cyy%2BDP9609JrW1Z9CrINmr7%2BHN83k9KUaw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/oda2kyd2/wandb-metadata.json?Expires=1706346539&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rDnGTUPH6v9ro5qMAX8yPoUj0e0HvXUoAEEstrJL4vooRueZ%2BCvpICQYfceCargGw2sdsfKmygInUsNbr2gt%2BnSeS%2BGte35u23WF%2BOJxrjjoyqp8CzKilDkNFolktQ%2BkCW54vdtZP9aUwYQY2Y3SOutyvCuK9fmm4BQcpaTRAeL0778XsXha5xtW%2B4tlinbBSk4yFnLFWNuhOk4ZD1L7lR3tTK%2FnvuM8mDR6Vd7GGtbRMgcjQbWNDhIZ0OGil0bF1CSHmful1BLqjOV0edSqRETIy2PMgBiCJpS%2BBIVelyIEVFREMzL3cyy%2BDP9609JrW1Z9CrINmr7%2BHN83k9KUaw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6000346370>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:11:30,256 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15651'}
2024-01-26 17:11:30,256 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:11:30,879 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:11:30,880 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:30,924 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:11:35,201 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:40,206 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:45,206 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:45,879 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:11:45,880 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:45,922 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:11:48,623 DEBUG   SenderThread:3042410 [sender.py:send():382] send: stats
2024-01-26 17:11:50,625 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:55,626 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:00,626 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:00,880 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:12:00,880 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:12:00,922 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:12:06,226 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:11,228 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:15,904 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:12:15,905 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:12:15,922 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:12:16,317 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:18,625 DEBUG   SenderThread:3042410 [sender.py:send():382] send: stats
2024-01-26 17:12:21,722 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:26,730 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:30,909 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:12:30,909 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:12:30,921 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:12:32,278 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:37,286 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:42,322 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:45,880 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:12:45,880 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:12:45,922 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:12:48,236 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:48,629 DEBUG   SenderThread:3042410 [sender.py:send():382] send: stats
2024-01-26 17:12:53,631 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:58,631 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:00,880 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:13:00,880 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:13:00,922 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:13:04,223 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:09,224 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:14,225 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:15,880 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:13:15,880 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:13:15,922 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:13:18,692 DEBUG   SenderThread:3042410 [sender.py:send():382] send: stats
2024-01-26 17:13:19,693 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:24,698 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:29,699 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:30,923 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:13:30,923 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:13:30,923 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:13:35,378 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:40,565 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:45,566 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:45,880 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:13:45,880 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:13:45,922 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:13:48,708 DEBUG   SenderThread:3042410 [sender.py:send():382] send: stats
2024-01-26 17:13:50,756 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:55,790 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:00,795 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:00,880 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:14:00,881 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:14:00,922 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:14:06,176 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:07,128 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/oda2kyd2/wandb-metadata.json?Expires=1706346539&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rDnGTUPH6v9ro5qMAX8yPoUj0e0HvXUoAEEstrJL4vooRueZ%2BCvpICQYfceCargGw2sdsfKmygInUsNbr2gt%2BnSeS%2BGte35u23WF%2BOJxrjjoyqp8CzKilDkNFolktQ%2BkCW54vdtZP9aUwYQY2Y3SOutyvCuK9fmm4BQcpaTRAeL0778XsXha5xtW%2B4tlinbBSk4yFnLFWNuhOk4ZD1L7lR3tTK%2FnvuM8mDR6Vd7GGtbRMgcjQbWNDhIZ0OGil0bF1CSHmful1BLqjOV0edSqRETIy2PMgBiCJpS%2BBIVelyIEVFREMzL3cyy%2BDP9609JrW1Z9CrINmr7%2BHN83k9KUaw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/oda2kyd2/wandb-metadata.json?Expires=1706346539&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rDnGTUPH6v9ro5qMAX8yPoUj0e0HvXUoAEEstrJL4vooRueZ%2BCvpICQYfceCargGw2sdsfKmygInUsNbr2gt%2BnSeS%2BGte35u23WF%2BOJxrjjoyqp8CzKilDkNFolktQ%2BkCW54vdtZP9aUwYQY2Y3SOutyvCuK9fmm4BQcpaTRAeL0778XsXha5xtW%2B4tlinbBSk4yFnLFWNuhOk4ZD1L7lR3tTK%2FnvuM8mDR6Vd7GGtbRMgcjQbWNDhIZ0OGil0bF1CSHmful1BLqjOV0edSqRETIy2PMgBiCJpS%2BBIVelyIEVFREMzL3cyy%2BDP9609JrW1Z9CrINmr7%2BHN83k9KUaw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6000384640>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:14:07,129 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15651'}
2024-01-26 17:14:07,129 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:14:11,177 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:15,880 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:14:15,881 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:14:15,922 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:14:16,182 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:18,710 DEBUG   SenderThread:3042410 [sender.py:send():382] send: stats
2024-01-26 17:14:21,712 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:26,713 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:30,881 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:14:30,881 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:14:30,922 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:14:32,181 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:37,202 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:42,369 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:45,926 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:14:45,926 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:14:45,927 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:14:48,263 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:48,748 DEBUG   SenderThread:3042410 [sender.py:send():382] send: stats
2024-01-26 17:14:53,749 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:58,750 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:00,881 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:15:00,882 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:15:00,922 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:15:04,194 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:09,214 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:09,214 DEBUG   SenderThread:3042410 [sender.py:send():382] send: exit
2024-01-26 17:15:09,214 INFO    SenderThread:3042410 [sender.py:send_exit():589] handling exit code: 1
2024-01-26 17:15:09,214 INFO    SenderThread:3042410 [sender.py:send_exit():591] handling runtime: 380
2024-01-26 17:15:09,215 INFO    SenderThread:3042410 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-01-26 17:15:09,215 INFO    SenderThread:3042410 [sender.py:send_exit():597] send defer
2024-01-26 17:15:09,215 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:09,215 INFO    HandlerThread:3042410 [handler.py:handle_request_defer():172] handle defer: 0
2024-01-26 17:15:09,215 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:09,215 INFO    SenderThread:3042410 [sender.py:send_request_defer():613] handle sender defer: 0
2024-01-26 17:15:09,216 INFO    SenderThread:3042410 [sender.py:transition_state():617] send defer: 1
2024-01-26 17:15:09,216 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:09,216 INFO    HandlerThread:3042410 [handler.py:handle_request_defer():172] handle defer: 1
2024-01-26 17:15:09,216 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:09,216 INFO    SenderThread:3042410 [sender.py:send_request_defer():613] handle sender defer: 1
2024-01-26 17:15:09,216 INFO    SenderThread:3042410 [sender.py:transition_state():617] send defer: 2
2024-01-26 17:15:09,216 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:09,216 INFO    HandlerThread:3042410 [handler.py:handle_request_defer():172] handle defer: 2
2024-01-26 17:15:09,216 INFO    HandlerThread:3042410 [system_monitor.py:finish():203] Stopping system monitor
2024-01-26 17:15:09,216 DEBUG   SystemMonitor:3042410 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-01-26 17:15:09,216 DEBUG   SystemMonitor:3042410 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-01-26 17:15:09,230 INFO    HandlerThread:3042410 [interfaces.py:finish():202] Joined cpu monitor
2024-01-26 17:15:09,230 INFO    HandlerThread:3042410 [interfaces.py:finish():202] Joined disk monitor
2024-01-26 17:15:09,732 INFO    Thread-12 :3042410 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/files/wandb-summary.json
2024-01-26 17:15:11,732 INFO    Thread-12 :3042410 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/files/output.log
2024-01-26 17:15:27,683 INFO    HandlerThread:3042410 [interfaces.py:finish():202] Joined gpu monitor
2024-01-26 17:15:27,684 INFO    HandlerThread:3042410 [interfaces.py:finish():202] Joined memory monitor
2024-01-26 17:15:27,684 INFO    HandlerThread:3042410 [interfaces.py:finish():202] Joined network monitor
2024-01-26 17:15:27,684 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:15:27,684 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:27,684 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:27,684 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:27,684 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:27,684 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:27,684 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:27,685 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:27,685 INFO    SenderThread:3042410 [sender.py:send_request_defer():613] handle sender defer: 2
2024-01-26 17:15:27,686 INFO    SenderThread:3042410 [sender.py:transition_state():617] send defer: 3
2024-01-26 17:15:27,686 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:27,686 INFO    HandlerThread:3042410 [handler.py:handle_request_defer():172] handle defer: 3
2024-01-26 17:15:27,686 DEBUG   SenderThread:3042410 [sender.py:send():382] send: stats
2024-01-26 17:15:27,687 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:15:27,688 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:27,688 INFO    SenderThread:3042410 [sender.py:send_request_defer():613] handle sender defer: 3
2024-01-26 17:15:27,688 INFO    SenderThread:3042410 [sender.py:transition_state():617] send defer: 4
2024-01-26 17:15:27,690 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:27,691 INFO    HandlerThread:3042410 [handler.py:handle_request_defer():172] handle defer: 4
2024-01-26 17:15:27,691 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:27,691 INFO    SenderThread:3042410 [sender.py:send_request_defer():613] handle sender defer: 4
2024-01-26 17:15:27,691 INFO    SenderThread:3042410 [sender.py:transition_state():617] send defer: 5
2024-01-26 17:15:27,691 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:27,691 INFO    HandlerThread:3042410 [handler.py:handle_request_defer():172] handle defer: 5
2024-01-26 17:15:27,691 DEBUG   SenderThread:3042410 [sender.py:send():382] send: summary
2024-01-26 17:15:27,691 INFO    SenderThread:3042410 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-01-26 17:15:27,692 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:27,692 INFO    SenderThread:3042410 [sender.py:send_request_defer():613] handle sender defer: 5
2024-01-26 17:15:27,692 INFO    SenderThread:3042410 [sender.py:transition_state():617] send defer: 6
2024-01-26 17:15:27,692 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:27,692 INFO    HandlerThread:3042410 [handler.py:handle_request_defer():172] handle defer: 6
2024-01-26 17:15:27,692 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:27,692 INFO    SenderThread:3042410 [sender.py:send_request_defer():613] handle sender defer: 6
2024-01-26 17:15:27,692 INFO    SenderThread:3042410 [sender.py:transition_state():617] send defer: 7
2024-01-26 17:15:27,692 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:27,692 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:27,692 INFO    HandlerThread:3042410 [handler.py:handle_request_defer():172] handle defer: 7
2024-01-26 17:15:27,693 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:27,693 INFO    SenderThread:3042410 [sender.py:send_request_defer():613] handle sender defer: 7
2024-01-26 17:15:27,826 INFO    Thread-12 :3042410 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/files/wandb-summary.json
2024-01-26 17:15:28,300 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:15:29,059 INFO    SenderThread:3042410 [sender.py:transition_state():617] send defer: 8
2024-01-26 17:15:29,059 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:15:29,059 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:29,059 INFO    HandlerThread:3042410 [handler.py:handle_request_defer():172] handle defer: 8
2024-01-26 17:15:29,059 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:29,059 INFO    SenderThread:3042410 [sender.py:send_request_defer():613] handle sender defer: 8
2024-01-26 17:15:29,059 INFO    SenderThread:3042410 [job_builder.py:build():296] Attempting to build job artifact
2024-01-26 17:15:29,060 INFO    SenderThread:3042410 [job_builder.py:_get_source_type():426] is repo sourced job
2024-01-26 17:15:29,262 INFO    SenderThread:3042410 [job_builder.py:build():402] adding wandb-job metadata file
2024-01-26 17:15:29,268 INFO    SenderThread:3042410 [sender.py:transition_state():617] send defer: 9
2024-01-26 17:15:29,269 DEBUG   SenderThread:3042410 [sender.py:send():382] send: artifact
2024-01-26 17:15:29,269 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:29,272 INFO    HandlerThread:3042410 [handler.py:handle_request_defer():172] handle defer: 9
2024-01-26 17:15:29,299 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:15:29,827 INFO    Thread-12 :3042410 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/files/output.log
2024-01-26 17:15:31,375 ERROR   wandb-upload_1:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789539/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZCk12f1cM38XvMX6vQcAhFkIcZ1w7slY8En3ZcbLKIy9Y2oU4rUR0xUTzTXRDn64IZRLyf486r59Pyk908VHQsLuK5XqoZkao9ZVA6AfvKfd73wKi%2F00NGlAB9YxfRWvFSyQktRilS49mgBb3GVrz8CTIoWXDMHUkfrKWDFLAjBkj%2BE1t8yWJj5txr9lbB2D7LropUXvqOQ1HyyLYQ5LVbaPpYZ6Nf1I2AnVEkRv%2BaKWGoIId8eC4xAhlHaq679g4OC3TkyMhoohIrxcAv7XUmjkAz9eHblSV3N%2BAYty%2FqttqHgZEB3w1yM%2FVQ70xQ0%2FrQqQK5tLOWAj2sWRy7hkKQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789539/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZCk12f1cM38XvMX6vQcAhFkIcZ1w7slY8En3ZcbLKIy9Y2oU4rUR0xUTzTXRDn64IZRLyf486r59Pyk908VHQsLuK5XqoZkao9ZVA6AfvKfd73wKi%2F00NGlAB9YxfRWvFSyQktRilS49mgBb3GVrz8CTIoWXDMHUkfrKWDFLAjBkj%2BE1t8yWJj5txr9lbB2D7LropUXvqOQ1HyyLYQ5LVbaPpYZ6Nf1I2AnVEkRv%2BaKWGoIId8eC4xAhlHaq679g4OC3TkyMhoohIrxcAv7XUmjkAz9eHblSV3N%2BAYty%2FqttqHgZEB3w1yM%2FVQ70xQ0%2FrQqQK5tLOWAj2sWRy7hkKQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f600056a0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:31,375 ERROR   wandb-upload_1:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:31,375 ERROR   wandb-upload_1:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:31,376 ERROR   wandb-upload_2:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789539/6873c23a2381d1524249eb1a948a45a5?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZgU0pkB0fHglh%2FauBL5PbcNRqJwS6ME5RhGtUzDRy1R6imXUg1o8hRNXrg7vCrtTIZlreTNTH8GZVgi6UMPv9xdpjMUqF2b4HWfVNZOXUc6rDQP2%2BFogutx%2FF9Go2Jcx%2FAWy6lJTmfBdbr5KDCaO1QvczvYB0UbGmyaAOzPhWEu1Bw8vOyTSr1xb0z%2Bb%2FHBpgL%2F034xsMTynUIxDI1m0FKzu9v9lSNsz37NWcJcoS4%2BUfAH7eEkfQY80u5L3xnpYXTiafbcOmPZ5pJmTw5to6ySjUBm8RA75g5KnKcUa4A4hXpMenYTLZaPGR9Q6Ae2hFxq1Ld5GJ5OMeu136MOOCg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789539/6873c23a2381d1524249eb1a948a45a5?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZgU0pkB0fHglh%2FauBL5PbcNRqJwS6ME5RhGtUzDRy1R6imXUg1o8hRNXrg7vCrtTIZlreTNTH8GZVgi6UMPv9xdpjMUqF2b4HWfVNZOXUc6rDQP2%2BFogutx%2FF9Go2Jcx%2FAWy6lJTmfBdbr5KDCaO1QvczvYB0UbGmyaAOzPhWEu1Bw8vOyTSr1xb0z%2Bb%2FHBpgL%2F034xsMTynUIxDI1m0FKzu9v9lSNsz37NWcJcoS4%2BUfAH7eEkfQY80u5L3xnpYXTiafbcOmPZ5pJmTw5to6ySjUBm8RA75g5KnKcUa4A4hXpMenYTLZaPGR9Q6Ae2hFxq1Ld5GJ5OMeu136MOOCg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f600056ab80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:31,376 ERROR   wandb-upload_2:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:31,376 ERROR   wandb-upload_2:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:32,408 ERROR   wandb-upload_2:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789539/6873c23a2381d1524249eb1a948a45a5?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZgU0pkB0fHglh%2FauBL5PbcNRqJwS6ME5RhGtUzDRy1R6imXUg1o8hRNXrg7vCrtTIZlreTNTH8GZVgi6UMPv9xdpjMUqF2b4HWfVNZOXUc6rDQP2%2BFogutx%2FF9Go2Jcx%2FAWy6lJTmfBdbr5KDCaO1QvczvYB0UbGmyaAOzPhWEu1Bw8vOyTSr1xb0z%2Bb%2FHBpgL%2F034xsMTynUIxDI1m0FKzu9v9lSNsz37NWcJcoS4%2BUfAH7eEkfQY80u5L3xnpYXTiafbcOmPZ5pJmTw5to6ySjUBm8RA75g5KnKcUa4A4hXpMenYTLZaPGR9Q6Ae2hFxq1Ld5GJ5OMeu136MOOCg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789539/6873c23a2381d1524249eb1a948a45a5?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZgU0pkB0fHglh%2FauBL5PbcNRqJwS6ME5RhGtUzDRy1R6imXUg1o8hRNXrg7vCrtTIZlreTNTH8GZVgi6UMPv9xdpjMUqF2b4HWfVNZOXUc6rDQP2%2BFogutx%2FF9Go2Jcx%2FAWy6lJTmfBdbr5KDCaO1QvczvYB0UbGmyaAOzPhWEu1Bw8vOyTSr1xb0z%2Bb%2FHBpgL%2F034xsMTynUIxDI1m0FKzu9v9lSNsz37NWcJcoS4%2BUfAH7eEkfQY80u5L3xnpYXTiafbcOmPZ5pJmTw5to6ySjUBm8RA75g5KnKcUa4A4hXpMenYTLZaPGR9Q6Ae2hFxq1Ld5GJ5OMeu136MOOCg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f600037f4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:32,408 ERROR   wandb-upload_2:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:32,408 ERROR   wandb-upload_2:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:32,522 ERROR   wandb-upload_1:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789539/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZCk12f1cM38XvMX6vQcAhFkIcZ1w7slY8En3ZcbLKIy9Y2oU4rUR0xUTzTXRDn64IZRLyf486r59Pyk908VHQsLuK5XqoZkao9ZVA6AfvKfd73wKi%2F00NGlAB9YxfRWvFSyQktRilS49mgBb3GVrz8CTIoWXDMHUkfrKWDFLAjBkj%2BE1t8yWJj5txr9lbB2D7LropUXvqOQ1HyyLYQ5LVbaPpYZ6Nf1I2AnVEkRv%2BaKWGoIId8eC4xAhlHaq679g4OC3TkyMhoohIrxcAv7XUmjkAz9eHblSV3N%2BAYty%2FqttqHgZEB3w1yM%2FVQ70xQ0%2FrQqQK5tLOWAj2sWRy7hkKQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789539/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZCk12f1cM38XvMX6vQcAhFkIcZ1w7slY8En3ZcbLKIy9Y2oU4rUR0xUTzTXRDn64IZRLyf486r59Pyk908VHQsLuK5XqoZkao9ZVA6AfvKfd73wKi%2F00NGlAB9YxfRWvFSyQktRilS49mgBb3GVrz8CTIoWXDMHUkfrKWDFLAjBkj%2BE1t8yWJj5txr9lbB2D7LropUXvqOQ1HyyLYQ5LVbaPpYZ6Nf1I2AnVEkRv%2BaKWGoIId8eC4xAhlHaq679g4OC3TkyMhoohIrxcAv7XUmjkAz9eHblSV3N%2BAYty%2FqttqHgZEB3w1yM%2FVQ70xQ0%2FrQqQK5tLOWAj2sWRy7hkKQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6000529820>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:32,522 ERROR   wandb-upload_1:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:32,522 ERROR   wandb-upload_1:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:32,522 INFO    wandb-upload_1:3042410 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f6000529820>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789539/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZCk12f1cM38XvMX6vQcAhFkIcZ1w7slY8En3ZcbLKIy9Y2oU4rUR0xUTzTXRDn64IZRLyf486r59Pyk908VHQsLuK5XqoZkao9ZVA6AfvKfd73wKi%2F00NGlAB9YxfRWvFSyQktRilS49mgBb3GVrz8CTIoWXDMHUkfrKWDFLAjBkj%2BE1t8yWJj5txr9lbB2D7LropUXvqOQ1HyyLYQ5LVbaPpYZ6Nf1I2AnVEkRv%2BaKWGoIId8eC4xAhlHaq679g4OC3TkyMhoohIrxcAv7XUmjkAz9eHblSV3N%2BAYty%2FqttqHgZEB3w1yM%2FVQ70xQ0%2FrQqQK5tLOWAj2sWRy7hkKQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6000529820>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789539/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZCk12f1cM38XvMX6vQcAhFkIcZ1w7slY8En3ZcbLKIy9Y2oU4rUR0xUTzTXRDn64IZRLyf486r59Pyk908VHQsLuK5XqoZkao9ZVA6AfvKfd73wKi%2F00NGlAB9YxfRWvFSyQktRilS49mgBb3GVrz8CTIoWXDMHUkfrKWDFLAjBkj%2BE1t8yWJj5txr9lbB2D7LropUXvqOQ1HyyLYQ5LVbaPpYZ6Nf1I2AnVEkRv%2BaKWGoIId8eC4xAhlHaq679g4OC3TkyMhoohIrxcAv7XUmjkAz9eHblSV3N%2BAYty%2FqttqHgZEB3w1yM%2FVQ70xQ0%2FrQqQK5tLOWAj2sWRy7hkKQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6000529820>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2789, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-01-26 17:15:34,301 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:34,565 ERROR   wandb-upload_2:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789539/6873c23a2381d1524249eb1a948a45a5?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZgU0pkB0fHglh%2FauBL5PbcNRqJwS6ME5RhGtUzDRy1R6imXUg1o8hRNXrg7vCrtTIZlreTNTH8GZVgi6UMPv9xdpjMUqF2b4HWfVNZOXUc6rDQP2%2BFogutx%2FF9Go2Jcx%2FAWy6lJTmfBdbr5KDCaO1QvczvYB0UbGmyaAOzPhWEu1Bw8vOyTSr1xb0z%2Bb%2FHBpgL%2F034xsMTynUIxDI1m0FKzu9v9lSNsz37NWcJcoS4%2BUfAH7eEkfQY80u5L3xnpYXTiafbcOmPZ5pJmTw5to6ySjUBm8RA75g5KnKcUa4A4hXpMenYTLZaPGR9Q6Ae2hFxq1Ld5GJ5OMeu136MOOCg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789539/6873c23a2381d1524249eb1a948a45a5?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZgU0pkB0fHglh%2FauBL5PbcNRqJwS6ME5RhGtUzDRy1R6imXUg1o8hRNXrg7vCrtTIZlreTNTH8GZVgi6UMPv9xdpjMUqF2b4HWfVNZOXUc6rDQP2%2BFogutx%2FF9Go2Jcx%2FAWy6lJTmfBdbr5KDCaO1QvczvYB0UbGmyaAOzPhWEu1Bw8vOyTSr1xb0z%2Bb%2FHBpgL%2F034xsMTynUIxDI1m0FKzu9v9lSNsz37NWcJcoS4%2BUfAH7eEkfQY80u5L3xnpYXTiafbcOmPZ5pJmTw5to6ySjUBm8RA75g5KnKcUa4A4hXpMenYTLZaPGR9Q6Ae2hFxq1Ld5GJ5OMeu136MOOCg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6000384400>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:34,565 ERROR   wandb-upload_2:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:34,565 ERROR   wandb-upload_2:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:34,653 ERROR   wandb-upload_1:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789539/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZCk12f1cM38XvMX6vQcAhFkIcZ1w7slY8En3ZcbLKIy9Y2oU4rUR0xUTzTXRDn64IZRLyf486r59Pyk908VHQsLuK5XqoZkao9ZVA6AfvKfd73wKi%2F00NGlAB9YxfRWvFSyQktRilS49mgBb3GVrz8CTIoWXDMHUkfrKWDFLAjBkj%2BE1t8yWJj5txr9lbB2D7LropUXvqOQ1HyyLYQ5LVbaPpYZ6Nf1I2AnVEkRv%2BaKWGoIId8eC4xAhlHaq679g4OC3TkyMhoohIrxcAv7XUmjkAz9eHblSV3N%2BAYty%2FqttqHgZEB3w1yM%2FVQ70xQ0%2FrQqQK5tLOWAj2sWRy7hkKQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789539/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZCk12f1cM38XvMX6vQcAhFkIcZ1w7slY8En3ZcbLKIy9Y2oU4rUR0xUTzTXRDn64IZRLyf486r59Pyk908VHQsLuK5XqoZkao9ZVA6AfvKfd73wKi%2F00NGlAB9YxfRWvFSyQktRilS49mgBb3GVrz8CTIoWXDMHUkfrKWDFLAjBkj%2BE1t8yWJj5txr9lbB2D7LropUXvqOQ1HyyLYQ5LVbaPpYZ6Nf1I2AnVEkRv%2BaKWGoIId8eC4xAhlHaq679g4OC3TkyMhoohIrxcAv7XUmjkAz9eHblSV3N%2BAYty%2FqttqHgZEB3w1yM%2FVQ70xQ0%2FrQqQK5tLOWAj2sWRy7hkKQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f600037f640>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:34,653 ERROR   wandb-upload_1:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:34,654 ERROR   wandb-upload_1:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:38,703 ERROR   wandb-upload_1:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789539/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZCk12f1cM38XvMX6vQcAhFkIcZ1w7slY8En3ZcbLKIy9Y2oU4rUR0xUTzTXRDn64IZRLyf486r59Pyk908VHQsLuK5XqoZkao9ZVA6AfvKfd73wKi%2F00NGlAB9YxfRWvFSyQktRilS49mgBb3GVrz8CTIoWXDMHUkfrKWDFLAjBkj%2BE1t8yWJj5txr9lbB2D7LropUXvqOQ1HyyLYQ5LVbaPpYZ6Nf1I2AnVEkRv%2BaKWGoIId8eC4xAhlHaq679g4OC3TkyMhoohIrxcAv7XUmjkAz9eHblSV3N%2BAYty%2FqttqHgZEB3w1yM%2FVQ70xQ0%2FrQqQK5tLOWAj2sWRy7hkKQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789539/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZCk12f1cM38XvMX6vQcAhFkIcZ1w7slY8En3ZcbLKIy9Y2oU4rUR0xUTzTXRDn64IZRLyf486r59Pyk908VHQsLuK5XqoZkao9ZVA6AfvKfd73wKi%2F00NGlAB9YxfRWvFSyQktRilS49mgBb3GVrz8CTIoWXDMHUkfrKWDFLAjBkj%2BE1t8yWJj5txr9lbB2D7LropUXvqOQ1HyyLYQ5LVbaPpYZ6Nf1I2AnVEkRv%2BaKWGoIId8eC4xAhlHaq679g4OC3TkyMhoohIrxcAv7XUmjkAz9eHblSV3N%2BAYty%2FqttqHgZEB3w1yM%2FVQ70xQ0%2FrQqQK5tLOWAj2sWRy7hkKQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6000529fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:38,703 ERROR   wandb-upload_1:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:38,703 ERROR   wandb-upload_1:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:38,998 ERROR   wandb-upload_2:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789539/6873c23a2381d1524249eb1a948a45a5?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZgU0pkB0fHglh%2FauBL5PbcNRqJwS6ME5RhGtUzDRy1R6imXUg1o8hRNXrg7vCrtTIZlreTNTH8GZVgi6UMPv9xdpjMUqF2b4HWfVNZOXUc6rDQP2%2BFogutx%2FF9Go2Jcx%2FAWy6lJTmfBdbr5KDCaO1QvczvYB0UbGmyaAOzPhWEu1Bw8vOyTSr1xb0z%2Bb%2FHBpgL%2F034xsMTynUIxDI1m0FKzu9v9lSNsz37NWcJcoS4%2BUfAH7eEkfQY80u5L3xnpYXTiafbcOmPZ5pJmTw5to6ySjUBm8RA75g5KnKcUa4A4hXpMenYTLZaPGR9Q6Ae2hFxq1Ld5GJ5OMeu136MOOCg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789539/6873c23a2381d1524249eb1a948a45a5?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZgU0pkB0fHglh%2FauBL5PbcNRqJwS6ME5RhGtUzDRy1R6imXUg1o8hRNXrg7vCrtTIZlreTNTH8GZVgi6UMPv9xdpjMUqF2b4HWfVNZOXUc6rDQP2%2BFogutx%2FF9Go2Jcx%2FAWy6lJTmfBdbr5KDCaO1QvczvYB0UbGmyaAOzPhWEu1Bw8vOyTSr1xb0z%2Bb%2FHBpgL%2F034xsMTynUIxDI1m0FKzu9v9lSNsz37NWcJcoS4%2BUfAH7eEkfQY80u5L3xnpYXTiafbcOmPZ5pJmTw5to6ySjUBm8RA75g5KnKcUa4A4hXpMenYTLZaPGR9Q6Ae2hFxq1Ld5GJ5OMeu136MOOCg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f600056a760>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:38,998 ERROR   wandb-upload_2:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:38,998 ERROR   wandb-upload_2:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:39,302 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:44,304 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:47,062 ERROR   wandb-upload_2:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789539/6873c23a2381d1524249eb1a948a45a5?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZgU0pkB0fHglh%2FauBL5PbcNRqJwS6ME5RhGtUzDRy1R6imXUg1o8hRNXrg7vCrtTIZlreTNTH8GZVgi6UMPv9xdpjMUqF2b4HWfVNZOXUc6rDQP2%2BFogutx%2FF9Go2Jcx%2FAWy6lJTmfBdbr5KDCaO1QvczvYB0UbGmyaAOzPhWEu1Bw8vOyTSr1xb0z%2Bb%2FHBpgL%2F034xsMTynUIxDI1m0FKzu9v9lSNsz37NWcJcoS4%2BUfAH7eEkfQY80u5L3xnpYXTiafbcOmPZ5pJmTw5to6ySjUBm8RA75g5KnKcUa4A4hXpMenYTLZaPGR9Q6Ae2hFxq1Ld5GJ5OMeu136MOOCg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789539/6873c23a2381d1524249eb1a948a45a5?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZgU0pkB0fHglh%2FauBL5PbcNRqJwS6ME5RhGtUzDRy1R6imXUg1o8hRNXrg7vCrtTIZlreTNTH8GZVgi6UMPv9xdpjMUqF2b4HWfVNZOXUc6rDQP2%2BFogutx%2FF9Go2Jcx%2FAWy6lJTmfBdbr5KDCaO1QvczvYB0UbGmyaAOzPhWEu1Bw8vOyTSr1xb0z%2Bb%2FHBpgL%2F034xsMTynUIxDI1m0FKzu9v9lSNsz37NWcJcoS4%2BUfAH7eEkfQY80u5L3xnpYXTiafbcOmPZ5pJmTw5to6ySjUBm8RA75g5KnKcUa4A4hXpMenYTLZaPGR9Q6Ae2hFxq1Ld5GJ5OMeu136MOOCg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f60003842e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:47,062 ERROR   wandb-upload_2:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:47,062 ERROR   wandb-upload_2:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:47,835 ERROR   wandb-upload_1:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789539/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZCk12f1cM38XvMX6vQcAhFkIcZ1w7slY8En3ZcbLKIy9Y2oU4rUR0xUTzTXRDn64IZRLyf486r59Pyk908VHQsLuK5XqoZkao9ZVA6AfvKfd73wKi%2F00NGlAB9YxfRWvFSyQktRilS49mgBb3GVrz8CTIoWXDMHUkfrKWDFLAjBkj%2BE1t8yWJj5txr9lbB2D7LropUXvqOQ1HyyLYQ5LVbaPpYZ6Nf1I2AnVEkRv%2BaKWGoIId8eC4xAhlHaq679g4OC3TkyMhoohIrxcAv7XUmjkAz9eHblSV3N%2BAYty%2FqttqHgZEB3w1yM%2FVQ70xQ0%2FrQqQK5tLOWAj2sWRy7hkKQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789539/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZCk12f1cM38XvMX6vQcAhFkIcZ1w7slY8En3ZcbLKIy9Y2oU4rUR0xUTzTXRDn64IZRLyf486r59Pyk908VHQsLuK5XqoZkao9ZVA6AfvKfd73wKi%2F00NGlAB9YxfRWvFSyQktRilS49mgBb3GVrz8CTIoWXDMHUkfrKWDFLAjBkj%2BE1t8yWJj5txr9lbB2D7LropUXvqOQ1HyyLYQ5LVbaPpYZ6Nf1I2AnVEkRv%2BaKWGoIId8eC4xAhlHaq679g4OC3TkyMhoohIrxcAv7XUmjkAz9eHblSV3N%2BAYty%2FqttqHgZEB3w1yM%2FVQ70xQ0%2FrQqQK5tLOWAj2sWRy7hkKQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6000384fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:47,836 ERROR   wandb-upload_1:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:47,836 ERROR   wandb-upload_1:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:49,306 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:54,308 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:59,310 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:04,312 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:05,997 ERROR   wandb-upload_2:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789539/6873c23a2381d1524249eb1a948a45a5?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZgU0pkB0fHglh%2FauBL5PbcNRqJwS6ME5RhGtUzDRy1R6imXUg1o8hRNXrg7vCrtTIZlreTNTH8GZVgi6UMPv9xdpjMUqF2b4HWfVNZOXUc6rDQP2%2BFogutx%2FF9Go2Jcx%2FAWy6lJTmfBdbr5KDCaO1QvczvYB0UbGmyaAOzPhWEu1Bw8vOyTSr1xb0z%2Bb%2FHBpgL%2F034xsMTynUIxDI1m0FKzu9v9lSNsz37NWcJcoS4%2BUfAH7eEkfQY80u5L3xnpYXTiafbcOmPZ5pJmTw5to6ySjUBm8RA75g5KnKcUa4A4hXpMenYTLZaPGR9Q6Ae2hFxq1Ld5GJ5OMeu136MOOCg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789539/6873c23a2381d1524249eb1a948a45a5?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZgU0pkB0fHglh%2FauBL5PbcNRqJwS6ME5RhGtUzDRy1R6imXUg1o8hRNXrg7vCrtTIZlreTNTH8GZVgi6UMPv9xdpjMUqF2b4HWfVNZOXUc6rDQP2%2BFogutx%2FF9Go2Jcx%2FAWy6lJTmfBdbr5KDCaO1QvczvYB0UbGmyaAOzPhWEu1Bw8vOyTSr1xb0z%2Bb%2FHBpgL%2F034xsMTynUIxDI1m0FKzu9v9lSNsz37NWcJcoS4%2BUfAH7eEkfQY80u5L3xnpYXTiafbcOmPZ5pJmTw5to6ySjUBm8RA75g5KnKcUa4A4hXpMenYTLZaPGR9Q6Ae2hFxq1Ld5GJ5OMeu136MOOCg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6000368190>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:16:05,997 ERROR   wandb-upload_2:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:16:05,997 ERROR   wandb-upload_2:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:06,965 ERROR   wandb-upload_1:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789539/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZCk12f1cM38XvMX6vQcAhFkIcZ1w7slY8En3ZcbLKIy9Y2oU4rUR0xUTzTXRDn64IZRLyf486r59Pyk908VHQsLuK5XqoZkao9ZVA6AfvKfd73wKi%2F00NGlAB9YxfRWvFSyQktRilS49mgBb3GVrz8CTIoWXDMHUkfrKWDFLAjBkj%2BE1t8yWJj5txr9lbB2D7LropUXvqOQ1HyyLYQ5LVbaPpYZ6Nf1I2AnVEkRv%2BaKWGoIId8eC4xAhlHaq679g4OC3TkyMhoohIrxcAv7XUmjkAz9eHblSV3N%2BAYty%2FqttqHgZEB3w1yM%2FVQ70xQ0%2FrQqQK5tLOWAj2sWRy7hkKQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789539/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZCk12f1cM38XvMX6vQcAhFkIcZ1w7slY8En3ZcbLKIy9Y2oU4rUR0xUTzTXRDn64IZRLyf486r59Pyk908VHQsLuK5XqoZkao9ZVA6AfvKfd73wKi%2F00NGlAB9YxfRWvFSyQktRilS49mgBb3GVrz8CTIoWXDMHUkfrKWDFLAjBkj%2BE1t8yWJj5txr9lbB2D7LropUXvqOQ1HyyLYQ5LVbaPpYZ6Nf1I2AnVEkRv%2BaKWGoIId8eC4xAhlHaq679g4OC3TkyMhoohIrxcAv7XUmjkAz9eHblSV3N%2BAYty%2FqttqHgZEB3w1yM%2FVQ70xQ0%2FrQqQK5tLOWAj2sWRy7hkKQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f60003680d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:16:06,965 ERROR   wandb-upload_1:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:16:06,965 ERROR   wandb-upload_1:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:09,314 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:14,316 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:19,318 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:24,321 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:29,322 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:34,325 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:39,327 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:41,258 ERROR   wandb-upload_1:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789539/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZCk12f1cM38XvMX6vQcAhFkIcZ1w7slY8En3ZcbLKIy9Y2oU4rUR0xUTzTXRDn64IZRLyf486r59Pyk908VHQsLuK5XqoZkao9ZVA6AfvKfd73wKi%2F00NGlAB9YxfRWvFSyQktRilS49mgBb3GVrz8CTIoWXDMHUkfrKWDFLAjBkj%2BE1t8yWJj5txr9lbB2D7LropUXvqOQ1HyyLYQ5LVbaPpYZ6Nf1I2AnVEkRv%2BaKWGoIId8eC4xAhlHaq679g4OC3TkyMhoohIrxcAv7XUmjkAz9eHblSV3N%2BAYty%2FqttqHgZEB3w1yM%2FVQ70xQ0%2FrQqQK5tLOWAj2sWRy7hkKQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789539/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZCk12f1cM38XvMX6vQcAhFkIcZ1w7slY8En3ZcbLKIy9Y2oU4rUR0xUTzTXRDn64IZRLyf486r59Pyk908VHQsLuK5XqoZkao9ZVA6AfvKfd73wKi%2F00NGlAB9YxfRWvFSyQktRilS49mgBb3GVrz8CTIoWXDMHUkfrKWDFLAjBkj%2BE1t8yWJj5txr9lbB2D7LropUXvqOQ1HyyLYQ5LVbaPpYZ6Nf1I2AnVEkRv%2BaKWGoIId8eC4xAhlHaq679g4OC3TkyMhoohIrxcAv7XUmjkAz9eHblSV3N%2BAYty%2FqttqHgZEB3w1yM%2FVQ70xQ0%2FrQqQK5tLOWAj2sWRy7hkKQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f600036a250>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:16:41,258 ERROR   wandb-upload_1:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:16:41,258 ERROR   wandb-upload_1:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:42,695 ERROR   wandb-upload_2:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789539/6873c23a2381d1524249eb1a948a45a5?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZgU0pkB0fHglh%2FauBL5PbcNRqJwS6ME5RhGtUzDRy1R6imXUg1o8hRNXrg7vCrtTIZlreTNTH8GZVgi6UMPv9xdpjMUqF2b4HWfVNZOXUc6rDQP2%2BFogutx%2FF9Go2Jcx%2FAWy6lJTmfBdbr5KDCaO1QvczvYB0UbGmyaAOzPhWEu1Bw8vOyTSr1xb0z%2Bb%2FHBpgL%2F034xsMTynUIxDI1m0FKzu9v9lSNsz37NWcJcoS4%2BUfAH7eEkfQY80u5L3xnpYXTiafbcOmPZ5pJmTw5to6ySjUBm8RA75g5KnKcUa4A4hXpMenYTLZaPGR9Q6Ae2hFxq1Ld5GJ5OMeu136MOOCg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789539/6873c23a2381d1524249eb1a948a45a5?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZgU0pkB0fHglh%2FauBL5PbcNRqJwS6ME5RhGtUzDRy1R6imXUg1o8hRNXrg7vCrtTIZlreTNTH8GZVgi6UMPv9xdpjMUqF2b4HWfVNZOXUc6rDQP2%2BFogutx%2FF9Go2Jcx%2FAWy6lJTmfBdbr5KDCaO1QvczvYB0UbGmyaAOzPhWEu1Bw8vOyTSr1xb0z%2Bb%2FHBpgL%2F034xsMTynUIxDI1m0FKzu9v9lSNsz37NWcJcoS4%2BUfAH7eEkfQY80u5L3xnpYXTiafbcOmPZ5pJmTw5to6ySjUBm8RA75g5KnKcUa4A4hXpMenYTLZaPGR9Q6Ae2hFxq1Ld5GJ5OMeu136MOOCg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f600039e730>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:16:42,695 ERROR   wandb-upload_2:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:16:42,695 ERROR   wandb-upload_2:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:44,329 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:49,330 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:54,333 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:59,335 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:04,337 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:09,339 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:14,342 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:19,344 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:24,346 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:29,349 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:34,351 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:39,353 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:44,355 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:49,357 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:51,182 ERROR   wandb-upload_2:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789539/6873c23a2381d1524249eb1a948a45a5?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZgU0pkB0fHglh%2FauBL5PbcNRqJwS6ME5RhGtUzDRy1R6imXUg1o8hRNXrg7vCrtTIZlreTNTH8GZVgi6UMPv9xdpjMUqF2b4HWfVNZOXUc6rDQP2%2BFogutx%2FF9Go2Jcx%2FAWy6lJTmfBdbr5KDCaO1QvczvYB0UbGmyaAOzPhWEu1Bw8vOyTSr1xb0z%2Bb%2FHBpgL%2F034xsMTynUIxDI1m0FKzu9v9lSNsz37NWcJcoS4%2BUfAH7eEkfQY80u5L3xnpYXTiafbcOmPZ5pJmTw5to6ySjUBm8RA75g5KnKcUa4A4hXpMenYTLZaPGR9Q6Ae2hFxq1Ld5GJ5OMeu136MOOCg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789539/6873c23a2381d1524249eb1a948a45a5?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZgU0pkB0fHglh%2FauBL5PbcNRqJwS6ME5RhGtUzDRy1R6imXUg1o8hRNXrg7vCrtTIZlreTNTH8GZVgi6UMPv9xdpjMUqF2b4HWfVNZOXUc6rDQP2%2BFogutx%2FF9Go2Jcx%2FAWy6lJTmfBdbr5KDCaO1QvczvYB0UbGmyaAOzPhWEu1Bw8vOyTSr1xb0z%2Bb%2FHBpgL%2F034xsMTynUIxDI1m0FKzu9v9lSNsz37NWcJcoS4%2BUfAH7eEkfQY80u5L3xnpYXTiafbcOmPZ5pJmTw5to6ySjUBm8RA75g5KnKcUa4A4hXpMenYTLZaPGR9Q6Ae2hFxq1Ld5GJ5OMeu136MOOCg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f600035e2e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:17:51,183 ERROR   wandb-upload_2:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:17:51,183 ERROR   wandb-upload_2:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:17:54,359 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:55,124 ERROR   wandb-upload_1:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789539/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZCk12f1cM38XvMX6vQcAhFkIcZ1w7slY8En3ZcbLKIy9Y2oU4rUR0xUTzTXRDn64IZRLyf486r59Pyk908VHQsLuK5XqoZkao9ZVA6AfvKfd73wKi%2F00NGlAB9YxfRWvFSyQktRilS49mgBb3GVrz8CTIoWXDMHUkfrKWDFLAjBkj%2BE1t8yWJj5txr9lbB2D7LropUXvqOQ1HyyLYQ5LVbaPpYZ6Nf1I2AnVEkRv%2BaKWGoIId8eC4xAhlHaq679g4OC3TkyMhoohIrxcAv7XUmjkAz9eHblSV3N%2BAYty%2FqttqHgZEB3w1yM%2FVQ70xQ0%2FrQqQK5tLOWAj2sWRy7hkKQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789539/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346931&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZCk12f1cM38XvMX6vQcAhFkIcZ1w7slY8En3ZcbLKIy9Y2oU4rUR0xUTzTXRDn64IZRLyf486r59Pyk908VHQsLuK5XqoZkao9ZVA6AfvKfd73wKi%2F00NGlAB9YxfRWvFSyQktRilS49mgBb3GVrz8CTIoWXDMHUkfrKWDFLAjBkj%2BE1t8yWJj5txr9lbB2D7LropUXvqOQ1HyyLYQ5LVbaPpYZ6Nf1I2AnVEkRv%2BaKWGoIId8eC4xAhlHaq679g4OC3TkyMhoohIrxcAv7XUmjkAz9eHblSV3N%2BAYty%2FqttqHgZEB3w1yM%2FVQ70xQ0%2FrQqQK5tLOWAj2sWRy7hkKQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6000352670>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:17:55,125 ERROR   wandb-upload_1:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:17:55,125 ERROR   wandb-upload_1:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:17:59,361 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:04,364 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:09,366 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:14,368 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:19,371 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:24,373 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:29,374 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:34,377 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:39,379 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:42,510 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/oda2kyd2/wandb-metadata.json?Expires=1706346539&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rDnGTUPH6v9ro5qMAX8yPoUj0e0HvXUoAEEstrJL4vooRueZ%2BCvpICQYfceCargGw2sdsfKmygInUsNbr2gt%2BnSeS%2BGte35u23WF%2BOJxrjjoyqp8CzKilDkNFolktQ%2BkCW54vdtZP9aUwYQY2Y3SOutyvCuK9fmm4BQcpaTRAeL0778XsXha5xtW%2B4tlinbBSk4yFnLFWNuhOk4ZD1L7lR3tTK%2FnvuM8mDR6Vd7GGtbRMgcjQbWNDhIZ0OGil0bF1CSHmful1BLqjOV0edSqRETIy2PMgBiCJpS%2BBIVelyIEVFREMzL3cyy%2BDP9609JrW1Z9CrINmr7%2BHN83k9KUaw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/oda2kyd2/wandb-metadata.json?Expires=1706346539&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rDnGTUPH6v9ro5qMAX8yPoUj0e0HvXUoAEEstrJL4vooRueZ%2BCvpICQYfceCargGw2sdsfKmygInUsNbr2gt%2BnSeS%2BGte35u23WF%2BOJxrjjoyqp8CzKilDkNFolktQ%2BkCW54vdtZP9aUwYQY2Y3SOutyvCuK9fmm4BQcpaTRAeL0778XsXha5xtW%2B4tlinbBSk4yFnLFWNuhOk4ZD1L7lR3tTK%2FnvuM8mDR6Vd7GGtbRMgcjQbWNDhIZ0OGil0bF1CSHmful1BLqjOV0edSqRETIy2PMgBiCJpS%2BBIVelyIEVFREMzL3cyy%2BDP9609JrW1Z9CrINmr7%2BHN83k9KUaw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f600056a370>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:18:42,511 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15651'}
2024-01-26 17:18:42,511 ERROR   wandb-upload_0:3042410 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:18:44,381 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:49,383 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:54,386 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:59,388 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:04,391 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:09,393 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:14,395 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:19,397 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:24,399 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:29,402 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:34,403 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:39,405 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:44,407 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:49,410 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:54,412 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:59,414 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:04,263 INFO    wandb-upload_1:3042410 [upload_job.py:push():89] Uploaded file /home/yanxindong/.local/share/wandb/artifacts/staging/tmp3wy93opp
2024-01-26 17:20:04,418 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:09,419 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:14,421 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:19,424 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:24,426 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:27,687 INFO    wandb-upload_2:3042410 [upload_job.py:push():89] Uploaded file /home/yanxindong/.local/share/wandb/artifacts/staging/tmp7kvbqk44
2024-01-26 17:20:29,428 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:29,655 INFO    SenderThread:3042410 [sender.py:send_artifact():1494] sent artifact job-https___github.com_kkkjj-d_mkor.git_bert_run_pretraining.py - {'id': 'QXJ0aWZhY3Q6NzAzNzg5NTM5', 'state': 'PENDING', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjEzMzk4MTIwMA==', 'latestArtifact': None}}
2024-01-26 17:20:29,655 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: defer
2024-01-26 17:20:29,655 INFO    SenderThread:3042410 [sender.py:send_request_defer():613] handle sender defer: 9
2024-01-26 17:20:29,655 INFO    SenderThread:3042410 [dir_watcher.py:finish():358] shutting down directory watcher
2024-01-26 17:20:29,655 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:20:29,873 INFO    SenderThread:3042410 [dir_watcher.py:finish():388] scan: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/files
2024-01-26 17:20:29,873 INFO    SenderThread:3042410 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/files/wandb-summary.json wandb-summary.json
2024-01-26 17:20:29,873 INFO    SenderThread:3042410 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/files/conda-environment.yaml conda-environment.yaml
2024-01-26 17:20:29,876 INFO    SenderThread:3042410 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/files/wandb-metadata.json wandb-metadata.json
2024-01-26 17:20:29,877 INFO    SenderThread:3042410 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/files/output.log output.log
2024-01-26 17:20:29,877 INFO    SenderThread:3042410 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/files/requirements.txt requirements.txt
2024-01-26 17:20:29,879 INFO    SenderThread:3042410 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/files/config.yaml config.yaml
2024-01-26 17:20:29,879 INFO    SenderThread:3042410 [sender.py:transition_state():617] send defer: 10
2024-01-26 17:20:29,880 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:29,880 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:20:29,886 INFO    HandlerThread:3042410 [handler.py:handle_request_defer():172] handle defer: 10
2024-01-26 17:20:29,886 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: defer
2024-01-26 17:20:29,886 INFO    SenderThread:3042410 [sender.py:send_request_defer():613] handle sender defer: 10
2024-01-26 17:20:29,886 INFO    SenderThread:3042410 [file_pusher.py:finish():175] shutting down file pusher
2024-01-26 17:20:30,429 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:30,429 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:30,679 INFO    wandb-upload_1:3042410 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/files/wandb-summary.json
2024-01-26 17:20:31,049 INFO    wandb-upload_5:3042410 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/files/config.yaml
2024-01-26 17:20:31,435 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:31,435 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:31,655 INFO    wandb-upload_3:3042410 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/files/output.log
2024-01-26 17:20:31,657 INFO    wandb-upload_4:3042410 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/files/requirements.txt
2024-01-26 17:20:32,432 INFO    wandb-upload_2:3042410 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/files/conda-environment.yaml
2024-01-26 17:20:32,435 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:32,435 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:33,435 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:33,436 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:34,437 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:34,438 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:35,438 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:35,438 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:35,439 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:20:36,439 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:36,441 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:37,439 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:37,440 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:38,440 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:38,441 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:39,441 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:39,441 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:40,443 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:20:40,443 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:40,444 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:41,443 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:41,444 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:42,444 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:42,444 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:43,445 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:43,446 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:44,446 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:44,446 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:45,447 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:45,447 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:20:45,448 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:46,449 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:46,450 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:47,449 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:47,450 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:48,451 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:48,452 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:49,453 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:49,454 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:50,455 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:20:50,458 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:50,458 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:51,458 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:51,459 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:52,459 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:52,460 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:53,460 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:53,460 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:54,461 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:54,461 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:55,461 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:55,462 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:55,463 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:20:56,463 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:56,464 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:57,464 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:57,465 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:58,465 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:58,466 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:59,465 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:59,466 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:00,466 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:00,467 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:00,467 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:01,467 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:01,467 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:02,467 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:02,467 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:03,467 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:03,468 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:04,468 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:04,469 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:05,471 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:05,471 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:05,471 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:06,471 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:06,472 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:07,472 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:07,473 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:08,474 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:08,474 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:09,474 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:09,475 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:10,475 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:10,476 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:10,476 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:11,476 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:11,476 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:12,477 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:12,478 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:13,477 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:13,478 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:14,478 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:14,478 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:15,478 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:15,478 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:15,479 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:16,479 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:16,480 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:17,480 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:17,480 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:18,480 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:18,481 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:19,481 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:19,482 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:20,483 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:20,484 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:20,484 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:21,485 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:21,486 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:22,486 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:22,487 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:23,488 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:23,488 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:24,488 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:24,489 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:25,490 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:25,490 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:25,490 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:26,491 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:26,491 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:27,491 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:27,491 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:28,492 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:28,493 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:29,492 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:29,493 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:30,494 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:30,494 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:30,495 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:31,494 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:31,495 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:32,496 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:32,496 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:33,496 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:33,497 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:34,497 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:34,498 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:35,498 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:35,498 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:35,499 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:36,500 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:36,500 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:37,500 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:37,501 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:38,501 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:38,502 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:39,502 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:39,503 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:40,503 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:40,504 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:40,504 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:41,504 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:41,505 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:42,505 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:42,505 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:43,505 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:43,506 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:44,506 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:44,506 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:45,506 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:45,506 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:45,507 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:46,506 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:46,507 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:47,507 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:47,508 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:48,508 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:48,509 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:49,509 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:49,510 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:50,511 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:50,514 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:50,516 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:51,515 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:51,515 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:52,515 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:52,515 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:53,516 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:53,516 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:54,517 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:54,517 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:55,517 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:55,518 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:55,518 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:56,518 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:56,519 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:57,519 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:57,519 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:58,520 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:58,521 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:59,521 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:59,522 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:00,522 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:00,523 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:00,523 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:01,523 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:01,524 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:02,524 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:02,525 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:03,525 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:03,525 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:04,526 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:04,526 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:05,526 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:05,527 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:05,527 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:06,527 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:06,528 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:07,527 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:07,528 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:08,529 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:08,529 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:09,529 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:09,530 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:10,531 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:10,531 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:10,531 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:11,531 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:11,532 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:12,532 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:12,532 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:13,533 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:13,533 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:14,534 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:14,534 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:15,535 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:15,535 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:15,536 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:16,536 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:16,537 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:17,537 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:17,537 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:18,537 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:18,538 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:19,538 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:19,538 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:20,539 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:20,539 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:20,539 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:21,539 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:21,540 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:22,541 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:22,541 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:23,541 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:23,541 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:24,542 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:24,542 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:25,542 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:25,543 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:25,543 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:26,544 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:26,544 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:27,544 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:27,545 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:28,545 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:28,546 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:29,545 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:29,546 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:30,546 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:30,546 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:30,547 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:31,547 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:31,547 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:32,548 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:32,548 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:33,548 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:33,549 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:34,549 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:34,549 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:35,549 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:35,550 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:35,550 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:36,551 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:36,552 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:37,552 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:37,553 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:38,553 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:38,553 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:39,554 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:39,554 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:40,555 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:40,555 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:40,556 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:41,556 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:41,556 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:42,557 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:42,557 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:43,557 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:43,558 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:44,559 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:44,559 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:45,559 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:45,559 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:45,559 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:46,559 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:46,560 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:47,560 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:47,561 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:48,561 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:48,562 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:49,562 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:49,563 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:50,563 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:50,564 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:50,564 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:51,564 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:51,564 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:52,565 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:52,565 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:53,566 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:53,566 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:54,566 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:54,567 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:55,567 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:55,567 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:55,568 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:56,568 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:56,569 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:57,569 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:57,569 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:58,570 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:58,570 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:59,570 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:59,571 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:00,571 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:00,572 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:00,572 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:01,572 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:01,572 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:02,572 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:02,573 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:03,573 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:03,574 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:04,575 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:04,576 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:05,576 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:05,576 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:05,576 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:06,577 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:06,577 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:07,578 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:07,578 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:08,579 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:08,580 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:09,580 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:09,580 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:10,581 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:10,581 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:10,582 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:11,581 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:11,582 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:12,582 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:12,583 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:13,583 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:13,583 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:14,584 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:14,584 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:15,584 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:15,584 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:15,584 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:16,584 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:16,585 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:17,585 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:17,585 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:18,586 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:18,586 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:19,586 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:19,587 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:20,587 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:20,588 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:20,588 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:21,588 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:21,588 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:22,589 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:22,589 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:23,589 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:23,590 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:24,590 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:24,590 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:25,590 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:25,591 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:25,591 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:26,592 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:26,592 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:27,592 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:27,593 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:28,593 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:28,594 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:29,594 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:29,595 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:30,595 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:30,595 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:30,595 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:31,595 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:31,596 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:32,596 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:32,596 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:33,597 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:33,597 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:34,597 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:34,598 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:35,598 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:35,599 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:35,599 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:36,600 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:36,600 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:37,600 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:37,600 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:38,601 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:38,601 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:39,601 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:39,602 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:40,602 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:40,602 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:40,603 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:41,603 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:41,603 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:42,603 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:42,603 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:43,604 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:43,604 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:44,605 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:44,605 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:45,605 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:45,606 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:45,606 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:46,607 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:46,607 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:47,607 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:47,608 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:48,080 INFO    wandb-upload_0:3042410 [upload_job.py:push():131] Uploaded file /tmp/tmpy57ur4b7wandb/xtkj3ru2-wandb-metadata.json
2024-01-26 17:23:48,281 INFO    Thread-11 :3042410 [sender.py:transition_state():617] send defer: 11
2024-01-26 17:23:48,282 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:23:48,282 INFO    HandlerThread:3042410 [handler.py:handle_request_defer():172] handle defer: 11
2024-01-26 17:23:48,282 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: defer
2024-01-26 17:23:48,282 INFO    SenderThread:3042410 [sender.py:send_request_defer():613] handle sender defer: 11
2024-01-26 17:23:48,283 INFO    SenderThread:3042410 [file_pusher.py:join():181] waiting for file pusher
2024-01-26 17:23:48,283 INFO    SenderThread:3042410 [sender.py:transition_state():617] send defer: 12
2024-01-26 17:23:48,283 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:23:48,283 INFO    HandlerThread:3042410 [handler.py:handle_request_defer():172] handle defer: 12
2024-01-26 17:23:48,283 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: defer
2024-01-26 17:23:48,283 INFO    SenderThread:3042410 [sender.py:send_request_defer():613] handle sender defer: 12
2024-01-26 17:23:48,284 INFO    SenderThread:3042410 [file_stream.py:finish():595] file stream finish called
2024-01-26 17:23:48,555 INFO    SenderThread:3042410 [file_stream.py:finish():599] file stream finish is done
2024-01-26 17:23:48,555 INFO    SenderThread:3042410 [sender.py:transition_state():617] send defer: 13
2024-01-26 17:23:48,555 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:23:48,555 INFO    HandlerThread:3042410 [handler.py:handle_request_defer():172] handle defer: 13
2024-01-26 17:23:48,556 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: defer
2024-01-26 17:23:48,556 INFO    SenderThread:3042410 [sender.py:send_request_defer():613] handle sender defer: 13
2024-01-26 17:23:48,556 INFO    SenderThread:3042410 [sender.py:transition_state():617] send defer: 14
2024-01-26 17:23:48,556 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:23:48,557 INFO    HandlerThread:3042410 [handler.py:handle_request_defer():172] handle defer: 14
2024-01-26 17:23:48,557 DEBUG   SenderThread:3042410 [sender.py:send():382] send: final
2024-01-26 17:23:48,557 DEBUG   SenderThread:3042410 [sender.py:send():382] send: footer
2024-01-26 17:23:48,558 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: defer
2024-01-26 17:23:48,558 INFO    SenderThread:3042410 [sender.py:send_request_defer():613] handle sender defer: 14
2024-01-26 17:23:48,559 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:48,559 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:48,560 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:48,561 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:48,561 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: server_info
2024-01-26 17:23:48,561 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: get_summary
2024-01-26 17:23:48,562 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: server_info
2024-01-26 17:23:48,564 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: sampled_history
2024-01-26 17:23:48,564 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:23:48,564 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: job_info
2024-01-26 17:23:48,830 DEBUG   SenderThread:3042410 [sender.py:send_request():409] send_request: job_info
2024-01-26 17:23:48,831 INFO    MainThread:3042410 [wandb_run.py:_footer_history_summary_info():3857] rendering history
2024-01-26 17:23:48,831 INFO    MainThread:3042410 [wandb_run.py:_footer_history_summary_info():3889] rendering summary
2024-01-26 17:23:48,831 INFO    MainThread:3042410 [wandb_run.py:_footer_sync_info():3816] logging synced files
2024-01-26 17:23:48,832 DEBUG   HandlerThread:3042410 [handler.py:handle_request():146] handle_request: shutdown
2024-01-26 17:23:48,832 INFO    HandlerThread:3042410 [handler.py:finish():869] shutting down handler
2024-01-26 17:23:49,565 INFO    WriterThread:3042410 [datastore.py:close():296] close: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-oda2kyd2/run-oda2kyd2.wandb
2024-01-26 17:23:49,831 INFO    SenderThread:3042410 [sender.py:finish():1572] shutting down sender
2024-01-26 17:23:49,831 INFO    SenderThread:3042410 [file_pusher.py:finish():175] shutting down file pusher
2024-01-26 17:23:49,831 INFO    SenderThread:3042410 [file_pusher.py:join():181] waiting for file pusher
