2024-01-26 17:08:45,858 INFO    StreamThr :3042421 [internal.py:wandb_internal():86] W&B internal server running at pid: 3042421, started at: 2024-01-26 17:08:45.857647
2024-01-26 17:08:45,894 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status
2024-01-26 17:08:45,905 INFO    WriterThread:3042421 [datastore.py:open_for_write():87] open: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/run-b2arb4hk.wandb
2024-01-26 17:08:45,906 DEBUG   SenderThread:3042421 [sender.py:send():382] send: header
2024-01-26 17:08:45,906 DEBUG   SenderThread:3042421 [sender.py:send():382] send: run
2024-01-26 17:08:46,788 INFO    SenderThread:3042421 [dir_watcher.py:__init__():211] watching files in: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/files
2024-01-26 17:08:46,789 INFO    SenderThread:3042421 [sender.py:_start_run_threads():1136] run started: b2arb4hk with start time 1706260125.810575
2024-01-26 17:08:46,793 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: check_version
2024-01-26 17:08:46,793 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: check_version
2024-01-26 17:08:47,154 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: run_start
2024-01-26 17:08:47,164 DEBUG   HandlerThread:3042421 [system_info.py:__init__():27] System info init
2024-01-26 17:08:47,164 DEBUG   HandlerThread:3042421 [system_info.py:__init__():42] System info init done
2024-01-26 17:08:47,164 INFO    HandlerThread:3042421 [system_monitor.py:start():194] Starting system monitor
2024-01-26 17:08:47,164 INFO    SystemMonitor:3042421 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-01-26 17:08:47,165 INFO    HandlerThread:3042421 [system_monitor.py:probe():214] Collecting system info
2024-01-26 17:08:47,170 INFO    SystemMonitor:3042421 [interfaces.py:start():190] Started cpu monitoring
2024-01-26 17:08:47,174 INFO    SystemMonitor:3042421 [interfaces.py:start():190] Started disk monitoring
2024-01-26 17:08:47,178 INFO    SystemMonitor:3042421 [interfaces.py:start():190] Started gpu monitoring
2024-01-26 17:08:47,181 INFO    SystemMonitor:3042421 [interfaces.py:start():190] Started memory monitoring
2024-01-26 17:08:47,185 INFO    SystemMonitor:3042421 [interfaces.py:start():190] Started network monitoring
2024-01-26 17:08:47,268 DEBUG   HandlerThread:3042421 [system_info.py:probe():151] Probing system
2024-01-26 17:08:47,276 DEBUG   HandlerThread:3042421 [system_info.py:_probe_git():136] Probing git
2024-01-26 17:08:47,302 DEBUG   HandlerThread:3042421 [system_info.py:_probe_git():144] Probing git done
2024-01-26 17:08:47,303 DEBUG   HandlerThread:3042421 [system_info.py:probe():199] Probing system done
2024-01-26 17:08:47,303 DEBUG   HandlerThread:3042421 [system_monitor.py:probe():223] {'os': 'Linux-5.15.0-91-generic-x86_64-with-glibc2.17', 'python': '3.8.17', 'heartbeatAt': '2024-01-26T09:08:47.268255', 'startedAt': '2024-01-26T09:08:45.776824', 'docker': None, 'cuda': None, 'args': ('--local_rank=7', '--config_file', 'config/bert_pretraining_phase2_config.json', '--input_dir', '/home/yanxindong/mkor/bert/data/encoded/sequences_lowercase_max_seq_len_512_next_seq_task_true', '--output_dir', 'results/adam', '--weight_decay', '0.01', '--num_steps_per_checkpoint', '200'), 'state': 'running', 'program': 'run_pretraining.py', 'codePathLocal': 'run_pretraining.py', 'codePath': 'bert/run_pretraining.py', 'git': {'remote': 'https://github.com/kkkjj-d/mkor.git', 'commit': 'efe99e84fef5594780cfb1df6d6a1f61da4ebba0'}, 'email': '1262670315@qq.com', 'root': '/home/yanxindong/mkor', 'host': 'a6000-X640-G40', 'username': 'yanxindong', 'executable': '/home/yanxindong/anaconda/envs/eva/bin/python', 'cpu_count': 64, 'cpu_count_logical': 128, 'cpu_freq': {'current': 2798.4157812500007, 'min': 800.0, 'max': 3400.0}, 'cpu_freq_per_core': [{'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.003, 'min': 800.0, 'max': 3400.0}, {'current': 2424.276, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 2981.175, 'min': 800.0, 'max': 3400.0}, {'current': 1500.0, 'min': 800.0, 'max': 3400.0}, {'current': 1900.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.001, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3000.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2334.562, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2261.035, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 1700.0, 'min': 800.0, 'max': 3400.0}, {'current': 1700.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3131.387, 'min': 800.0, 'max': 3400.0}, {'current': 2951.882, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.009, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 1700.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3062.266, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2900.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1500.0, 'min': 800.0, 'max': 3400.0}, {'current': 2887.513, 'min': 800.0, 'max': 3400.0}, {'current': 1600.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1100.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 2900.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3200.0, 'min': 800.0, 'max': 3400.0}, {'current': 2518.878, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2000.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3000.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 2923.255, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1100.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3100.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 2900.0, 'min': 800.0, 'max': 3400.0}, {'current': 1400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 2000.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 2700.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 1500.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1600.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3070.802, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2835.561, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}], 'disk': {'/': {'total': 438.05088806152344, 'used': 28.042720794677734}}, 'gpu': 'NVIDIA RTX A6000', 'gpu_count': 8, 'gpu_devices': [{'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}], 'memory': {'total': 503.51250076293945}}
2024-01-26 17:08:47,303 INFO    HandlerThread:3042421 [system_monitor.py:probe():224] Finished collecting system info
2024-01-26 17:08:47,303 INFO    HandlerThread:3042421 [system_monitor.py:probe():227] Publishing system info
2024-01-26 17:08:47,303 DEBUG   HandlerThread:3042421 [system_info.py:_save_conda():208] Saving list of conda packages installed into the current environment
2024-01-26 17:08:47,790 INFO    Thread-12 :3042421 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/files/conda-environment.yaml
2024-01-26 17:08:57,458 DEBUG   HandlerThread:3042421 [system_info.py:_save_conda():220] Saving conda packages done
2024-01-26 17:08:57,460 INFO    HandlerThread:3042421 [system_monitor.py:probe():229] Finished publishing system info
2024-01-26 17:08:57,465 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:08:57,471 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:08:57,472 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:08:57,472 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:08:57,472 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: python_packages
2024-01-26 17:08:57,472 DEBUG   SenderThread:3042421 [sender.py:send():382] send: files
2024-01-26 17:08:57,472 INFO    SenderThread:3042421 [sender.py:_save_file():1403] saving file wandb-metadata.json with policy now
2024-01-26 17:08:57,473 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: python_packages
2024-01-26 17:08:57,501 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:08:57,502 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:08:57,541 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:08:57,791 INFO    Thread-12 :3042421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/files/conda-environment.yaml
2024-01-26 17:08:57,792 INFO    Thread-12 :3042421 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/files/wandb-metadata.json
2024-01-26 17:08:57,792 INFO    Thread-12 :3042421 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/files/requirements.txt
2024-01-26 17:08:57,805 DEBUG   SenderThread:3042421 [sender.py:send():382] send: telemetry
2024-01-26 17:08:58,359 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/b2arb4hk/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lqiK6NPhItf%2B7BfwSHGQQ2bjZgAilIu5z2bDPKlOTZdVQ7H17h8N72yrarsPy2B8BXSCJ6uMNvG55x03MteEJY86yVTo4%2FNO5QNRK26yt9PLjnpLmMgJUWWLRDkA%2Fj9jL4VdWmXKM%2B8p04wBnJiShJ9J9GhtUefMwQOg%2B6k2Cb0o37SZCVgTKvnoGkAGEwZKox6DpycClF2nZStVfz9175fBqjglTVPIcGtutzkWRkfPxxNXJafgtZVyYt1bsnalw7LkL9iEN9xEbX55lGE6Mgj%2B%2Bv8Vg3H3OMXJFwPX%2BOFyMHyI7M4%2FksG0%2FBAXsXGHAdDlXIbd88A4zttGkF7wjQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/b2arb4hk/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lqiK6NPhItf%2B7BfwSHGQQ2bjZgAilIu5z2bDPKlOTZdVQ7H17h8N72yrarsPy2B8BXSCJ6uMNvG55x03MteEJY86yVTo4%2FNO5QNRK26yt9PLjnpLmMgJUWWLRDkA%2Fj9jL4VdWmXKM%2B8p04wBnJiShJ9J9GhtUefMwQOg%2B6k2Cb0o37SZCVgTKvnoGkAGEwZKox6DpycClF2nZStVfz9175fBqjglTVPIcGtutzkWRkfPxxNXJafgtZVyYt1bsnalw7LkL9iEN9xEbX55lGE6Mgj%2B%2Bv8Vg3H3OMXJFwPX%2BOFyMHyI7M4%2FksG0%2FBAXsXGHAdDlXIbd88A4zttGkF7wjQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b835feb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:08:58,359 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15651'}
2024-01-26 17:08:58,359 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:08:59,369 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/b2arb4hk/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lqiK6NPhItf%2B7BfwSHGQQ2bjZgAilIu5z2bDPKlOTZdVQ7H17h8N72yrarsPy2B8BXSCJ6uMNvG55x03MteEJY86yVTo4%2FNO5QNRK26yt9PLjnpLmMgJUWWLRDkA%2Fj9jL4VdWmXKM%2B8p04wBnJiShJ9J9GhtUefMwQOg%2B6k2Cb0o37SZCVgTKvnoGkAGEwZKox6DpycClF2nZStVfz9175fBqjglTVPIcGtutzkWRkfPxxNXJafgtZVyYt1bsnalw7LkL9iEN9xEbX55lGE6Mgj%2B%2Bv8Vg3H3OMXJFwPX%2BOFyMHyI7M4%2FksG0%2FBAXsXGHAdDlXIbd88A4zttGkF7wjQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/b2arb4hk/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lqiK6NPhItf%2B7BfwSHGQQ2bjZgAilIu5z2bDPKlOTZdVQ7H17h8N72yrarsPy2B8BXSCJ6uMNvG55x03MteEJY86yVTo4%2FNO5QNRK26yt9PLjnpLmMgJUWWLRDkA%2Fj9jL4VdWmXKM%2B8p04wBnJiShJ9J9GhtUefMwQOg%2B6k2Cb0o37SZCVgTKvnoGkAGEwZKox6DpycClF2nZStVfz9175fBqjglTVPIcGtutzkWRkfPxxNXJafgtZVyYt1bsnalw7LkL9iEN9xEbX55lGE6Mgj%2B%2Bv8Vg3H3OMXJFwPX%2BOFyMHyI7M4%2FksG0%2FBAXsXGHAdDlXIbd88A4zttGkF7wjQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b8317b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:08:59,369 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15651'}
2024-01-26 17:08:59,369 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:01,547 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/b2arb4hk/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lqiK6NPhItf%2B7BfwSHGQQ2bjZgAilIu5z2bDPKlOTZdVQ7H17h8N72yrarsPy2B8BXSCJ6uMNvG55x03MteEJY86yVTo4%2FNO5QNRK26yt9PLjnpLmMgJUWWLRDkA%2Fj9jL4VdWmXKM%2B8p04wBnJiShJ9J9GhtUefMwQOg%2B6k2Cb0o37SZCVgTKvnoGkAGEwZKox6DpycClF2nZStVfz9175fBqjglTVPIcGtutzkWRkfPxxNXJafgtZVyYt1bsnalw7LkL9iEN9xEbX55lGE6Mgj%2B%2Bv8Vg3H3OMXJFwPX%2BOFyMHyI7M4%2FksG0%2FBAXsXGHAdDlXIbd88A4zttGkF7wjQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/b2arb4hk/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lqiK6NPhItf%2B7BfwSHGQQ2bjZgAilIu5z2bDPKlOTZdVQ7H17h8N72yrarsPy2B8BXSCJ6uMNvG55x03MteEJY86yVTo4%2FNO5QNRK26yt9PLjnpLmMgJUWWLRDkA%2Fj9jL4VdWmXKM%2B8p04wBnJiShJ9J9GhtUefMwQOg%2B6k2Cb0o37SZCVgTKvnoGkAGEwZKox6DpycClF2nZStVfz9175fBqjglTVPIcGtutzkWRkfPxxNXJafgtZVyYt1bsnalw7LkL9iEN9xEbX55lGE6Mgj%2B%2Bv8Vg3H3OMXJFwPX%2BOFyMHyI7M4%2FksG0%2FBAXsXGHAdDlXIbd88A4zttGkF7wjQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b83274c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:01,547 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15651'}
2024-01-26 17:09:01,547 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:01,547 INFO    wandb-upload_0:3042421 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f22b83274c0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/b2arb4hk/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lqiK6NPhItf%2B7BfwSHGQQ2bjZgAilIu5z2bDPKlOTZdVQ7H17h8N72yrarsPy2B8BXSCJ6uMNvG55x03MteEJY86yVTo4%2FNO5QNRK26yt9PLjnpLmMgJUWWLRDkA%2Fj9jL4VdWmXKM%2B8p04wBnJiShJ9J9GhtUefMwQOg%2B6k2Cb0o37SZCVgTKvnoGkAGEwZKox6DpycClF2nZStVfz9175fBqjglTVPIcGtutzkWRkfPxxNXJafgtZVyYt1bsnalw7LkL9iEN9xEbX55lGE6Mgj%2B%2Bv8Vg3H3OMXJFwPX%2BOFyMHyI7M4%2FksG0%2FBAXsXGHAdDlXIbd88A4zttGkF7wjQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b83274c0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/b2arb4hk/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lqiK6NPhItf%2B7BfwSHGQQ2bjZgAilIu5z2bDPKlOTZdVQ7H17h8N72yrarsPy2B8BXSCJ6uMNvG55x03MteEJY86yVTo4%2FNO5QNRK26yt9PLjnpLmMgJUWWLRDkA%2Fj9jL4VdWmXKM%2B8p04wBnJiShJ9J9GhtUefMwQOg%2B6k2Cb0o37SZCVgTKvnoGkAGEwZKox6DpycClF2nZStVfz9175fBqjglTVPIcGtutzkWRkfPxxNXJafgtZVyYt1bsnalw7LkL9iEN9xEbX55lGE6Mgj%2B%2Bv8Vg3H3OMXJFwPX%2BOFyMHyI7M4%2FksG0%2FBAXsXGHAdDlXIbd88A4zttGkF7wjQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b83274c0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2789, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-01-26 17:09:01,806 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:05,930 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/b2arb4hk/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lqiK6NPhItf%2B7BfwSHGQQ2bjZgAilIu5z2bDPKlOTZdVQ7H17h8N72yrarsPy2B8BXSCJ6uMNvG55x03MteEJY86yVTo4%2FNO5QNRK26yt9PLjnpLmMgJUWWLRDkA%2Fj9jL4VdWmXKM%2B8p04wBnJiShJ9J9GhtUefMwQOg%2B6k2Cb0o37SZCVgTKvnoGkAGEwZKox6DpycClF2nZStVfz9175fBqjglTVPIcGtutzkWRkfPxxNXJafgtZVyYt1bsnalw7LkL9iEN9xEbX55lGE6Mgj%2B%2Bv8Vg3H3OMXJFwPX%2BOFyMHyI7M4%2FksG0%2FBAXsXGHAdDlXIbd88A4zttGkF7wjQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/b2arb4hk/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lqiK6NPhItf%2B7BfwSHGQQ2bjZgAilIu5z2bDPKlOTZdVQ7H17h8N72yrarsPy2B8BXSCJ6uMNvG55x03MteEJY86yVTo4%2FNO5QNRK26yt9PLjnpLmMgJUWWLRDkA%2Fj9jL4VdWmXKM%2B8p04wBnJiShJ9J9GhtUefMwQOg%2B6k2Cb0o37SZCVgTKvnoGkAGEwZKox6DpycClF2nZStVfz9175fBqjglTVPIcGtutzkWRkfPxxNXJafgtZVyYt1bsnalw7LkL9iEN9xEbX55lGE6Mgj%2B%2Bv8Vg3H3OMXJFwPX%2BOFyMHyI7M4%2FksG0%2FBAXsXGHAdDlXIbd88A4zttGkF7wjQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b8317f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:05,930 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15651'}
2024-01-26 17:09:05,930 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:06,806 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:11,807 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:12,494 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:09:12,495 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:09:12,538 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:09:14,381 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/b2arb4hk/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lqiK6NPhItf%2B7BfwSHGQQ2bjZgAilIu5z2bDPKlOTZdVQ7H17h8N72yrarsPy2B8BXSCJ6uMNvG55x03MteEJY86yVTo4%2FNO5QNRK26yt9PLjnpLmMgJUWWLRDkA%2Fj9jL4VdWmXKM%2B8p04wBnJiShJ9J9GhtUefMwQOg%2B6k2Cb0o37SZCVgTKvnoGkAGEwZKox6DpycClF2nZStVfz9175fBqjglTVPIcGtutzkWRkfPxxNXJafgtZVyYt1bsnalw7LkL9iEN9xEbX55lGE6Mgj%2B%2Bv8Vg3H3OMXJFwPX%2BOFyMHyI7M4%2FksG0%2FBAXsXGHAdDlXIbd88A4zttGkF7wjQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/b2arb4hk/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lqiK6NPhItf%2B7BfwSHGQQ2bjZgAilIu5z2bDPKlOTZdVQ7H17h8N72yrarsPy2B8BXSCJ6uMNvG55x03MteEJY86yVTo4%2FNO5QNRK26yt9PLjnpLmMgJUWWLRDkA%2Fj9jL4VdWmXKM%2B8p04wBnJiShJ9J9GhtUefMwQOg%2B6k2Cb0o37SZCVgTKvnoGkAGEwZKox6DpycClF2nZStVfz9175fBqjglTVPIcGtutzkWRkfPxxNXJafgtZVyYt1bsnalw7LkL9iEN9xEbX55lGE6Mgj%2B%2Bv8Vg3H3OMXJFwPX%2BOFyMHyI7M4%2FksG0%2FBAXsXGHAdDlXIbd88A4zttGkF7wjQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b8327070>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:14,381 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15651'}
2024-01-26 17:09:14,381 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:16,855 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:17,797 INFO    Thread-12 :3042421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/files/config.yaml
2024-01-26 17:09:22,128 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:27,202 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:27,494 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:09:27,495 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:09:27,545 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:09:32,623 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/b2arb4hk/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lqiK6NPhItf%2B7BfwSHGQQ2bjZgAilIu5z2bDPKlOTZdVQ7H17h8N72yrarsPy2B8BXSCJ6uMNvG55x03MteEJY86yVTo4%2FNO5QNRK26yt9PLjnpLmMgJUWWLRDkA%2Fj9jL4VdWmXKM%2B8p04wBnJiShJ9J9GhtUefMwQOg%2B6k2Cb0o37SZCVgTKvnoGkAGEwZKox6DpycClF2nZStVfz9175fBqjglTVPIcGtutzkWRkfPxxNXJafgtZVyYt1bsnalw7LkL9iEN9xEbX55lGE6Mgj%2B%2Bv8Vg3H3OMXJFwPX%2BOFyMHyI7M4%2FksG0%2FBAXsXGHAdDlXIbd88A4zttGkF7wjQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/b2arb4hk/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lqiK6NPhItf%2B7BfwSHGQQ2bjZgAilIu5z2bDPKlOTZdVQ7H17h8N72yrarsPy2B8BXSCJ6uMNvG55x03MteEJY86yVTo4%2FNO5QNRK26yt9PLjnpLmMgJUWWLRDkA%2Fj9jL4VdWmXKM%2B8p04wBnJiShJ9J9GhtUefMwQOg%2B6k2Cb0o37SZCVgTKvnoGkAGEwZKox6DpycClF2nZStVfz9175fBqjglTVPIcGtutzkWRkfPxxNXJafgtZVyYt1bsnalw7LkL9iEN9xEbX55lGE6Mgj%2B%2Bv8Vg3H3OMXJFwPX%2BOFyMHyI7M4%2FksG0%2FBAXsXGHAdDlXIbd88A4zttGkF7wjQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b83170a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:09:32,623 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15651'}
2024-01-26 17:09:32,623 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:09:32,918 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:37,918 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:42,495 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:09:42,495 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:09:42,538 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:09:45,837 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:47,185 DEBUG   SystemMonitor:3042421 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-01-26 17:09:47,189 DEBUG   SenderThread:3042421 [sender.py:send():382] send: stats
2024-01-26 17:09:51,198 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:56,198 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:09:57,494 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:09:57,495 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:09:57,538 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:10:01,826 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:06,865 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:11,322 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/b2arb4hk/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lqiK6NPhItf%2B7BfwSHGQQ2bjZgAilIu5z2bDPKlOTZdVQ7H17h8N72yrarsPy2B8BXSCJ6uMNvG55x03MteEJY86yVTo4%2FNO5QNRK26yt9PLjnpLmMgJUWWLRDkA%2Fj9jL4VdWmXKM%2B8p04wBnJiShJ9J9GhtUefMwQOg%2B6k2Cb0o37SZCVgTKvnoGkAGEwZKox6DpycClF2nZStVfz9175fBqjglTVPIcGtutzkWRkfPxxNXJafgtZVyYt1bsnalw7LkL9iEN9xEbX55lGE6Mgj%2B%2Bv8Vg3H3OMXJFwPX%2BOFyMHyI7M4%2FksG0%2FBAXsXGHAdDlXIbd88A4zttGkF7wjQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/b2arb4hk/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lqiK6NPhItf%2B7BfwSHGQQ2bjZgAilIu5z2bDPKlOTZdVQ7H17h8N72yrarsPy2B8BXSCJ6uMNvG55x03MteEJY86yVTo4%2FNO5QNRK26yt9PLjnpLmMgJUWWLRDkA%2Fj9jL4VdWmXKM%2B8p04wBnJiShJ9J9GhtUefMwQOg%2B6k2Cb0o37SZCVgTKvnoGkAGEwZKox6DpycClF2nZStVfz9175fBqjglTVPIcGtutzkWRkfPxxNXJafgtZVyYt1bsnalw7LkL9iEN9xEbX55lGE6Mgj%2B%2Bv8Vg3H3OMXJFwPX%2BOFyMHyI7M4%2FksG0%2FBAXsXGHAdDlXIbd88A4zttGkF7wjQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b8327340>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:10:11,322 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15651'}
2024-01-26 17:10:11,322 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:10:11,901 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:12,495 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:10:12,495 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:10:12,538 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:10:17,192 DEBUG   SenderThread:3042421 [sender.py:send():382] send: stats
2024-01-26 17:10:17,195 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:22,194 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:27,194 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:27,495 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:10:27,495 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:10:27,542 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:10:32,778 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:33,987 INFO    Thread-12 :3042421 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/files/output.log
2024-01-26 17:10:35,987 INFO    Thread-12 :3042421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/files/output.log
2024-01-26 17:10:38,158 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:43,159 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:44,899 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:10:44,899 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:10:44,900 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:10:47,193 DEBUG   SenderThread:3042421 [sender.py:send():382] send: stats
2024-01-26 17:10:48,394 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:53,556 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:58,630 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:10:59,950 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:10:59,950 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:10:59,950 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:04,374 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:09,422 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:14,430 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:14,918 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:11:14,918 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:15,030 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:11:17,248 DEBUG   SenderThread:3042421 [sender.py:send():382] send: stats
2024-01-26 17:11:17,807 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/b2arb4hk/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lqiK6NPhItf%2B7BfwSHGQQ2bjZgAilIu5z2bDPKlOTZdVQ7H17h8N72yrarsPy2B8BXSCJ6uMNvG55x03MteEJY86yVTo4%2FNO5QNRK26yt9PLjnpLmMgJUWWLRDkA%2Fj9jL4VdWmXKM%2B8p04wBnJiShJ9J9GhtUefMwQOg%2B6k2Cb0o37SZCVgTKvnoGkAGEwZKox6DpycClF2nZStVfz9175fBqjglTVPIcGtutzkWRkfPxxNXJafgtZVyYt1bsnalw7LkL9iEN9xEbX55lGE6Mgj%2B%2Bv8Vg3H3OMXJFwPX%2BOFyMHyI7M4%2FksG0%2FBAXsXGHAdDlXIbd88A4zttGkF7wjQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/b2arb4hk/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lqiK6NPhItf%2B7BfwSHGQQ2bjZgAilIu5z2bDPKlOTZdVQ7H17h8N72yrarsPy2B8BXSCJ6uMNvG55x03MteEJY86yVTo4%2FNO5QNRK26yt9PLjnpLmMgJUWWLRDkA%2Fj9jL4VdWmXKM%2B8p04wBnJiShJ9J9GhtUefMwQOg%2B6k2Cb0o37SZCVgTKvnoGkAGEwZKox6DpycClF2nZStVfz9175fBqjglTVPIcGtutzkWRkfPxxNXJafgtZVyYt1bsnalw7LkL9iEN9xEbX55lGE6Mgj%2B%2Bv8Vg3H3OMXJFwPX%2BOFyMHyI7M4%2FksG0%2FBAXsXGHAdDlXIbd88A4zttGkF7wjQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b81a5c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:11:17,807 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15651'}
2024-01-26 17:11:17,807 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:11:20,256 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:25,471 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:29,899 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:11:29,899 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:11:29,900 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:31,234 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:36,235 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:41,236 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:44,899 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:11:44,899 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:44,942 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:11:46,257 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:47,251 DEBUG   SenderThread:3042421 [sender.py:send():382] send: stats
2024-01-26 17:11:52,253 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:57,253 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:11:59,899 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:11:59,899 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:11:59,942 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:12:02,273 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:07,274 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:12,370 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:14,899 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:12:14,899 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:12:14,962 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:12:17,253 DEBUG   SenderThread:3042421 [sender.py:send():382] send: stats
2024-01-26 17:12:18,303 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:23,406 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:28,600 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:29,899 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:12:29,899 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:12:30,006 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:12:34,330 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:39,331 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:44,357 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:44,899 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:12:44,899 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:12:44,903 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:12:47,256 DEBUG   SenderThread:3042421 [sender.py:send():382] send: stats
2024-01-26 17:12:50,258 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:55,258 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:12:59,899 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:12:59,899 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:12:59,942 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:13:01,205 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:06,206 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:11,207 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:14,899 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:13:14,899 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:13:14,942 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:13:16,829 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:17,257 DEBUG   SenderThread:3042421 [sender.py:send():382] send: stats
2024-01-26 17:13:22,374 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:27,470 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:29,958 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:13:29,958 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:13:29,959 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:13:33,378 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:38,379 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:43,501 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:44,899 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:13:44,900 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:13:45,098 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:13:47,288 DEBUG   SenderThread:3042421 [sender.py:send():382] send: stats
2024-01-26 17:13:49,374 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:53,887 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/b2arb4hk/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lqiK6NPhItf%2B7BfwSHGQQ2bjZgAilIu5z2bDPKlOTZdVQ7H17h8N72yrarsPy2B8BXSCJ6uMNvG55x03MteEJY86yVTo4%2FNO5QNRK26yt9PLjnpLmMgJUWWLRDkA%2Fj9jL4VdWmXKM%2B8p04wBnJiShJ9J9GhtUefMwQOg%2B6k2Cb0o37SZCVgTKvnoGkAGEwZKox6DpycClF2nZStVfz9175fBqjglTVPIcGtutzkWRkfPxxNXJafgtZVyYt1bsnalw7LkL9iEN9xEbX55lGE6Mgj%2B%2Bv8Vg3H3OMXJFwPX%2BOFyMHyI7M4%2FksG0%2FBAXsXGHAdDlXIbd88A4zttGkF7wjQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/b2arb4hk/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lqiK6NPhItf%2B7BfwSHGQQ2bjZgAilIu5z2bDPKlOTZdVQ7H17h8N72yrarsPy2B8BXSCJ6uMNvG55x03MteEJY86yVTo4%2FNO5QNRK26yt9PLjnpLmMgJUWWLRDkA%2Fj9jL4VdWmXKM%2B8p04wBnJiShJ9J9GhtUefMwQOg%2B6k2Cb0o37SZCVgTKvnoGkAGEwZKox6DpycClF2nZStVfz9175fBqjglTVPIcGtutzkWRkfPxxNXJafgtZVyYt1bsnalw7LkL9iEN9xEbX55lGE6Mgj%2B%2Bv8Vg3H3OMXJFwPX%2BOFyMHyI7M4%2FksG0%2FBAXsXGHAdDlXIbd88A4zttGkF7wjQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b8317b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:13:53,887 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15651'}
2024-01-26 17:13:53,887 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:13:54,466 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:59,466 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:13:59,900 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:13:59,900 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:13:59,904 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:14:05,243 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:10,244 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:14,900 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:14:14,900 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:14:14,942 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:14:16,189 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:17,291 DEBUG   SenderThread:3042421 [sender.py:send():382] send: stats
2024-01-26 17:14:21,292 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:26,293 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:29,926 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:14:29,926 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:14:30,059 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:14:31,298 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:36,424 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:41,468 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:44,900 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:14:44,900 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:14:44,904 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:14:47,352 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:47,354 DEBUG   SenderThread:3042421 [sender.py:send():382] send: stats
2024-01-26 17:14:52,418 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:57,420 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:14:59,900 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:14:59,900 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:14:59,942 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:15:03,222 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:08,223 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:13,223 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:14,900 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:15:14,900 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:15:14,942 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:15:17,357 DEBUG   SenderThread:3042421 [sender.py:send():382] send: stats
2024-01-26 17:15:18,361 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:23,363 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:28,365 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:29,900 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:15:29,901 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:15:29,942 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:15:34,198 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:39,202 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:40,650 DEBUG   SenderThread:3042421 [sender.py:send():382] send: exit
2024-01-26 17:15:40,651 INFO    SenderThread:3042421 [sender.py:send_exit():589] handling exit code: 1
2024-01-26 17:15:40,651 INFO    SenderThread:3042421 [sender.py:send_exit():591] handling runtime: 413
2024-01-26 17:15:40,651 INFO    SenderThread:3042421 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-01-26 17:15:40,651 INFO    SenderThread:3042421 [sender.py:send_exit():597] send defer
2024-01-26 17:15:40,652 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:40,652 INFO    HandlerThread:3042421 [handler.py:handle_request_defer():172] handle defer: 0
2024-01-26 17:15:40,652 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:40,652 INFO    SenderThread:3042421 [sender.py:send_request_defer():613] handle sender defer: 0
2024-01-26 17:15:40,652 INFO    SenderThread:3042421 [sender.py:transition_state():617] send defer: 1
2024-01-26 17:15:40,652 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:40,652 INFO    HandlerThread:3042421 [handler.py:handle_request_defer():172] handle defer: 1
2024-01-26 17:15:40,652 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:40,652 INFO    SenderThread:3042421 [sender.py:send_request_defer():613] handle sender defer: 1
2024-01-26 17:15:40,652 INFO    SenderThread:3042421 [sender.py:transition_state():617] send defer: 2
2024-01-26 17:15:40,652 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:40,652 INFO    HandlerThread:3042421 [handler.py:handle_request_defer():172] handle defer: 2
2024-01-26 17:15:40,652 INFO    HandlerThread:3042421 [system_monitor.py:finish():203] Stopping system monitor
2024-01-26 17:15:40,653 INFO    HandlerThread:3042421 [interfaces.py:finish():202] Joined cpu monitor
2024-01-26 17:15:40,653 INFO    HandlerThread:3042421 [interfaces.py:finish():202] Joined disk monitor
2024-01-26 17:15:40,653 DEBUG   SystemMonitor:3042421 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-01-26 17:15:40,654 DEBUG   SystemMonitor:3042421 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-01-26 17:15:40,919 INFO    Thread-12 :3042421 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/files/wandb-summary.json
2024-01-26 17:15:42,513 INFO    HandlerThread:3042421 [interfaces.py:finish():202] Joined gpu monitor
2024-01-26 17:15:42,514 INFO    HandlerThread:3042421 [interfaces.py:finish():202] Joined memory monitor
2024-01-26 17:15:42,514 INFO    HandlerThread:3042421 [interfaces.py:finish():202] Joined network monitor
2024-01-26 17:15:42,514 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:15:42,514 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:42,514 INFO    SenderThread:3042421 [sender.py:send_request_defer():613] handle sender defer: 2
2024-01-26 17:15:42,514 INFO    SenderThread:3042421 [sender.py:transition_state():617] send defer: 3
2024-01-26 17:15:42,515 DEBUG   SenderThread:3042421 [sender.py:send():382] send: stats
2024-01-26 17:15:42,515 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:15:42,515 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:42,516 INFO    HandlerThread:3042421 [handler.py:handle_request_defer():172] handle defer: 3
2024-01-26 17:15:42,516 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:42,516 INFO    SenderThread:3042421 [sender.py:send_request_defer():613] handle sender defer: 3
2024-01-26 17:15:42,516 INFO    SenderThread:3042421 [sender.py:transition_state():617] send defer: 4
2024-01-26 17:15:42,516 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:42,516 INFO    HandlerThread:3042421 [handler.py:handle_request_defer():172] handle defer: 4
2024-01-26 17:15:42,516 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:42,516 INFO    SenderThread:3042421 [sender.py:send_request_defer():613] handle sender defer: 4
2024-01-26 17:15:42,516 INFO    SenderThread:3042421 [sender.py:transition_state():617] send defer: 5
2024-01-26 17:15:42,516 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:42,516 INFO    HandlerThread:3042421 [handler.py:handle_request_defer():172] handle defer: 5
2024-01-26 17:15:42,516 DEBUG   SenderThread:3042421 [sender.py:send():382] send: summary
2024-01-26 17:15:42,517 INFO    SenderThread:3042421 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-01-26 17:15:42,517 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:42,517 INFO    SenderThread:3042421 [sender.py:send_request_defer():613] handle sender defer: 5
2024-01-26 17:15:42,517 INFO    SenderThread:3042421 [sender.py:transition_state():617] send defer: 6
2024-01-26 17:15:42,517 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:42,517 INFO    HandlerThread:3042421 [handler.py:handle_request_defer():172] handle defer: 6
2024-01-26 17:15:42,517 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:42,517 INFO    SenderThread:3042421 [sender.py:send_request_defer():613] handle sender defer: 6
2024-01-26 17:15:42,517 INFO    SenderThread:3042421 [sender.py:transition_state():617] send defer: 7
2024-01-26 17:15:42,517 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:15:42,517 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:42,517 INFO    HandlerThread:3042421 [handler.py:handle_request_defer():172] handle defer: 7
2024-01-26 17:15:42,517 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:42,517 INFO    SenderThread:3042421 [sender.py:send_request_defer():613] handle sender defer: 7
2024-01-26 17:15:42,663 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:15:42,920 INFO    Thread-12 :3042421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/files/wandb-summary.json
2024-01-26 17:15:42,935 INFO    SenderThread:3042421 [sender.py:transition_state():617] send defer: 8
2024-01-26 17:15:42,935 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:15:42,935 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:42,935 INFO    HandlerThread:3042421 [handler.py:handle_request_defer():172] handle defer: 8
2024-01-26 17:15:42,936 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: defer
2024-01-26 17:15:42,936 INFO    SenderThread:3042421 [sender.py:send_request_defer():613] handle sender defer: 8
2024-01-26 17:15:42,936 INFO    SenderThread:3042421 [job_builder.py:build():296] Attempting to build job artifact
2024-01-26 17:15:42,936 INFO    SenderThread:3042421 [job_builder.py:_get_source_type():426] is repo sourced job
2024-01-26 17:15:42,962 INFO    SenderThread:3042421 [job_builder.py:build():402] adding wandb-job metadata file
2024-01-26 17:15:42,964 INFO    SenderThread:3042421 [sender.py:transition_state():617] send defer: 9
2024-01-26 17:15:42,965 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:15:42,965 DEBUG   SenderThread:3042421 [sender.py:send():382] send: artifact
2024-01-26 17:15:42,965 INFO    HandlerThread:3042421 [handler.py:handle_request_defer():172] handle defer: 9
2024-01-26 17:15:43,664 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:15:43,921 INFO    Thread-12 :3042421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/files/output.log
2024-01-26 17:15:46,129 ERROR   wandb-upload_1:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789754/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=I0vnNTk3C4YYdBgtMfwmQt%2BN8Lus3%2F4w8VM6WNlRb2Ai4CEnDRUeVbzlD0NuvjH5mNQ6xLFdxL%2FU1Jkge%2BluFp17GxLZWBSeOHXHy9BpeBF9xdDga0Pu2gp0fauomM57kqhTz%2B%2FehO6PCeqLuHBxLP1vexGUpkK4eeJt%2FOff5fdLE52gDrMtaUHA2DPZ0iU%2FJ2Gbok2X1Hfq4NPx5KLb67fRWM4knvf0mSdbt1euh8mGmPsxWnzfGMG4Myur2Xj6P8TR%2BDZwyzJLcG6rQXKl60hKRz2DHO5NqbeEKRqtxJZPAOoPAf60Jw9mbh6QFZZ2g9MJBm8ObS3n7CeQH6y5ZA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789754/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=I0vnNTk3C4YYdBgtMfwmQt%2BN8Lus3%2F4w8VM6WNlRb2Ai4CEnDRUeVbzlD0NuvjH5mNQ6xLFdxL%2FU1Jkge%2BluFp17GxLZWBSeOHXHy9BpeBF9xdDga0Pu2gp0fauomM57kqhTz%2B%2FehO6PCeqLuHBxLP1vexGUpkK4eeJt%2FOff5fdLE52gDrMtaUHA2DPZ0iU%2FJ2Gbok2X1Hfq4NPx5KLb67fRWM4knvf0mSdbt1euh8mGmPsxWnzfGMG4Myur2Xj6P8TR%2BDZwyzJLcG6rQXKl60hKRz2DHO5NqbeEKRqtxJZPAOoPAf60Jw9mbh6QFZZ2g9MJBm8ObS3n7CeQH6y5ZA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b81b71f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:46,129 ERROR   wandb-upload_1:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:46,129 ERROR   wandb-upload_1:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:46,130 ERROR   wandb-upload_2:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789754/6873c23a2381d1524249eb1a948a45a5?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cHJXNLLOEIAbhu3yjIpNmYJmRp6%2Fv3A3FnKTzWRDFh0IARMQ8RrAzUHdWVUPOQAiR8V8iJn8J3EIXiEyFWpToEH3Zr6sHpA0qqPKwibXhjlIrLPV9tqi0rMr4mzgKoVfPXz5k0wrLMrqyxjuyv4gvjY65rDdbuUfiOPJQFYZvwDbVW79VbTcEwTzHYWfaQCn2p%2FBXWS3WzV9P%2BVsmOF1dSmavLPgZq%2Fr%2FXn8GqJjq3SUOLcDfwBEZIZUNAdThbZkXn1BStz%2BuPIu%2FcsF2psg%2BLWyyhEXiitM0AzTduNjhUvEBYAD8LE1fMcXiNWj0BUU70gnuxfsooVxtgKnQ8xpsA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789754/6873c23a2381d1524249eb1a948a45a5?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cHJXNLLOEIAbhu3yjIpNmYJmRp6%2Fv3A3FnKTzWRDFh0IARMQ8RrAzUHdWVUPOQAiR8V8iJn8J3EIXiEyFWpToEH3Zr6sHpA0qqPKwibXhjlIrLPV9tqi0rMr4mzgKoVfPXz5k0wrLMrqyxjuyv4gvjY65rDdbuUfiOPJQFYZvwDbVW79VbTcEwTzHYWfaQCn2p%2FBXWS3WzV9P%2BVsmOF1dSmavLPgZq%2Fr%2FXn8GqJjq3SUOLcDfwBEZIZUNAdThbZkXn1BStz%2BuPIu%2FcsF2psg%2BLWyyhEXiitM0AzTduNjhUvEBYAD8LE1fMcXiNWj0BUU70gnuxfsooVxtgKnQ8xpsA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b81b7820>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:46,130 ERROR   wandb-upload_2:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:46,130 ERROR   wandb-upload_2:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:47,143 ERROR   wandb-upload_1:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789754/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=I0vnNTk3C4YYdBgtMfwmQt%2BN8Lus3%2F4w8VM6WNlRb2Ai4CEnDRUeVbzlD0NuvjH5mNQ6xLFdxL%2FU1Jkge%2BluFp17GxLZWBSeOHXHy9BpeBF9xdDga0Pu2gp0fauomM57kqhTz%2B%2FehO6PCeqLuHBxLP1vexGUpkK4eeJt%2FOff5fdLE52gDrMtaUHA2DPZ0iU%2FJ2Gbok2X1Hfq4NPx5KLb67fRWM4knvf0mSdbt1euh8mGmPsxWnzfGMG4Myur2Xj6P8TR%2BDZwyzJLcG6rQXKl60hKRz2DHO5NqbeEKRqtxJZPAOoPAf60Jw9mbh6QFZZ2g9MJBm8ObS3n7CeQH6y5ZA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789754/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=I0vnNTk3C4YYdBgtMfwmQt%2BN8Lus3%2F4w8VM6WNlRb2Ai4CEnDRUeVbzlD0NuvjH5mNQ6xLFdxL%2FU1Jkge%2BluFp17GxLZWBSeOHXHy9BpeBF9xdDga0Pu2gp0fauomM57kqhTz%2B%2FehO6PCeqLuHBxLP1vexGUpkK4eeJt%2FOff5fdLE52gDrMtaUHA2DPZ0iU%2FJ2Gbok2X1Hfq4NPx5KLb67fRWM4knvf0mSdbt1euh8mGmPsxWnzfGMG4Myur2Xj6P8TR%2BDZwyzJLcG6rQXKl60hKRz2DHO5NqbeEKRqtxJZPAOoPAf60Jw9mbh6QFZZ2g9MJBm8ObS3n7CeQH6y5ZA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b8317fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:47,143 ERROR   wandb-upload_1:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:47,143 ERROR   wandb-upload_1:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:47,301 ERROR   wandb-upload_2:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789754/6873c23a2381d1524249eb1a948a45a5?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cHJXNLLOEIAbhu3yjIpNmYJmRp6%2Fv3A3FnKTzWRDFh0IARMQ8RrAzUHdWVUPOQAiR8V8iJn8J3EIXiEyFWpToEH3Zr6sHpA0qqPKwibXhjlIrLPV9tqi0rMr4mzgKoVfPXz5k0wrLMrqyxjuyv4gvjY65rDdbuUfiOPJQFYZvwDbVW79VbTcEwTzHYWfaQCn2p%2FBXWS3WzV9P%2BVsmOF1dSmavLPgZq%2Fr%2FXn8GqJjq3SUOLcDfwBEZIZUNAdThbZkXn1BStz%2BuPIu%2FcsF2psg%2BLWyyhEXiitM0AzTduNjhUvEBYAD8LE1fMcXiNWj0BUU70gnuxfsooVxtgKnQ8xpsA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789754/6873c23a2381d1524249eb1a948a45a5?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cHJXNLLOEIAbhu3yjIpNmYJmRp6%2Fv3A3FnKTzWRDFh0IARMQ8RrAzUHdWVUPOQAiR8V8iJn8J3EIXiEyFWpToEH3Zr6sHpA0qqPKwibXhjlIrLPV9tqi0rMr4mzgKoVfPXz5k0wrLMrqyxjuyv4gvjY65rDdbuUfiOPJQFYZvwDbVW79VbTcEwTzHYWfaQCn2p%2FBXWS3WzV9P%2BVsmOF1dSmavLPgZq%2Fr%2FXn8GqJjq3SUOLcDfwBEZIZUNAdThbZkXn1BStz%2BuPIu%2FcsF2psg%2BLWyyhEXiitM0AzTduNjhUvEBYAD8LE1fMcXiNWj0BUU70gnuxfsooVxtgKnQ8xpsA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b8377160>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:47,301 ERROR   wandb-upload_2:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:47,301 ERROR   wandb-upload_2:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:47,301 INFO    wandb-upload_2:3042421 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f22b8377160>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789754/6873c23a2381d1524249eb1a948a45a5?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cHJXNLLOEIAbhu3yjIpNmYJmRp6%2Fv3A3FnKTzWRDFh0IARMQ8RrAzUHdWVUPOQAiR8V8iJn8J3EIXiEyFWpToEH3Zr6sHpA0qqPKwibXhjlIrLPV9tqi0rMr4mzgKoVfPXz5k0wrLMrqyxjuyv4gvjY65rDdbuUfiOPJQFYZvwDbVW79VbTcEwTzHYWfaQCn2p%2FBXWS3WzV9P%2BVsmOF1dSmavLPgZq%2Fr%2FXn8GqJjq3SUOLcDfwBEZIZUNAdThbZkXn1BStz%2BuPIu%2FcsF2psg%2BLWyyhEXiitM0AzTduNjhUvEBYAD8LE1fMcXiNWj0BUU70gnuxfsooVxtgKnQ8xpsA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b8377160>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789754/6873c23a2381d1524249eb1a948a45a5?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cHJXNLLOEIAbhu3yjIpNmYJmRp6%2Fv3A3FnKTzWRDFh0IARMQ8RrAzUHdWVUPOQAiR8V8iJn8J3EIXiEyFWpToEH3Zr6sHpA0qqPKwibXhjlIrLPV9tqi0rMr4mzgKoVfPXz5k0wrLMrqyxjuyv4gvjY65rDdbuUfiOPJQFYZvwDbVW79VbTcEwTzHYWfaQCn2p%2FBXWS3WzV9P%2BVsmOF1dSmavLPgZq%2Fr%2FXn8GqJjq3SUOLcDfwBEZIZUNAdThbZkXn1BStz%2BuPIu%2FcsF2psg%2BLWyyhEXiitM0AzTduNjhUvEBYAD8LE1fMcXiNWj0BUU70gnuxfsooVxtgKnQ8xpsA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b8377160>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2789, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-01-26 17:15:48,667 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:49,238 ERROR   wandb-upload_1:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789754/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=I0vnNTk3C4YYdBgtMfwmQt%2BN8Lus3%2F4w8VM6WNlRb2Ai4CEnDRUeVbzlD0NuvjH5mNQ6xLFdxL%2FU1Jkge%2BluFp17GxLZWBSeOHXHy9BpeBF9xdDga0Pu2gp0fauomM57kqhTz%2B%2FehO6PCeqLuHBxLP1vexGUpkK4eeJt%2FOff5fdLE52gDrMtaUHA2DPZ0iU%2FJ2Gbok2X1Hfq4NPx5KLb67fRWM4knvf0mSdbt1euh8mGmPsxWnzfGMG4Myur2Xj6P8TR%2BDZwyzJLcG6rQXKl60hKRz2DHO5NqbeEKRqtxJZPAOoPAf60Jw9mbh6QFZZ2g9MJBm8ObS3n7CeQH6y5ZA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789754/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=I0vnNTk3C4YYdBgtMfwmQt%2BN8Lus3%2F4w8VM6WNlRb2Ai4CEnDRUeVbzlD0NuvjH5mNQ6xLFdxL%2FU1Jkge%2BluFp17GxLZWBSeOHXHy9BpeBF9xdDga0Pu2gp0fauomM57kqhTz%2B%2FehO6PCeqLuHBxLP1vexGUpkK4eeJt%2FOff5fdLE52gDrMtaUHA2DPZ0iU%2FJ2Gbok2X1Hfq4NPx5KLb67fRWM4knvf0mSdbt1euh8mGmPsxWnzfGMG4Myur2Xj6P8TR%2BDZwyzJLcG6rQXKl60hKRz2DHO5NqbeEKRqtxJZPAOoPAf60Jw9mbh6QFZZ2g9MJBm8ObS3n7CeQH6y5ZA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b815d760>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:49,238 ERROR   wandb-upload_1:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:49,238 ERROR   wandb-upload_1:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:49,766 ERROR   wandb-upload_2:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789754/6873c23a2381d1524249eb1a948a45a5?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cHJXNLLOEIAbhu3yjIpNmYJmRp6%2Fv3A3FnKTzWRDFh0IARMQ8RrAzUHdWVUPOQAiR8V8iJn8J3EIXiEyFWpToEH3Zr6sHpA0qqPKwibXhjlIrLPV9tqi0rMr4mzgKoVfPXz5k0wrLMrqyxjuyv4gvjY65rDdbuUfiOPJQFYZvwDbVW79VbTcEwTzHYWfaQCn2p%2FBXWS3WzV9P%2BVsmOF1dSmavLPgZq%2Fr%2FXn8GqJjq3SUOLcDfwBEZIZUNAdThbZkXn1BStz%2BuPIu%2FcsF2psg%2BLWyyhEXiitM0AzTduNjhUvEBYAD8LE1fMcXiNWj0BUU70gnuxfsooVxtgKnQ8xpsA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789754/6873c23a2381d1524249eb1a948a45a5?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cHJXNLLOEIAbhu3yjIpNmYJmRp6%2Fv3A3FnKTzWRDFh0IARMQ8RrAzUHdWVUPOQAiR8V8iJn8J3EIXiEyFWpToEH3Zr6sHpA0qqPKwibXhjlIrLPV9tqi0rMr4mzgKoVfPXz5k0wrLMrqyxjuyv4gvjY65rDdbuUfiOPJQFYZvwDbVW79VbTcEwTzHYWfaQCn2p%2FBXWS3WzV9P%2BVsmOF1dSmavLPgZq%2Fr%2FXn8GqJjq3SUOLcDfwBEZIZUNAdThbZkXn1BStz%2BuPIu%2FcsF2psg%2BLWyyhEXiitM0AzTduNjhUvEBYAD8LE1fMcXiNWj0BUU70gnuxfsooVxtgKnQ8xpsA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b8377d30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:49,766 ERROR   wandb-upload_2:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:49,766 ERROR   wandb-upload_2:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:53,283 ERROR   wandb-upload_1:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789754/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=I0vnNTk3C4YYdBgtMfwmQt%2BN8Lus3%2F4w8VM6WNlRb2Ai4CEnDRUeVbzlD0NuvjH5mNQ6xLFdxL%2FU1Jkge%2BluFp17GxLZWBSeOHXHy9BpeBF9xdDga0Pu2gp0fauomM57kqhTz%2B%2FehO6PCeqLuHBxLP1vexGUpkK4eeJt%2FOff5fdLE52gDrMtaUHA2DPZ0iU%2FJ2Gbok2X1Hfq4NPx5KLb67fRWM4knvf0mSdbt1euh8mGmPsxWnzfGMG4Myur2Xj6P8TR%2BDZwyzJLcG6rQXKl60hKRz2DHO5NqbeEKRqtxJZPAOoPAf60Jw9mbh6QFZZ2g9MJBm8ObS3n7CeQH6y5ZA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789754/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=I0vnNTk3C4YYdBgtMfwmQt%2BN8Lus3%2F4w8VM6WNlRb2Ai4CEnDRUeVbzlD0NuvjH5mNQ6xLFdxL%2FU1Jkge%2BluFp17GxLZWBSeOHXHy9BpeBF9xdDga0Pu2gp0fauomM57kqhTz%2B%2FehO6PCeqLuHBxLP1vexGUpkK4eeJt%2FOff5fdLE52gDrMtaUHA2DPZ0iU%2FJ2Gbok2X1Hfq4NPx5KLb67fRWM4knvf0mSdbt1euh8mGmPsxWnzfGMG4Myur2Xj6P8TR%2BDZwyzJLcG6rQXKl60hKRz2DHO5NqbeEKRqtxJZPAOoPAf60Jw9mbh6QFZZ2g9MJBm8ObS3n7CeQH6y5ZA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b8377be0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:53,283 ERROR   wandb-upload_1:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:15:53,283 ERROR   wandb-upload_1:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:53,669 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:15:54,689 ERROR   wandb-upload_2:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789754/6873c23a2381d1524249eb1a948a45a5?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cHJXNLLOEIAbhu3yjIpNmYJmRp6%2Fv3A3FnKTzWRDFh0IARMQ8RrAzUHdWVUPOQAiR8V8iJn8J3EIXiEyFWpToEH3Zr6sHpA0qqPKwibXhjlIrLPV9tqi0rMr4mzgKoVfPXz5k0wrLMrqyxjuyv4gvjY65rDdbuUfiOPJQFYZvwDbVW79VbTcEwTzHYWfaQCn2p%2FBXWS3WzV9P%2BVsmOF1dSmavLPgZq%2Fr%2FXn8GqJjq3SUOLcDfwBEZIZUNAdThbZkXn1BStz%2BuPIu%2FcsF2psg%2BLWyyhEXiitM0AzTduNjhUvEBYAD8LE1fMcXiNWj0BUU70gnuxfsooVxtgKnQ8xpsA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789754/6873c23a2381d1524249eb1a948a45a5?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cHJXNLLOEIAbhu3yjIpNmYJmRp6%2Fv3A3FnKTzWRDFh0IARMQ8RrAzUHdWVUPOQAiR8V8iJn8J3EIXiEyFWpToEH3Zr6sHpA0qqPKwibXhjlIrLPV9tqi0rMr4mzgKoVfPXz5k0wrLMrqyxjuyv4gvjY65rDdbuUfiOPJQFYZvwDbVW79VbTcEwTzHYWfaQCn2p%2FBXWS3WzV9P%2BVsmOF1dSmavLPgZq%2Fr%2FXn8GqJjq3SUOLcDfwBEZIZUNAdThbZkXn1BStz%2BuPIu%2FcsF2psg%2BLWyyhEXiitM0AzTduNjhUvEBYAD8LE1fMcXiNWj0BUU70gnuxfsooVxtgKnQ8xpsA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b81b7070>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:15:54,689 ERROR   wandb-upload_2:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:15:54,689 ERROR   wandb-upload_2:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:15:58,671 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:01,439 ERROR   wandb-upload_1:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789754/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=I0vnNTk3C4YYdBgtMfwmQt%2BN8Lus3%2F4w8VM6WNlRb2Ai4CEnDRUeVbzlD0NuvjH5mNQ6xLFdxL%2FU1Jkge%2BluFp17GxLZWBSeOHXHy9BpeBF9xdDga0Pu2gp0fauomM57kqhTz%2B%2FehO6PCeqLuHBxLP1vexGUpkK4eeJt%2FOff5fdLE52gDrMtaUHA2DPZ0iU%2FJ2Gbok2X1Hfq4NPx5KLb67fRWM4knvf0mSdbt1euh8mGmPsxWnzfGMG4Myur2Xj6P8TR%2BDZwyzJLcG6rQXKl60hKRz2DHO5NqbeEKRqtxJZPAOoPAf60Jw9mbh6QFZZ2g9MJBm8ObS3n7CeQH6y5ZA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789754/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=I0vnNTk3C4YYdBgtMfwmQt%2BN8Lus3%2F4w8VM6WNlRb2Ai4CEnDRUeVbzlD0NuvjH5mNQ6xLFdxL%2FU1Jkge%2BluFp17GxLZWBSeOHXHy9BpeBF9xdDga0Pu2gp0fauomM57kqhTz%2B%2FehO6PCeqLuHBxLP1vexGUpkK4eeJt%2FOff5fdLE52gDrMtaUHA2DPZ0iU%2FJ2Gbok2X1Hfq4NPx5KLb67fRWM4knvf0mSdbt1euh8mGmPsxWnzfGMG4Myur2Xj6P8TR%2BDZwyzJLcG6rQXKl60hKRz2DHO5NqbeEKRqtxJZPAOoPAf60Jw9mbh6QFZZ2g9MJBm8ObS3n7CeQH6y5ZA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b815d6a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:16:01,439 ERROR   wandb-upload_1:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:16:01,439 ERROR   wandb-upload_1:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:03,672 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:03,740 ERROR   wandb-upload_2:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789754/6873c23a2381d1524249eb1a948a45a5?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cHJXNLLOEIAbhu3yjIpNmYJmRp6%2Fv3A3FnKTzWRDFh0IARMQ8RrAzUHdWVUPOQAiR8V8iJn8J3EIXiEyFWpToEH3Zr6sHpA0qqPKwibXhjlIrLPV9tqi0rMr4mzgKoVfPXz5k0wrLMrqyxjuyv4gvjY65rDdbuUfiOPJQFYZvwDbVW79VbTcEwTzHYWfaQCn2p%2FBXWS3WzV9P%2BVsmOF1dSmavLPgZq%2Fr%2FXn8GqJjq3SUOLcDfwBEZIZUNAdThbZkXn1BStz%2BuPIu%2FcsF2psg%2BLWyyhEXiitM0AzTduNjhUvEBYAD8LE1fMcXiNWj0BUU70gnuxfsooVxtgKnQ8xpsA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789754/6873c23a2381d1524249eb1a948a45a5?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cHJXNLLOEIAbhu3yjIpNmYJmRp6%2Fv3A3FnKTzWRDFh0IARMQ8RrAzUHdWVUPOQAiR8V8iJn8J3EIXiEyFWpToEH3Zr6sHpA0qqPKwibXhjlIrLPV9tqi0rMr4mzgKoVfPXz5k0wrLMrqyxjuyv4gvjY65rDdbuUfiOPJQFYZvwDbVW79VbTcEwTzHYWfaQCn2p%2FBXWS3WzV9P%2BVsmOF1dSmavLPgZq%2Fr%2FXn8GqJjq3SUOLcDfwBEZIZUNAdThbZkXn1BStz%2BuPIu%2FcsF2psg%2BLWyyhEXiitM0AzTduNjhUvEBYAD8LE1fMcXiNWj0BUU70gnuxfsooVxtgKnQ8xpsA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b815da60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:16:03,740 ERROR   wandb-upload_2:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:16:03,741 ERROR   wandb-upload_2:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:08,675 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:13,677 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:18,203 ERROR   wandb-upload_1:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789754/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=I0vnNTk3C4YYdBgtMfwmQt%2BN8Lus3%2F4w8VM6WNlRb2Ai4CEnDRUeVbzlD0NuvjH5mNQ6xLFdxL%2FU1Jkge%2BluFp17GxLZWBSeOHXHy9BpeBF9xdDga0Pu2gp0fauomM57kqhTz%2B%2FehO6PCeqLuHBxLP1vexGUpkK4eeJt%2FOff5fdLE52gDrMtaUHA2DPZ0iU%2FJ2Gbok2X1Hfq4NPx5KLb67fRWM4knvf0mSdbt1euh8mGmPsxWnzfGMG4Myur2Xj6P8TR%2BDZwyzJLcG6rQXKl60hKRz2DHO5NqbeEKRqtxJZPAOoPAf60Jw9mbh6QFZZ2g9MJBm8ObS3n7CeQH6y5ZA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789754/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=I0vnNTk3C4YYdBgtMfwmQt%2BN8Lus3%2F4w8VM6WNlRb2Ai4CEnDRUeVbzlD0NuvjH5mNQ6xLFdxL%2FU1Jkge%2BluFp17GxLZWBSeOHXHy9BpeBF9xdDga0Pu2gp0fauomM57kqhTz%2B%2FehO6PCeqLuHBxLP1vexGUpkK4eeJt%2FOff5fdLE52gDrMtaUHA2DPZ0iU%2FJ2Gbok2X1Hfq4NPx5KLb67fRWM4knvf0mSdbt1euh8mGmPsxWnzfGMG4Myur2Xj6P8TR%2BDZwyzJLcG6rQXKl60hKRz2DHO5NqbeEKRqtxJZPAOoPAf60Jw9mbh6QFZZ2g9MJBm8ObS3n7CeQH6y5ZA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b816a2e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:16:18,203 ERROR   wandb-upload_1:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:16:18,203 ERROR   wandb-upload_1:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:18,679 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:21,986 ERROR   wandb-upload_2:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789754/6873c23a2381d1524249eb1a948a45a5?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cHJXNLLOEIAbhu3yjIpNmYJmRp6%2Fv3A3FnKTzWRDFh0IARMQ8RrAzUHdWVUPOQAiR8V8iJn8J3EIXiEyFWpToEH3Zr6sHpA0qqPKwibXhjlIrLPV9tqi0rMr4mzgKoVfPXz5k0wrLMrqyxjuyv4gvjY65rDdbuUfiOPJQFYZvwDbVW79VbTcEwTzHYWfaQCn2p%2FBXWS3WzV9P%2BVsmOF1dSmavLPgZq%2Fr%2FXn8GqJjq3SUOLcDfwBEZIZUNAdThbZkXn1BStz%2BuPIu%2FcsF2psg%2BLWyyhEXiitM0AzTduNjhUvEBYAD8LE1fMcXiNWj0BUU70gnuxfsooVxtgKnQ8xpsA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789754/6873c23a2381d1524249eb1a948a45a5?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cHJXNLLOEIAbhu3yjIpNmYJmRp6%2Fv3A3FnKTzWRDFh0IARMQ8RrAzUHdWVUPOQAiR8V8iJn8J3EIXiEyFWpToEH3Zr6sHpA0qqPKwibXhjlIrLPV9tqi0rMr4mzgKoVfPXz5k0wrLMrqyxjuyv4gvjY65rDdbuUfiOPJQFYZvwDbVW79VbTcEwTzHYWfaQCn2p%2FBXWS3WzV9P%2BVsmOF1dSmavLPgZq%2Fr%2FXn8GqJjq3SUOLcDfwBEZIZUNAdThbZkXn1BStz%2BuPIu%2FcsF2psg%2BLWyyhEXiitM0AzTduNjhUvEBYAD8LE1fMcXiNWj0BUU70gnuxfsooVxtgKnQ8xpsA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b8173250>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:16:21,987 ERROR   wandb-upload_2:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:16:21,987 ERROR   wandb-upload_2:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:23,681 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:28,683 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:33,685 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:38,687 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:43,689 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:48,691 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:53,694 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:16:55,870 ERROR   wandb-upload_2:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789754/6873c23a2381d1524249eb1a948a45a5?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cHJXNLLOEIAbhu3yjIpNmYJmRp6%2Fv3A3FnKTzWRDFh0IARMQ8RrAzUHdWVUPOQAiR8V8iJn8J3EIXiEyFWpToEH3Zr6sHpA0qqPKwibXhjlIrLPV9tqi0rMr4mzgKoVfPXz5k0wrLMrqyxjuyv4gvjY65rDdbuUfiOPJQFYZvwDbVW79VbTcEwTzHYWfaQCn2p%2FBXWS3WzV9P%2BVsmOF1dSmavLPgZq%2Fr%2FXn8GqJjq3SUOLcDfwBEZIZUNAdThbZkXn1BStz%2BuPIu%2FcsF2psg%2BLWyyhEXiitM0AzTduNjhUvEBYAD8LE1fMcXiNWj0BUU70gnuxfsooVxtgKnQ8xpsA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789754/6873c23a2381d1524249eb1a948a45a5?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cHJXNLLOEIAbhu3yjIpNmYJmRp6%2Fv3A3FnKTzWRDFh0IARMQ8RrAzUHdWVUPOQAiR8V8iJn8J3EIXiEyFWpToEH3Zr6sHpA0qqPKwibXhjlIrLPV9tqi0rMr4mzgKoVfPXz5k0wrLMrqyxjuyv4gvjY65rDdbuUfiOPJQFYZvwDbVW79VbTcEwTzHYWfaQCn2p%2FBXWS3WzV9P%2BVsmOF1dSmavLPgZq%2Fr%2FXn8GqJjq3SUOLcDfwBEZIZUNAdThbZkXn1BStz%2BuPIu%2FcsF2psg%2BLWyyhEXiitM0AzTduNjhUvEBYAD8LE1fMcXiNWj0BUU70gnuxfsooVxtgKnQ8xpsA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b815d3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:16:55,871 ERROR   wandb-upload_2:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:16:55,871 ERROR   wandb-upload_2:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:56,073 ERROR   wandb-upload_1:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789754/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=I0vnNTk3C4YYdBgtMfwmQt%2BN8Lus3%2F4w8VM6WNlRb2Ai4CEnDRUeVbzlD0NuvjH5mNQ6xLFdxL%2FU1Jkge%2BluFp17GxLZWBSeOHXHy9BpeBF9xdDga0Pu2gp0fauomM57kqhTz%2B%2FehO6PCeqLuHBxLP1vexGUpkK4eeJt%2FOff5fdLE52gDrMtaUHA2DPZ0iU%2FJ2Gbok2X1Hfq4NPx5KLb67fRWM4knvf0mSdbt1euh8mGmPsxWnzfGMG4Myur2Xj6P8TR%2BDZwyzJLcG6rQXKl60hKRz2DHO5NqbeEKRqtxJZPAOoPAf60Jw9mbh6QFZZ2g9MJBm8ObS3n7CeQH6y5ZA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789754/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=I0vnNTk3C4YYdBgtMfwmQt%2BN8Lus3%2F4w8VM6WNlRb2Ai4CEnDRUeVbzlD0NuvjH5mNQ6xLFdxL%2FU1Jkge%2BluFp17GxLZWBSeOHXHy9BpeBF9xdDga0Pu2gp0fauomM57kqhTz%2B%2FehO6PCeqLuHBxLP1vexGUpkK4eeJt%2FOff5fdLE52gDrMtaUHA2DPZ0iU%2FJ2Gbok2X1Hfq4NPx5KLb67fRWM4knvf0mSdbt1euh8mGmPsxWnzfGMG4Myur2Xj6P8TR%2BDZwyzJLcG6rQXKl60hKRz2DHO5NqbeEKRqtxJZPAOoPAf60Jw9mbh6QFZZ2g9MJBm8ObS3n7CeQH6y5ZA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b815d250>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:16:56,073 ERROR   wandb-upload_1:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:16:56,073 ERROR   wandb-upload_1:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:16:58,696 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:03,698 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:08,700 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:13,702 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:18,705 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:23,707 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:28,710 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:33,712 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:38,714 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:43,716 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:48,719 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:53,721 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:17:58,723 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:03,725 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:08,727 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:11,837 ERROR   wandb-upload_2:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789754/6873c23a2381d1524249eb1a948a45a5?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cHJXNLLOEIAbhu3yjIpNmYJmRp6%2Fv3A3FnKTzWRDFh0IARMQ8RrAzUHdWVUPOQAiR8V8iJn8J3EIXiEyFWpToEH3Zr6sHpA0qqPKwibXhjlIrLPV9tqi0rMr4mzgKoVfPXz5k0wrLMrqyxjuyv4gvjY65rDdbuUfiOPJQFYZvwDbVW79VbTcEwTzHYWfaQCn2p%2FBXWS3WzV9P%2BVsmOF1dSmavLPgZq%2Fr%2FXn8GqJjq3SUOLcDfwBEZIZUNAdThbZkXn1BStz%2BuPIu%2FcsF2psg%2BLWyyhEXiitM0AzTduNjhUvEBYAD8LE1fMcXiNWj0BUU70gnuxfsooVxtgKnQ8xpsA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789754/6873c23a2381d1524249eb1a948a45a5?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cHJXNLLOEIAbhu3yjIpNmYJmRp6%2Fv3A3FnKTzWRDFh0IARMQ8RrAzUHdWVUPOQAiR8V8iJn8J3EIXiEyFWpToEH3Zr6sHpA0qqPKwibXhjlIrLPV9tqi0rMr4mzgKoVfPXz5k0wrLMrqyxjuyv4gvjY65rDdbuUfiOPJQFYZvwDbVW79VbTcEwTzHYWfaQCn2p%2FBXWS3WzV9P%2BVsmOF1dSmavLPgZq%2Fr%2FXn8GqJjq3SUOLcDfwBEZIZUNAdThbZkXn1BStz%2BuPIu%2FcsF2psg%2BLWyyhEXiitM0AzTduNjhUvEBYAD8LE1fMcXiNWj0BUU70gnuxfsooVxtgKnQ8xpsA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b816e160>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:18:11,837 ERROR   wandb-upload_2:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'aHPCOiOB0VJCSesalIpFpQ==', 'Content-Type': 'application/json', 'Content-Length': '609'}
2024-01-26 17:18:11,837 ERROR   wandb-upload_2:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:18:13,380 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/b2arb4hk/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lqiK6NPhItf%2B7BfwSHGQQ2bjZgAilIu5z2bDPKlOTZdVQ7H17h8N72yrarsPy2B8BXSCJ6uMNvG55x03MteEJY86yVTo4%2FNO5QNRK26yt9PLjnpLmMgJUWWLRDkA%2Fj9jL4VdWmXKM%2B8p04wBnJiShJ9J9GhtUefMwQOg%2B6k2Cb0o37SZCVgTKvnoGkAGEwZKox6DpycClF2nZStVfz9175fBqjglTVPIcGtutzkWRkfPxxNXJafgtZVyYt1bsnalw7LkL9iEN9xEbX55lGE6Mgj%2B%2Bv8Vg3H3OMXJFwPX%2BOFyMHyI7M4%2FksG0%2FBAXsXGHAdDlXIbd88A4zttGkF7wjQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/b2arb4hk/wandb-metadata.json?Expires=1706346538&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lqiK6NPhItf%2B7BfwSHGQQ2bjZgAilIu5z2bDPKlOTZdVQ7H17h8N72yrarsPy2B8BXSCJ6uMNvG55x03MteEJY86yVTo4%2FNO5QNRK26yt9PLjnpLmMgJUWWLRDkA%2Fj9jL4VdWmXKM%2B8p04wBnJiShJ9J9GhtUefMwQOg%2B6k2Cb0o37SZCVgTKvnoGkAGEwZKox6DpycClF2nZStVfz9175fBqjglTVPIcGtutzkWRkfPxxNXJafgtZVyYt1bsnalw7LkL9iEN9xEbX55lGE6Mgj%2B%2Bv8Vg3H3OMXJFwPX%2BOFyMHyI7M4%2FksG0%2FBAXsXGHAdDlXIbd88A4zttGkF7wjQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b814a940>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:18:13,380 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15651'}
2024-01-26 17:18:13,380 ERROR   wandb-upload_0:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:18:13,699 ERROR   wandb-upload_1:3042421 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/133981200/703789754/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=I0vnNTk3C4YYdBgtMfwmQt%2BN8Lus3%2F4w8VM6WNlRb2Ai4CEnDRUeVbzlD0NuvjH5mNQ6xLFdxL%2FU1Jkge%2BluFp17GxLZWBSeOHXHy9BpeBF9xdDga0Pu2gp0fauomM57kqhTz%2B%2FehO6PCeqLuHBxLP1vexGUpkK4eeJt%2FOff5fdLE52gDrMtaUHA2DPZ0iU%2FJ2Gbok2X1Hfq4NPx5KLb67fRWM4knvf0mSdbt1euh8mGmPsxWnzfGMG4Myur2Xj6P8TR%2BDZwyzJLcG6rQXKl60hKRz2DHO5NqbeEKRqtxJZPAOoPAf60Jw9mbh6QFZZ2g9MJBm8ObS3n7CeQH6y5ZA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/133981200/703789754/4c5eecce3762d6201f9f2c7c9b21094b?Expires=1706346945&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=I0vnNTk3C4YYdBgtMfwmQt%2BN8Lus3%2F4w8VM6WNlRb2Ai4CEnDRUeVbzlD0NuvjH5mNQ6xLFdxL%2FU1Jkge%2BluFp17GxLZWBSeOHXHy9BpeBF9xdDga0Pu2gp0fauomM57kqhTz%2B%2FehO6PCeqLuHBxLP1vexGUpkK4eeJt%2FOff5fdLE52gDrMtaUHA2DPZ0iU%2FJ2Gbok2X1Hfq4NPx5KLb67fRWM4knvf0mSdbt1euh8mGmPsxWnzfGMG4Myur2Xj6P8TR%2BDZwyzJLcG6rQXKl60hKRz2DHO5NqbeEKRqtxJZPAOoPAf60Jw9mbh6QFZZ2g9MJBm8ObS3n7CeQH6y5ZA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22b814a7f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:18:13,699 ERROR   wandb-upload_1:3042421 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'TF7szjdi1iAfnyx8myEJSw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1292'}
2024-01-26 17:18:13,699 ERROR   wandb-upload_1:3042421 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:18:13,729 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:18,731 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:23,732 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:28,735 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:33,736 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:38,738 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:43,740 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:48,742 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:53,744 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:18:58,747 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:03,749 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:08,751 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:13,752 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:18,755 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:23,756 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:28,759 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:33,761 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:38,762 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:43,764 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:48,766 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:53,768 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:19:58,770 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:03,771 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:08,773 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:13,775 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:18,777 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:21,993 INFO    wandb-upload_2:3042421 [upload_job.py:push():89] Uploaded file /home/yanxindong/.local/share/wandb/artifacts/staging/tmptfgmia9f
2024-01-26 17:20:23,779 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:28,781 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:33,783 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:38,785 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:43,787 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:45,530 INFO    wandb-upload_1:3042421 [upload_job.py:push():89] Uploaded file /home/yanxindong/.local/share/wandb/artifacts/staging/tmp81_9pcty
2024-01-26 17:20:47,195 ERROR   Thread-11 :3042421 [internal_api.py:execute():373] 500 response executing GraphQL.
2024-01-26 17:20:47,195 ERROR   Thread-11 :3042421 [internal_api.py:execute():374] {"errors":[{"message":"An internal error occurred. Please contact support.","path":["commitArtifact"]}],"data":{"commitArtifact":null}}
2024-01-26 17:20:48,789 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:20:49,247 INFO    SenderThread:3042421 [sender.py:send_artifact():1494] sent artifact job-https___github.com_kkkjj-d_mkor.git_bert_run_pretraining.py - {'id': 'QXJ0aWZhY3Q6NzAzNzg5NzU0', 'state': 'PENDING', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjEzMzk4MTIwMA==', 'latestArtifact': None}}
2024-01-26 17:20:49,247 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: defer
2024-01-26 17:20:49,247 INFO    SenderThread:3042421 [sender.py:send_request_defer():613] handle sender defer: 9
2024-01-26 17:20:49,247 INFO    SenderThread:3042421 [dir_watcher.py:finish():358] shutting down directory watcher
2024-01-26 17:20:49,247 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:20:49,968 INFO    SenderThread:3042421 [dir_watcher.py:finish():388] scan: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/files
2024-01-26 17:20:49,968 INFO    SenderThread:3042421 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/files/wandb-summary.json wandb-summary.json
2024-01-26 17:20:49,969 INFO    SenderThread:3042421 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/files/conda-environment.yaml conda-environment.yaml
2024-01-26 17:20:49,969 INFO    SenderThread:3042421 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/files/wandb-metadata.json wandb-metadata.json
2024-01-26 17:20:49,969 INFO    SenderThread:3042421 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/files/output.log output.log
2024-01-26 17:20:49,977 INFO    SenderThread:3042421 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/files/requirements.txt requirements.txt
2024-01-26 17:20:49,980 INFO    SenderThread:3042421 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/files/config.yaml config.yaml
2024-01-26 17:20:49,980 INFO    SenderThread:3042421 [sender.py:transition_state():617] send defer: 10
2024-01-26 17:20:49,980 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:49,980 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:20:49,980 INFO    HandlerThread:3042421 [handler.py:handle_request_defer():172] handle defer: 10
2024-01-26 17:20:49,982 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: defer
2024-01-26 17:20:49,984 INFO    SenderThread:3042421 [sender.py:send_request_defer():613] handle sender defer: 10
2024-01-26 17:20:49,984 INFO    SenderThread:3042421 [file_pusher.py:finish():175] shutting down file pusher
2024-01-26 17:20:50,617 INFO    wandb-upload_2:3042421 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/files/wandb-summary.json
2024-01-26 17:20:50,790 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:50,791 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:51,120 INFO    wandb-upload_3:3042421 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/files/output.log
2024-01-26 17:20:51,163 INFO    wandb-upload_5:3042421 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/files/config.yaml
2024-01-26 17:20:51,298 INFO    wandb-upload_4:3042421 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/files/requirements.txt
2024-01-26 17:20:51,791 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:51,791 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:51,876 INFO    wandb-upload_1:3042421 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/files/conda-environment.yaml
2024-01-26 17:20:52,792 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:52,793 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:53,792 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:53,793 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:54,793 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:54,794 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:20:54,794 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:55,794 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:55,794 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:56,795 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:56,795 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:57,795 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:57,796 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:58,796 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:58,797 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:59,796 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:20:59,797 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:20:59,798 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:00,797 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:00,797 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:01,798 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:01,798 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:02,799 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:02,799 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:03,800 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:03,801 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:04,801 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:04,801 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:04,802 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:05,802 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:05,803 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:06,803 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:06,804 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:07,804 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:07,805 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:08,805 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:08,805 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:09,806 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:09,806 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:09,807 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:10,807 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:10,808 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:11,808 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:11,808 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:12,808 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:12,808 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:13,808 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:13,809 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:14,809 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:14,810 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:14,810 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:15,810 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:15,811 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:16,812 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:16,812 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:17,812 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:17,812 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:18,813 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:18,813 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:19,813 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:19,814 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:19,815 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:20,815 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:20,815 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:21,815 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:21,816 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:22,816 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:22,817 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:23,817 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:23,817 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:24,818 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:24,818 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:24,818 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:25,818 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:25,819 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:26,819 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:26,819 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:27,819 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:27,820 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:28,820 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:28,821 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:29,821 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:29,822 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:29,822 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:30,823 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:30,823 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:31,823 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:31,823 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:32,824 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:32,825 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:33,824 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:33,825 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:34,826 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:34,826 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:34,826 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:35,826 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:35,826 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:36,827 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:36,828 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:37,828 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:37,828 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:38,829 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:38,830 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:39,830 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:39,830 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:39,831 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:40,832 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:40,833 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:41,833 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:41,833 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:42,833 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:42,833 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:43,834 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:43,834 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:44,834 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:44,834 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:44,834 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:45,834 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:45,835 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:46,835 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:46,835 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:47,835 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:47,836 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:48,837 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:48,837 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:49,837 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:49,837 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:49,838 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:50,838 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:50,838 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:51,838 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:51,839 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:52,839 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:52,840 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:53,841 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:53,841 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:54,842 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:54,842 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:21:54,843 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:55,842 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:55,843 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:56,843 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:56,844 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:57,844 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:57,845 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:58,845 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:58,846 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:59,846 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:21:59,847 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:21:59,848 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:00,847 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:00,848 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:01,848 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:01,849 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:02,849 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:02,849 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:03,850 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:03,851 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:04,850 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:04,851 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:04,852 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:05,851 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:05,852 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:06,852 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:06,853 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:07,852 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:07,853 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:08,853 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:08,855 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:09,853 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:09,854 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:09,854 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:10,854 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:10,854 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:11,854 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:11,854 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:12,855 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:12,855 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:13,855 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:13,856 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:14,857 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:14,857 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:14,858 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:15,857 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:15,858 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:16,858 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:16,859 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:17,859 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:17,860 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:18,861 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:18,862 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:19,861 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:19,862 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:19,863 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:20,863 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:20,863 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:21,864 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:21,864 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:22,865 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:22,866 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:23,865 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:23,865 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:24,866 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:24,867 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:24,868 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:25,868 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:25,869 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:26,868 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:26,869 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:27,869 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:27,870 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:28,870 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:28,870 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:29,871 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:29,871 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:29,872 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:30,872 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:30,873 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:31,873 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:31,873 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:32,873 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:32,874 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:33,874 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:33,874 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:34,875 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:34,875 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:34,876 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:35,876 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:35,876 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:36,876 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:36,877 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:37,877 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:37,878 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:38,878 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:38,879 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:39,878 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:39,879 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:39,879 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:40,880 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:40,881 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:41,880 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:41,881 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:42,882 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:42,883 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:43,883 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:43,884 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:44,884 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:44,884 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:44,885 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:45,885 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:45,886 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:46,885 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:46,885 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:47,887 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:47,888 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:48,887 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:48,889 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:49,889 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:49,890 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:49,891 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:50,890 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:50,891 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:51,891 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:51,892 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:52,892 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:52,892 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:53,892 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:53,893 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:54,893 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:54,894 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:54,894 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:22:55,894 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:55,894 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:56,895 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:56,895 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:57,895 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:57,895 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:58,896 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:58,896 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:59,897 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:22:59,897 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:22:59,898 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:00,897 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:00,898 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:01,899 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:01,899 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:02,899 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:02,900 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:03,900 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:03,901 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:04,901 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:04,902 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:04,902 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:05,902 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:05,903 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:06,903 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:06,903 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:07,903 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:07,904 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:08,904 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:08,905 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:09,905 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:09,905 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:09,906 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:10,907 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:10,907 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:11,908 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:11,909 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:12,909 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:12,909 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:13,909 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:13,910 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:14,910 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:14,910 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:14,910 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:15,910 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:15,910 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:16,911 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:16,912 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:17,912 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:17,913 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:18,914 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:18,915 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:19,915 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:19,916 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:19,916 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:20,916 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:20,916 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:21,916 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:21,917 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:22,917 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:22,918 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:23,918 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:23,919 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:24,918 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:24,919 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:24,920 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:25,919 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:25,919 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:26,920 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:26,920 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:27,921 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:27,921 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:28,921 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:28,922 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:29,922 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:29,923 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:29,924 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:30,923 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:30,924 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:31,924 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:31,924 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:32,924 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:32,925 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:33,925 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:33,926 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:34,926 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:34,926 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:34,927 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:35,926 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:35,926 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:36,927 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:36,928 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:37,928 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:37,929 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:38,928 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:38,929 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:39,930 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:39,930 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:39,931 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:40,930 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:40,931 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:41,930 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:41,931 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:42,931 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:42,931 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:43,932 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:43,933 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:44,932 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:44,932 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:44,933 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:45,933 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:45,934 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:46,934 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:46,935 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:47,935 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:47,936 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:48,936 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:48,936 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:49,936 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:49,937 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:49,937 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:23:50,938 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:50,939 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:51,939 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:51,939 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:52,244 INFO    wandb-upload_0:3042421 [upload_job.py:push():131] Uploaded file /tmp/tmpt9lk7s81wandb/p1pknh3u-wandb-metadata.json
2024-01-26 17:23:52,445 INFO    Thread-11 :3042421 [sender.py:transition_state():617] send defer: 11
2024-01-26 17:23:52,445 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:23:52,445 INFO    HandlerThread:3042421 [handler.py:handle_request_defer():172] handle defer: 11
2024-01-26 17:23:52,446 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: defer
2024-01-26 17:23:52,446 INFO    SenderThread:3042421 [sender.py:send_request_defer():613] handle sender defer: 11
2024-01-26 17:23:52,446 INFO    SenderThread:3042421 [file_pusher.py:join():181] waiting for file pusher
2024-01-26 17:23:52,446 INFO    SenderThread:3042421 [sender.py:transition_state():617] send defer: 12
2024-01-26 17:23:52,446 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:23:52,446 INFO    HandlerThread:3042421 [handler.py:handle_request_defer():172] handle defer: 12
2024-01-26 17:23:52,447 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: defer
2024-01-26 17:23:52,447 INFO    SenderThread:3042421 [sender.py:send_request_defer():613] handle sender defer: 12
2024-01-26 17:23:52,447 INFO    SenderThread:3042421 [file_stream.py:finish():595] file stream finish called
2024-01-26 17:23:52,753 INFO    SenderThread:3042421 [file_stream.py:finish():599] file stream finish is done
2024-01-26 17:23:52,754 INFO    SenderThread:3042421 [sender.py:transition_state():617] send defer: 13
2024-01-26 17:23:52,754 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:23:52,754 INFO    HandlerThread:3042421 [handler.py:handle_request_defer():172] handle defer: 13
2024-01-26 17:23:52,754 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: defer
2024-01-26 17:23:52,754 INFO    SenderThread:3042421 [sender.py:send_request_defer():613] handle sender defer: 13
2024-01-26 17:23:52,754 INFO    SenderThread:3042421 [sender.py:transition_state():617] send defer: 14
2024-01-26 17:23:52,754 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: defer
2024-01-26 17:23:52,755 INFO    HandlerThread:3042421 [handler.py:handle_request_defer():172] handle defer: 14
2024-01-26 17:23:52,755 DEBUG   SenderThread:3042421 [sender.py:send():382] send: final
2024-01-26 17:23:52,755 DEBUG   SenderThread:3042421 [sender.py:send():382] send: footer
2024-01-26 17:23:52,755 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: defer
2024-01-26 17:23:52,755 INFO    SenderThread:3042421 [sender.py:send_request_defer():613] handle sender defer: 14
2024-01-26 17:23:52,755 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:52,756 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:52,756 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: poll_exit
2024-01-26 17:23:52,756 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: poll_exit
2024-01-26 17:23:52,756 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: server_info
2024-01-26 17:23:52,757 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: server_info
2024-01-26 17:23:52,757 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: get_summary
2024-01-26 17:23:52,760 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: sampled_history
2024-01-26 17:23:52,760 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:23:52,760 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: job_info
2024-01-26 17:23:53,025 DEBUG   SenderThread:3042421 [sender.py:send_request():409] send_request: job_info
2024-01-26 17:23:53,025 INFO    MainThread:3042421 [wandb_run.py:_footer_history_summary_info():3857] rendering history
2024-01-26 17:23:53,026 INFO    MainThread:3042421 [wandb_run.py:_footer_history_summary_info():3889] rendering summary
2024-01-26 17:23:53,026 INFO    MainThread:3042421 [wandb_run.py:_footer_sync_info():3816] logging synced files
2024-01-26 17:23:53,027 DEBUG   HandlerThread:3042421 [handler.py:handle_request():146] handle_request: shutdown
2024-01-26 17:23:53,027 INFO    HandlerThread:3042421 [handler.py:finish():869] shutting down handler
2024-01-26 17:23:53,760 INFO    WriterThread:3042421 [datastore.py:close():296] close: /home/yanxindong/mkor/bert/wandb/run-20240126_170845-b2arb4hk/run-b2arb4hk.wandb
2024-01-26 17:23:54,025 INFO    SenderThread:3042421 [sender.py:finish():1572] shutting down sender
2024-01-26 17:23:54,025 INFO    SenderThread:3042421 [file_pusher.py:finish():175] shutting down file pusher
2024-01-26 17:23:54,025 INFO    SenderThread:3042421 [file_pusher.py:join():181] waiting for file pusher
