2024-01-26 17:34:42,256 INFO    StreamThr :3081779 [internal.py:wandb_internal():86] W&B internal server running at pid: 3081779, started at: 2024-01-26 17:34:42.255224
2024-01-26 17:34:42,296 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status
2024-01-26 17:34:42,300 INFO    WriterThread:3081779 [datastore.py:open_for_write():87] open: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-pl2g1lom/run-pl2g1lom.wandb
2024-01-26 17:34:42,300 DEBUG   SenderThread:3081779 [sender.py:send():382] send: header
2024-01-26 17:34:42,316 DEBUG   SenderThread:3081779 [sender.py:send():382] send: run
2024-01-26 17:34:45,393 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: check_version
2024-01-26 17:34:45,423 INFO    SenderThread:3081779 [dir_watcher.py:__init__():211] watching files in: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-pl2g1lom/files
2024-01-26 17:34:45,424 INFO    SenderThread:3081779 [sender.py:_start_run_threads():1136] run started: pl2g1lom with start time 1706261682.204884
2024-01-26 17:34:45,424 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: check_version
2024-01-26 17:34:45,978 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: run_start
2024-01-26 17:34:45,995 DEBUG   HandlerThread:3081779 [system_info.py:__init__():27] System info init
2024-01-26 17:34:45,995 DEBUG   HandlerThread:3081779 [system_info.py:__init__():42] System info init done
2024-01-26 17:34:45,996 INFO    HandlerThread:3081779 [system_monitor.py:start():194] Starting system monitor
2024-01-26 17:34:45,996 INFO    SystemMonitor:3081779 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-01-26 17:34:45,997 INFO    HandlerThread:3081779 [system_monitor.py:probe():214] Collecting system info
2024-01-26 17:34:46,065 INFO    SystemMonitor:3081779 [interfaces.py:start():190] Started cpu monitoring
2024-01-26 17:34:46,107 INFO    SystemMonitor:3081779 [interfaces.py:start():190] Started disk monitoring
2024-01-26 17:34:46,117 INFO    SystemMonitor:3081779 [interfaces.py:start():190] Started gpu monitoring
2024-01-26 17:34:46,161 INFO    SystemMonitor:3081779 [interfaces.py:start():190] Started memory monitoring
2024-01-26 17:34:46,185 INFO    SystemMonitor:3081779 [interfaces.py:start():190] Started network monitoring
2024-01-26 17:34:46,213 DEBUG   HandlerThread:3081779 [system_info.py:probe():151] Probing system
2024-01-26 17:34:46,247 DEBUG   HandlerThread:3081779 [system_info.py:_probe_git():136] Probing git
2024-01-26 17:34:46,319 DEBUG   HandlerThread:3081779 [system_info.py:_probe_git():144] Probing git done
2024-01-26 17:34:46,319 DEBUG   HandlerThread:3081779 [system_info.py:probe():199] Probing system done
2024-01-26 17:34:46,319 DEBUG   HandlerThread:3081779 [system_monitor.py:probe():223] {'os': 'Linux-5.15.0-91-generic-x86_64-with-glibc2.17', 'python': '3.8.17', 'heartbeatAt': '2024-01-26T09:34:46.213577', 'startedAt': '2024-01-26T09:34:42.180984', 'docker': None, 'cuda': None, 'args': ('--local_rank=5', '--config_file', 'config/bert_pretraining_phase2_config.json', '--input_dir', '/home/yanxindong/mkor/bert/data/encoded/sequences_lowercase_max_seq_len_512_next_seq_task_true', '--output_dir', 'results/adam', '--weight_decay', '0.01', '--num_steps_per_checkpoint', '200'), 'state': 'running', 'program': 'run_pretraining.py', 'codePathLocal': 'run_pretraining.py', 'codePath': 'bert/run_pretraining.py', 'git': {'remote': 'https://github.com/kkkjj-d/mkor.git', 'commit': 'efe99e84fef5594780cfb1df6d6a1f61da4ebba0'}, 'email': '1262670315@qq.com', 'root': '/home/yanxindong/mkor', 'host': 'a6000-X640-G40', 'username': 'yanxindong', 'executable': '/home/yanxindong/anaconda/envs/eva/bin/python', 'cpu_count': 64, 'cpu_count_logical': 128, 'cpu_freq': {'current': 1848.3833828125003, 'min': 800.0, 'max': 3400.0}, 'cpu_freq_per_core': [{'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2276.089, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2344.789, 'min': 800.0, 'max': 3400.0}, {'current': 2709.678, 'min': 800.0, 'max': 3400.0}, {'current': 2000.0, 'min': 800.0, 'max': 3400.0}, {'current': 1912.167, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 2692.91, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 2164.824, 'min': 800.0, 'max': 3400.0}, {'current': 1700.0, 'min': 800.0, 'max': 3400.0}, {'current': 1800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2092.909, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 2196.379, 'min': 800.0, 'max': 3400.0}, {'current': 2071.775, 'min': 800.0, 'max': 3400.0}, {'current': 1100.0, 'min': 800.0, 'max': 3400.0}, {'current': 2172.024, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2026.728, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3100.0, 'min': 800.0, 'max': 3400.0}, {'current': 2000.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1600.0, 'min': 800.0, 'max': 3400.0}, {'current': 2939.261, 'min': 800.0, 'max': 3400.0}, {'current': 2000.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 1900.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1929.579, 'min': 800.0, 'max': 3400.0}, {'current': 2522.545, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2573.865, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 2200.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2593.536, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2000.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 2369.135, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 2541.545, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 1800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 2000.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3254.444, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 2500.0, 'min': 800.0, 'max': 3400.0}, {'current': 900.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3114.275, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 3013.628, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 1100.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 1000.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 3300.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}, {'current': 800.0, 'min': 800.0, 'max': 3400.0}], 'disk': {'/': {'total': 438.05088806152344, 'used': 28.072593688964844}}, 'gpu': 'NVIDIA RTX A6000', 'gpu_count': 8, 'gpu_devices': [{'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}], 'memory': {'total': 503.51250076293945}}
2024-01-26 17:34:46,319 INFO    HandlerThread:3081779 [system_monitor.py:probe():224] Finished collecting system info
2024-01-26 17:34:46,319 INFO    HandlerThread:3081779 [system_monitor.py:probe():227] Publishing system info
2024-01-26 17:34:46,319 DEBUG   HandlerThread:3081779 [system_info.py:_save_conda():208] Saving list of conda packages installed into the current environment
2024-01-26 17:34:46,421 INFO    Thread-12 :3081779 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-pl2g1lom/files/conda-environment.yaml
2024-01-26 17:34:56,422 INFO    Thread-12 :3081779 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-pl2g1lom/files/conda-environment.yaml
2024-01-26 17:34:56,908 DEBUG   HandlerThread:3081779 [system_info.py:_save_conda():220] Saving conda packages done
2024-01-26 17:34:56,910 INFO    HandlerThread:3081779 [system_monitor.py:probe():229] Finished publishing system info
2024-01-26 17:34:56,916 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:34:56,941 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:34:56,942 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:34:56,942 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: keepalive
2024-01-26 17:34:56,942 DEBUG   SenderThread:3081779 [sender.py:send():382] send: files
2024-01-26 17:34:56,942 INFO    SenderThread:3081779 [sender.py:_save_file():1403] saving file wandb-metadata.json with policy now
2024-01-26 17:34:56,945 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: python_packages
2024-01-26 17:34:56,945 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: python_packages
2024-01-26 17:34:56,998 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:34:56,998 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:34:57,042 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:34:57,423 INFO    Thread-12 :3081779 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-pl2g1lom/files/requirements.txt
2024-01-26 17:34:57,423 INFO    Thread-12 :3081779 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-pl2g1lom/files/wandb-metadata.json
2024-01-26 17:34:57,500 ERROR   wandb-upload_0:3081779 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/pl2g1lom/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KaAumW5kzBlrRWvP6V3nBBlMLIxc0p7KYbBzJPYKScqD4CGXSpPZIwv5Oe0wJOTnpKFyCR7TkwDh3LmTR%2B%2BLBin0q1ZdAubiZB0vzJEVK%2FsmBmYL5SJXdrjLBFrdgpCZOcCYzx%2BjKjfl5B%2FRSA5SZ3K%2FV4vzXTaFCM6mAjdQp4dU2CfYOknNIHMcKw3uuW%2BgbmLuRY%2F4VfbCrzmGJgH9ZZZPJlZ7QEnSPyxAJr%2FSvjHqYPRVg84TOkHbBUdEf9XctqNbZNo9Cz%2FsXylsvR6vOWsFMYigrcpyy4kgrIrQOpeH%2BOypk%2FC3QSTtQdW3yVsND5vV9sPA02AwUj%2B%2BIkbPYQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/pl2g1lom/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KaAumW5kzBlrRWvP6V3nBBlMLIxc0p7KYbBzJPYKScqD4CGXSpPZIwv5Oe0wJOTnpKFyCR7TkwDh3LmTR%2B%2BLBin0q1ZdAubiZB0vzJEVK%2FsmBmYL5SJXdrjLBFrdgpCZOcCYzx%2BjKjfl5B%2FRSA5SZ3K%2FV4vzXTaFCM6mAjdQp4dU2CfYOknNIHMcKw3uuW%2BgbmLuRY%2F4VfbCrzmGJgH9ZZZPJlZ7QEnSPyxAJr%2FSvjHqYPRVg84TOkHbBUdEf9XctqNbZNo9Cz%2FsXylsvR6vOWsFMYigrcpyy4kgrIrQOpeH%2BOypk%2FC3QSTtQdW3yVsND5vV9sPA02AwUj%2B%2BIkbPYQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f62f0367cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:34:57,501 ERROR   wandb-upload_0:3081779 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15659'}
2024-01-26 17:34:57,501 ERROR   wandb-upload_0:3081779 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:34:57,667 DEBUG   SenderThread:3081779 [sender.py:send():382] send: telemetry
2024-01-26 17:34:58,549 ERROR   wandb-upload_0:3081779 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/pl2g1lom/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KaAumW5kzBlrRWvP6V3nBBlMLIxc0p7KYbBzJPYKScqD4CGXSpPZIwv5Oe0wJOTnpKFyCR7TkwDh3LmTR%2B%2BLBin0q1ZdAubiZB0vzJEVK%2FsmBmYL5SJXdrjLBFrdgpCZOcCYzx%2BjKjfl5B%2FRSA5SZ3K%2FV4vzXTaFCM6mAjdQp4dU2CfYOknNIHMcKw3uuW%2BgbmLuRY%2F4VfbCrzmGJgH9ZZZPJlZ7QEnSPyxAJr%2FSvjHqYPRVg84TOkHbBUdEf9XctqNbZNo9Cz%2FsXylsvR6vOWsFMYigrcpyy4kgrIrQOpeH%2BOypk%2FC3QSTtQdW3yVsND5vV9sPA02AwUj%2B%2BIkbPYQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/pl2g1lom/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KaAumW5kzBlrRWvP6V3nBBlMLIxc0p7KYbBzJPYKScqD4CGXSpPZIwv5Oe0wJOTnpKFyCR7TkwDh3LmTR%2B%2BLBin0q1ZdAubiZB0vzJEVK%2FsmBmYL5SJXdrjLBFrdgpCZOcCYzx%2BjKjfl5B%2FRSA5SZ3K%2FV4vzXTaFCM6mAjdQp4dU2CfYOknNIHMcKw3uuW%2BgbmLuRY%2F4VfbCrzmGJgH9ZZZPJlZ7QEnSPyxAJr%2FSvjHqYPRVg84TOkHbBUdEf9XctqNbZNo9Cz%2FsXylsvR6vOWsFMYigrcpyy4kgrIrQOpeH%2BOypk%2FC3QSTtQdW3yVsND5vV9sPA02AwUj%2B%2BIkbPYQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f62f033d520>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:34:58,549 ERROR   wandb-upload_0:3081779 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15659'}
2024-01-26 17:34:58,549 ERROR   wandb-upload_0:3081779 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:34:58,668 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:35:00,582 ERROR   wandb-upload_0:3081779 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/pl2g1lom/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KaAumW5kzBlrRWvP6V3nBBlMLIxc0p7KYbBzJPYKScqD4CGXSpPZIwv5Oe0wJOTnpKFyCR7TkwDh3LmTR%2B%2BLBin0q1ZdAubiZB0vzJEVK%2FsmBmYL5SJXdrjLBFrdgpCZOcCYzx%2BjKjfl5B%2FRSA5SZ3K%2FV4vzXTaFCM6mAjdQp4dU2CfYOknNIHMcKw3uuW%2BgbmLuRY%2F4VfbCrzmGJgH9ZZZPJlZ7QEnSPyxAJr%2FSvjHqYPRVg84TOkHbBUdEf9XctqNbZNo9Cz%2FsXylsvR6vOWsFMYigrcpyy4kgrIrQOpeH%2BOypk%2FC3QSTtQdW3yVsND5vV9sPA02AwUj%2B%2BIkbPYQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/pl2g1lom/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KaAumW5kzBlrRWvP6V3nBBlMLIxc0p7KYbBzJPYKScqD4CGXSpPZIwv5Oe0wJOTnpKFyCR7TkwDh3LmTR%2B%2BLBin0q1ZdAubiZB0vzJEVK%2FsmBmYL5SJXdrjLBFrdgpCZOcCYzx%2BjKjfl5B%2FRSA5SZ3K%2FV4vzXTaFCM6mAjdQp4dU2CfYOknNIHMcKw3uuW%2BgbmLuRY%2F4VfbCrzmGJgH9ZZZPJlZ7QEnSPyxAJr%2FSvjHqYPRVg84TOkHbBUdEf9XctqNbZNo9Cz%2FsXylsvR6vOWsFMYigrcpyy4kgrIrQOpeH%2BOypk%2FC3QSTtQdW3yVsND5vV9sPA02AwUj%2B%2BIkbPYQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f62f0346a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:35:00,582 ERROR   wandb-upload_0:3081779 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15659'}
2024-01-26 17:35:00,582 ERROR   wandb-upload_0:3081779 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:35:00,582 INFO    wandb-upload_0:3081779 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f62f0346a90>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/pl2g1lom/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KaAumW5kzBlrRWvP6V3nBBlMLIxc0p7KYbBzJPYKScqD4CGXSpPZIwv5Oe0wJOTnpKFyCR7TkwDh3LmTR%2B%2BLBin0q1ZdAubiZB0vzJEVK%2FsmBmYL5SJXdrjLBFrdgpCZOcCYzx%2BjKjfl5B%2FRSA5SZ3K%2FV4vzXTaFCM6mAjdQp4dU2CfYOknNIHMcKw3uuW%2BgbmLuRY%2F4VfbCrzmGJgH9ZZZPJlZ7QEnSPyxAJr%2FSvjHqYPRVg84TOkHbBUdEf9XctqNbZNo9Cz%2FsXylsvR6vOWsFMYigrcpyy4kgrIrQOpeH%2BOypk%2FC3QSTtQdW3yVsND5vV9sPA02AwUj%2B%2BIkbPYQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f62f0346a90>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/pl2g1lom/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KaAumW5kzBlrRWvP6V3nBBlMLIxc0p7KYbBzJPYKScqD4CGXSpPZIwv5Oe0wJOTnpKFyCR7TkwDh3LmTR%2B%2BLBin0q1ZdAubiZB0vzJEVK%2FsmBmYL5SJXdrjLBFrdgpCZOcCYzx%2BjKjfl5B%2FRSA5SZ3K%2FV4vzXTaFCM6mAjdQp4dU2CfYOknNIHMcKw3uuW%2BgbmLuRY%2F4VfbCrzmGJgH9ZZZPJlZ7QEnSPyxAJr%2FSvjHqYPRVg84TOkHbBUdEf9XctqNbZNo9Cz%2FsXylsvR6vOWsFMYigrcpyy4kgrIrQOpeH%2BOypk%2FC3QSTtQdW3yVsND5vV9sPA02AwUj%2B%2BIkbPYQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f62f0346a90>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2789, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yanxindong/anaconda/envs/eva/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-01-26 17:35:03,669 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:35:04,662 ERROR   wandb-upload_0:3081779 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/pl2g1lom/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KaAumW5kzBlrRWvP6V3nBBlMLIxc0p7KYbBzJPYKScqD4CGXSpPZIwv5Oe0wJOTnpKFyCR7TkwDh3LmTR%2B%2BLBin0q1ZdAubiZB0vzJEVK%2FsmBmYL5SJXdrjLBFrdgpCZOcCYzx%2BjKjfl5B%2FRSA5SZ3K%2FV4vzXTaFCM6mAjdQp4dU2CfYOknNIHMcKw3uuW%2BgbmLuRY%2F4VfbCrzmGJgH9ZZZPJlZ7QEnSPyxAJr%2FSvjHqYPRVg84TOkHbBUdEf9XctqNbZNo9Cz%2FsXylsvR6vOWsFMYigrcpyy4kgrIrQOpeH%2BOypk%2FC3QSTtQdW3yVsND5vV9sPA02AwUj%2B%2BIkbPYQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/pl2g1lom/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KaAumW5kzBlrRWvP6V3nBBlMLIxc0p7KYbBzJPYKScqD4CGXSpPZIwv5Oe0wJOTnpKFyCR7TkwDh3LmTR%2B%2BLBin0q1ZdAubiZB0vzJEVK%2FsmBmYL5SJXdrjLBFrdgpCZOcCYzx%2BjKjfl5B%2FRSA5SZ3K%2FV4vzXTaFCM6mAjdQp4dU2CfYOknNIHMcKw3uuW%2BgbmLuRY%2F4VfbCrzmGJgH9ZZZPJlZ7QEnSPyxAJr%2FSvjHqYPRVg84TOkHbBUdEf9XctqNbZNo9Cz%2FsXylsvR6vOWsFMYigrcpyy4kgrIrQOpeH%2BOypk%2FC3QSTtQdW3yVsND5vV9sPA02AwUj%2B%2BIkbPYQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f62f0346640>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:35:04,662 ERROR   wandb-upload_0:3081779 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15659'}
2024-01-26 17:35:04,662 ERROR   wandb-upload_0:3081779 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:35:08,669 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:35:11,998 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:35:11,998 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:35:12,046 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:35:13,430 ERROR   wandb-upload_0:3081779 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/pl2g1lom/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KaAumW5kzBlrRWvP6V3nBBlMLIxc0p7KYbBzJPYKScqD4CGXSpPZIwv5Oe0wJOTnpKFyCR7TkwDh3LmTR%2B%2BLBin0q1ZdAubiZB0vzJEVK%2FsmBmYL5SJXdrjLBFrdgpCZOcCYzx%2BjKjfl5B%2FRSA5SZ3K%2FV4vzXTaFCM6mAjdQp4dU2CfYOknNIHMcKw3uuW%2BgbmLuRY%2F4VfbCrzmGJgH9ZZZPJlZ7QEnSPyxAJr%2FSvjHqYPRVg84TOkHbBUdEf9XctqNbZNo9Cz%2FsXylsvR6vOWsFMYigrcpyy4kgrIrQOpeH%2BOypk%2FC3QSTtQdW3yVsND5vV9sPA02AwUj%2B%2BIkbPYQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/pl2g1lom/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KaAumW5kzBlrRWvP6V3nBBlMLIxc0p7KYbBzJPYKScqD4CGXSpPZIwv5Oe0wJOTnpKFyCR7TkwDh3LmTR%2B%2BLBin0q1ZdAubiZB0vzJEVK%2FsmBmYL5SJXdrjLBFrdgpCZOcCYzx%2BjKjfl5B%2FRSA5SZ3K%2FV4vzXTaFCM6mAjdQp4dU2CfYOknNIHMcKw3uuW%2BgbmLuRY%2F4VfbCrzmGJgH9ZZZPJlZ7QEnSPyxAJr%2FSvjHqYPRVg84TOkHbBUdEf9XctqNbZNo9Cz%2FsXylsvR6vOWsFMYigrcpyy4kgrIrQOpeH%2BOypk%2FC3QSTtQdW3yVsND5vV9sPA02AwUj%2B%2BIkbPYQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f62f033d610>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:35:13,431 ERROR   wandb-upload_0:3081779 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15659'}
2024-01-26 17:35:13,431 ERROR   wandb-upload_0:3081779 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:35:14,899 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:35:17,429 INFO    Thread-12 :3081779 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-pl2g1lom/files/config.yaml
2024-01-26 17:35:21,610 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:35:26,647 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:35:26,998 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:35:26,999 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:35:27,046 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:35:30,302 ERROR   wandb-upload_0:3081779 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/pl2g1lom/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KaAumW5kzBlrRWvP6V3nBBlMLIxc0p7KYbBzJPYKScqD4CGXSpPZIwv5Oe0wJOTnpKFyCR7TkwDh3LmTR%2B%2BLBin0q1ZdAubiZB0vzJEVK%2FsmBmYL5SJXdrjLBFrdgpCZOcCYzx%2BjKjfl5B%2FRSA5SZ3K%2FV4vzXTaFCM6mAjdQp4dU2CfYOknNIHMcKw3uuW%2BgbmLuRY%2F4VfbCrzmGJgH9ZZZPJlZ7QEnSPyxAJr%2FSvjHqYPRVg84TOkHbBUdEf9XctqNbZNo9Cz%2FsXylsvR6vOWsFMYigrcpyy4kgrIrQOpeH%2BOypk%2FC3QSTtQdW3yVsND5vV9sPA02AwUj%2B%2BIkbPYQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/pl2g1lom/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KaAumW5kzBlrRWvP6V3nBBlMLIxc0p7KYbBzJPYKScqD4CGXSpPZIwv5Oe0wJOTnpKFyCR7TkwDh3LmTR%2B%2BLBin0q1ZdAubiZB0vzJEVK%2FsmBmYL5SJXdrjLBFrdgpCZOcCYzx%2BjKjfl5B%2FRSA5SZ3K%2FV4vzXTaFCM6mAjdQp4dU2CfYOknNIHMcKw3uuW%2BgbmLuRY%2F4VfbCrzmGJgH9ZZZPJlZ7QEnSPyxAJr%2FSvjHqYPRVg84TOkHbBUdEf9XctqNbZNo9Cz%2FsXylsvR6vOWsFMYigrcpyy4kgrIrQOpeH%2BOypk%2FC3QSTtQdW3yVsND5vV9sPA02AwUj%2B%2BIkbPYQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f62f03469d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:35:30,303 ERROR   wandb-upload_0:3081779 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15659'}
2024-01-26 17:35:30,303 ERROR   wandb-upload_0:3081779 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:35:32,433 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:35:37,434 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:35:41,998 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:35:41,999 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:35:42,042 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:35:43,334 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:35:46,186 DEBUG   SystemMonitor:3081779 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-01-26 17:35:46,189 DEBUG   SenderThread:3081779 [sender.py:send():382] send: stats
2024-01-26 17:35:49,191 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:35:54,192 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:35:56,998 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:35:56,999 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:35:57,042 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:35:59,311 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:36:04,322 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:36:04,680 ERROR   wandb-upload_0:3081779 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/dynamic_x/bert_pytorch/pl2g1lom/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KaAumW5kzBlrRWvP6V3nBBlMLIxc0p7KYbBzJPYKScqD4CGXSpPZIwv5Oe0wJOTnpKFyCR7TkwDh3LmTR%2B%2BLBin0q1ZdAubiZB0vzJEVK%2FsmBmYL5SJXdrjLBFrdgpCZOcCYzx%2BjKjfl5B%2FRSA5SZ3K%2FV4vzXTaFCM6mAjdQp4dU2CfYOknNIHMcKw3uuW%2BgbmLuRY%2F4VfbCrzmGJgH9ZZZPJlZ7QEnSPyxAJr%2FSvjHqYPRVg84TOkHbBUdEf9XctqNbZNo9Cz%2FsXylsvR6vOWsFMYigrcpyy4kgrIrQOpeH%2BOypk%2FC3QSTtQdW3yVsND5vV9sPA02AwUj%2B%2BIkbPYQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/dynamic_x/bert_pytorch/pl2g1lom/wandb-metadata.json?Expires=1706348097&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KaAumW5kzBlrRWvP6V3nBBlMLIxc0p7KYbBzJPYKScqD4CGXSpPZIwv5Oe0wJOTnpKFyCR7TkwDh3LmTR%2B%2BLBin0q1ZdAubiZB0vzJEVK%2FsmBmYL5SJXdrjLBFrdgpCZOcCYzx%2BjKjfl5B%2FRSA5SZ3K%2FV4vzXTaFCM6mAjdQp4dU2CfYOknNIHMcKw3uuW%2BgbmLuRY%2F4VfbCrzmGJgH9ZZZPJlZ7QEnSPyxAJr%2FSvjHqYPRVg84TOkHbBUdEf9XctqNbZNo9Cz%2FsXylsvR6vOWsFMYigrcpyy4kgrIrQOpeH%2BOypk%2FC3QSTtQdW3yVsND5vV9sPA02AwUj%2B%2BIkbPYQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f62f028a790>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-26 17:36:04,680 ERROR   wandb-upload_0:3081779 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15659'}
2024-01-26 17:36:04,680 ERROR   wandb-upload_0:3081779 [internal_api.py:upload_file():2769] upload_file response body: 
2024-01-26 17:36:09,332 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:36:11,999 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:36:11,999 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:36:12,042 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:36:14,408 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:36:16,191 DEBUG   SenderThread:3081779 [sender.py:send():382] send: stats
2024-01-26 17:36:20,192 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:36:25,193 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:36:26,999 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:36:26,999 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:36:27,042 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:36:30,301 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:36:32,540 INFO    Thread-12 :3081779 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-pl2g1lom/files/output.log
2024-01-26 17:36:34,540 INFO    Thread-12 :3081779 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-pl2g1lom/files/output.log
2024-01-26 17:36:36,149 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:36:41,150 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:36:45,560 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:36:45,561 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:36:45,561 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:36:46,192 DEBUG   SenderThread:3081779 [sender.py:send():382] send: stats
2024-01-26 17:36:46,195 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:36:52,508 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:36:57,606 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:37:00,558 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:37:00,558 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:37:00,562 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:37:02,869 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:37:07,900 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:37:12,986 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:37:15,559 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:37:15,560 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:37:15,602 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:37:16,194 DEBUG   SenderThread:3081779 [sender.py:send():382] send: stats
2024-01-26 17:37:18,245 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:37:23,246 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:37:26,029 INFO    wandb-upload_0:3081779 [upload_job.py:push():131] Uploaded file /tmp/tmpmiq1h_63wandb/3oy7n2vb-wandb-metadata.json
2024-01-26 17:37:28,326 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:37:30,654 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:37:30,654 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:37:30,654 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:37:33,949 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:37:38,949 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:37:43,950 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:37:45,558 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:37:45,559 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:37:45,563 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:37:46,197 DEBUG   SenderThread:3081779 [sender.py:send():382] send: stats
2024-01-26 17:37:49,199 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:37:54,199 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:37:59,200 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:38:00,558 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:38:00,559 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:38:00,602 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:38:04,889 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:38:10,068 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:38:15,079 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:38:15,559 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:38:15,559 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:38:15,602 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:38:16,199 DEBUG   SenderThread:3081779 [sender.py:send():382] send: stats
2024-01-26 17:38:20,201 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:38:25,248 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:38:30,326 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:38:30,670 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:38:30,670 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:38:30,670 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:38:36,038 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:38:41,039 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:38:45,560 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:38:45,560 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:38:45,563 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:38:46,201 DEBUG   SenderThread:3081779 [sender.py:send():382] send: stats
2024-01-26 17:38:46,204 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:38:51,203 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:38:56,203 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:39:00,560 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:39:00,560 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:39:00,602 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:39:01,877 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:39:06,878 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:39:11,879 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:39:15,560 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:39:15,560 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:39:15,602 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:39:16,204 DEBUG   SenderThread:3081779 [sender.py:send():382] send: stats
2024-01-26 17:39:17,206 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:39:22,206 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:39:27,214 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:39:30,560 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:39:30,561 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:39:30,618 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:39:32,988 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:39:38,154 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:39:43,190 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:39:45,560 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:39:45,560 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:39:45,602 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:39:46,211 DEBUG   SenderThread:3081779 [sender.py:send():382] send: stats
2024-01-26 17:39:48,275 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:39:53,428 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:39:58,569 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:40:00,560 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:40:00,561 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:40:00,602 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:40:03,874 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:40:08,874 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:40:13,875 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:40:15,560 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:40:15,561 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:40:15,602 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:40:16,214 DEBUG   SenderThread:3081779 [sender.py:send():382] send: stats
2024-01-26 17:40:19,215 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:40:24,216 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:40:29,216 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:40:30,560 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:40:30,561 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:40:30,602 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:40:34,915 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:40:39,977 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:40:44,981 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:40:45,560 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:40:45,561 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:40:45,602 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:40:46,221 DEBUG   SenderThread:3081779 [sender.py:send():382] send: stats
2024-01-26 17:40:50,286 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:40:55,370 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:41:00,482 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:41:00,561 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:41:00,561 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:41:00,602 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:41:06,027 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:41:11,028 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:41:15,561 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:41:15,561 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:41:15,602 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:41:16,219 DEBUG   SenderThread:3081779 [sender.py:send():382] send: stats
2024-01-26 17:41:16,220 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:41:21,221 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:41:26,222 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:41:30,561 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:41:30,561 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:41:30,602 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:41:31,858 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:41:36,910 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:41:41,922 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:41:45,561 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:41:45,561 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:41:45,602 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:41:46,220 DEBUG   SenderThread:3081779 [sender.py:send():382] send: stats
2024-01-26 17:41:47,222 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:41:52,293 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:41:57,293 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:42:00,561 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:42:00,561 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:42:00,602 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:42:02,883 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:42:07,884 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:42:12,885 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:42:15,561 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:42:15,561 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:42:15,602 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:42:16,224 DEBUG   SenderThread:3081779 [sender.py:send():382] send: stats
2024-01-26 17:42:18,225 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:42:23,226 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:42:28,226 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:42:30,561 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:42:30,561 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:42:30,602 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:42:33,926 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:42:39,019 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:42:44,034 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:42:45,561 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:42:45,562 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:42:45,602 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:42:46,236 DEBUG   SenderThread:3081779 [sender.py:send():382] send: stats
2024-01-26 17:42:49,266 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:42:54,278 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:42:59,289 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:43:00,561 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: stop_status
2024-01-26 17:43:00,562 DEBUG   SenderThread:3081779 [sender.py:send_request():409] send_request: stop_status
2024-01-26 17:43:00,602 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-26 17:43:04,829 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:43:09,830 DEBUG   HandlerThread:3081779 [handler.py:handle_request():146] handle_request: status_report
2024-01-26 17:43:10,521 INFO    memory    :3081779 [interfaces.py:monitor():140] Process proc.memory.rssMB has exited.
2024-01-26 17:43:10,522 DEBUG   SystemMonitor:3081779 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-01-26 17:43:10,522 DEBUG   SystemMonitor:3081779 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-01-26 17:43:10,525 DEBUG   SenderThread:3081779 [sender.py:send():382] send: stats
2024-01-26 17:43:10,587 WARNING StreamThr :3081779 [internal.py:is_dead():414] Internal process exiting, parent pid 3081502 disappeared
2024-01-26 17:43:10,587 ERROR   StreamThr :3081779 [internal.py:wandb_internal():152] Internal process shutdown.
2024-01-26 17:43:11,524 INFO    HandlerThread:3081779 [handler.py:finish():869] shutting down handler
2024-01-26 17:43:11,525 INFO    HandlerThread:3081779 [system_monitor.py:finish():203] Stopping system monitor
2024-01-26 17:43:11,525 INFO    HandlerThread:3081779 [interfaces.py:finish():202] Joined cpu monitor
2024-01-26 17:43:11,525 INFO    HandlerThread:3081779 [interfaces.py:finish():202] Joined disk monitor
2024-01-26 17:43:11,525 INFO    HandlerThread:3081779 [interfaces.py:finish():202] Joined gpu monitor
2024-01-26 17:43:11,525 INFO    HandlerThread:3081779 [interfaces.py:finish():202] Joined memory monitor
2024-01-26 17:43:11,525 INFO    HandlerThread:3081779 [interfaces.py:finish():202] Joined network monitor
2024-01-26 17:43:11,526 INFO    WriterThread:3081779 [datastore.py:close():296] close: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-pl2g1lom/run-pl2g1lom.wandb
2024-01-26 17:43:11,526 INFO    SenderThread:3081779 [sender.py:finish():1572] shutting down sender
2024-01-26 17:43:12,524 INFO    SenderThread:3081779 [dir_watcher.py:finish():358] shutting down directory watcher
2024-01-26 17:43:12,584 INFO    MainThread:3081779 [internal.py:handle_exit():76] Internal process exited
2024-01-26 17:43:12,585 INFO    SenderThread:3081779 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-pl2g1lom/files/output.log
2024-01-26 17:43:12,585 INFO    SenderThread:3081779 [dir_watcher.py:finish():388] scan: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-pl2g1lom/files
2024-01-26 17:43:12,586 INFO    SenderThread:3081779 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-pl2g1lom/files/conda-environment.yaml conda-environment.yaml
2024-01-26 17:43:12,586 INFO    SenderThread:3081779 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-pl2g1lom/files/wandb-metadata.json wandb-metadata.json
2024-01-26 17:43:12,586 INFO    SenderThread:3081779 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-pl2g1lom/files/output.log output.log
2024-01-26 17:43:12,586 INFO    SenderThread:3081779 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-pl2g1lom/files/requirements.txt requirements.txt
2024-01-26 17:43:12,586 INFO    SenderThread:3081779 [dir_watcher.py:finish():402] scan save: /home/yanxindong/mkor/bert/wandb/run-20240126_173442-pl2g1lom/files/config.yaml config.yaml
2024-01-26 17:43:12,586 INFO    SenderThread:3081779 [file_pusher.py:finish():175] shutting down file pusher
2024-01-26 17:43:12,586 INFO    SenderThread:3081779 [file_pusher.py:join():181] waiting for file pusher
2024-01-26 17:43:13,877 INFO    wandb-upload_1:3081779 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_173442-pl2g1lom/files/output.log
2024-01-26 17:43:15,276 INFO    wandb-upload_3:3081779 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_173442-pl2g1lom/files/config.yaml
2024-01-26 17:43:15,772 INFO    wandb-upload_0:3081779 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_173442-pl2g1lom/files/conda-environment.yaml
2024-01-26 17:43:15,920 INFO    wandb-upload_2:3081779 [upload_job.py:push():131] Uploaded file /home/yanxindong/mkor/bert/wandb/run-20240126_173442-pl2g1lom/files/requirements.txt
